### ISSUE TITLE
How to I get access to orgs?

### ISSUE THREAD

**Issue by jessieay** [cloud-gov/cg-site#100]
Working on a Slack bot that I will deploy to Cloud Foundry. From what I've read on the docs, seems like this should be a part of the `devops` org within CF (since that is where Hubot lives) - is that right? If so, how do I get access to the`devops` org?

**Comment by ozzyjohnson** [comment]
@jessieay - Typically via an issue in https://github.com/18F/DevOps

**Comment by jessieay** [comment]
This is resolved. Closing.
