### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#101]
The name isn't super clear...how about `cloud-foundry-docs` or `docs.18f.gov`?

**Comment by jessieay** [comment]
I like the idea of having naming consistency between 18F sites and their GitHub repos! Also, this one in particular was hard for me to find as a newb.

**Comment by dlapiduz** [comment]
@afeld I am thinking of changing some of the repos to be less dependent on the "cloud foundry" brand and be more about "cloud.gov". The problem is that "cloud.gov" doesn't really exist yet, so I am kind of waiting on that. Does that make sense?

**Comment by afeld** [comment]
Sounds good.
