### ISSUE TITLE
Updates haven't updated since May

### ISSUE THREAD

**Issue by melodykramer** [cloud-gov/cg-site#105]
Is this supposed to be pulling from somewhere else?

https://docs.18f.gov/updates/2015-05-29/

It hasn't updated in a number of months.

**Comment by mogul** [comment]
You're right... We've just started to publicize regular updates on https://cloud.18f.gov (soon to be https://cloud.gov), and old updates you see on docs.18f.gov are a holdover that should be migrated or removed. Unfortunately we just lost the link to the updates page when we changed to the Federalist template, so they're not showing up there. I will look into that shortly.

**Comment by mogul** [comment]
See in particular [the posts on Diego's branch](https://github.com/18F/cf-landing/tree/sbst-template/_posts)... Feel free to add to that directory if you'd like to help. :)

**Comment by wslack** [comment]
What's the status of this now that it lives at docs.cloud.gov? cc @dlapiduz

**Comment by dlapiduz** [comment]
@wslack we are going to move the updates to https://cloud.gov/updates. This section is deprecated...

**Comment by afeld** [comment]
Corresponds to https://github.com/18F/cg-landing/issues/18.
