### ISSUE TITLE
typo on front page

### ISSUE THREAD

**Issue by melodykramer** [cloud-gov/cg-site#107]
Saw this [tweet](https://twitter.com/iandees/status/649725029895114752)

This paragraph: Develop, run, and manage web applications without the complexity and cost of building and maintaining infrastructure. Focus precious team effort in improving your service! 

on the main page should read:

Develop, run, and manage web applications without the complexity and cost of building and maintaining infrastructure. Focus precious team effort **on** improving your service!

**Comment by melodykramer** [comment]
oops - thought this was the repo for cloud.18f.gov - where is that one?

**Comment by mogul** [comment]
https://github.com/18F/cf-landing

**Comment by mogul** [comment]
(Also, that's already fixed on the sbst-template branch, but not yet deployed. See also [Hillary's issue with various niggles](https://github.com/18F/cf-landing/issues/16), which we've not yet addressed.)
