### ISSUE TITLE
rename again?

### ISSUE THREAD

**Issue by jessieay** [cloud-gov/cg-site#119]
Hey - this repo was recently renamed, but it is still hard to find. When I was searching for it within the 18F org on github, I searched "cloud" "cloudfoundry" and "cloudgov" but it didn't come up. Perhaps `cloud-gov-docs` would be a better and more findable name?

**Comment by dlapiduz** [comment]
@jessieay we are trying to group all the cloud.gov repos under the `cg-` prefix... it might make it a bit harder to find but there is a link in docs.cloud.gov. Maybe we can make it more prominent?

**Comment by jessieay** [comment]
How many cloud.gov repos are there? I think prefixes can be helpful, but only necessary in cases where there are many related repos. 

My use case is that I was on `docs.18f.gov` and saw something I wanted to change. I then went to https://github.com/18F and searched for the related repo by typing in "cloud" "cloudfoundry" and "cloudgov"

Another way to make the connection between the site and source would be to rename https://docs.18f.gov/ to https://cg-docs.18f.gov/ - I've always felt like having the cloud.gov docs at the `docs` subdomain was a bit odd. Thoughts?

**Comment by dlapiduz** [comment]
@jessieay we currently have docs.18f.gov for legacy purposes. We will retire it some time in favor of docs.cloud.gov.

**Comment by dlapiduz** [comment]
@jessieay we have about 25 repos for cloud.gov and the number is only growing. That is why we are trying to prefix everything...

**Comment by jessieay** [comment]
Makes sense! (re: naming convention / # of repos). I wasn't aware there were so many.

`docs.cloud.gov` will be a much better url! 

closing this issue

**Comment by mogul** [comment]
(Just to be clear, cloud.docs.gov is already up, and is considered the canonical URL... It's what cloud.gov links to under "Documentation".)

**Comment by jessieay** [comment]
Ok - I think I first visited docs.18f.gov via a new hire checklist that told me to go there to get started with CF, but I am no longer sure where that checklist was.
