### ISSUE TITLE
User management not working as expected in Firefox

### ISSUE THREAD

**Issue by froi** [cloud-gov/cg-site#1214]
Hello,

I hope this is the correct repo to report this.

Checkboxes to manage user roles are not appearing when using Firefox but are in Chrome:

__Firefox v. 58.0.2__
![image](https://user-images.githubusercontent.com/1918027/36990487-dc8857e4-2072-11e8-9bf8-c32ab5e5cb3e.png)

__Chrome v. 64.0.3282.186__
![image](https://user-images.githubusercontent.com/1918027/36990544-102af476-2073-11e8-9a8f-42fd1950b927.png)

The element appears in the Firefox inspector:
![image](https://user-images.githubusercontent.com/1918027/36990901-09548d78-2074-11e8-853c-cb0ac4f665b1.png)

I think the `|` that are being rendered are supposed to be checkboxes.

Thanks for all the hard work!

**Comment by brittag** [comment]
Thanks for reporting this - we'll poke around at what's happening here. The codebase for that is technically over at https://github.com/18F/cg-dashboard, but filing an issue here is totally fine too.

**Comment by froi** [comment]
Great to know @brittag. If you'd prefer I can open an issue in the cg-dashboard repo and close this one. 

Up to you :). Thanks

**Comment by mogul** [comment]
We're planning to push the existing dashboard into the 🌋soon; closing this issue as we won't be fixing it.
