### ISSUE TITLE
document how to deploy a Node app

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#13]
/cc @adelevie @ultrasaurus

**Comment by adelevie** [comment]
The thing where you need to ensure a start script is in `package.json`...

**Comment by afeld** [comment]
http://docs.cloudfoundry.org/buildpacks/node/

**Comment by ozzyjohnson** [comment]
Just added a doc on service instances which uses node in a few examples pulled from my experience deploying Beckley on Friday.

https://github.com/18F/cloud-foundry-notes/tree/accessing-v1-managed-services

**Comment by afeld** [comment]
@ozzyjohnson Feel free to create a `[WIP]` PR so that others can see it more easily and give any initial feedback!

**Comment by afeld** [comment]
:boom: https://docs.cloud.gov/apps/node/
