### ISSUE TITLE
Is there a place where we can look up on average ATO approval process timeframes?

### ISSUE THREAD

**Issue by 2chang** [cloud-gov/cg-site#1329]
I was attempting to look up how long the ATO process would take on a system, given the system is in a IaaS Government Cloud environment already?

**Comment by pburkholder** [comment]
Hi - interesting question!  Frankly, the ATO process is too dependent on how agencies approach it for us to generalize. Can you email us at cloud-gov-inquiries@gsa.gov and we'll help you with your specifics?

Cheers, Peter 

Also, you might want to read this to see what can map to your situation: https://18f.gsa.gov/2018/07/19/taking-the-ato-process-from-6-months-to-30-days/

**Comment by mogul** [comment]
You might also want to check out:
https://cloud.gov/docs/compliance/ato-process/

**Comment by 2chang** [comment]
Thank you both for the assistance on this end and I have been able to read through both. 

I wasn't sure if anyone here had experience or knew of the NIH ATO Cloud process. Our application is cloud based and currently sits in an government infrastructure (Network, metal, and data center) that are FedRamped so we will have to get an ATO for the actual application. As Peter so kindly mentioned above that each agency has different approaches but I just wanted to ask in case anyone here may know. 

Thanks again for the assistance and have a great weekend! 

Best Regards,
Will

**Comment by pburkholder** [comment]
This summer we've started working with an NIH customer who may be available to work with you on answering some of the NIH specific questions. Please contact us at cloud-gov-inquiries@gsa.gov and we'll put you in touch with them

Thanks, Peter
