### ISSUE TITLE
What are some of the tools and processes cloud.gov customers use to implement CI/CD pipelines for their cloud.gov apps? Does cloud.gov provide a solution as a service?

### ISSUE THREAD

**Issue by cx-ben-stokes** [cloud-gov/cg-site#1336]

**Comment by brittag** [comment]
Hi @benjaminstokes! Apologies for not getting to your question earlier. cloud.gov does not have a built-in CI/CD tool for customers. Customers can use any CI/CD tool of their choice - see https://cloud.gov/docs/apps/continuous-deployment/ for a few examples of how customers may configure this, including for Jenkins, Travis CI, and CircleCI. Happy to answer in more detail if that page doesn't have everything you're interested in. We're curious, why do you ask? Are you working on a similar project, or interested in using cloud.gov for something?
