### ISSUE TITLE
documentation on how we set up a password for kibana proxy in VCAP services

### ISSUE THREAD

**Issue by ultrasaurus** [cloud-gov/cg-site#134]
we use user-provided credentials in ED, would be good to document how to do this for other projects

```
cf env myapp
```

results in

```
 "user-provided": [
   {
    "credentials": {
     "password": "xxxxxx",
     "username": "kibana-user"
    },
    "label": "user-provided",
    "name": "elk-credentials",
    "syslog_drain_url": "",
    "tags": []
   },
```

**Comment by ozzyjohnson** [comment]
@ultrasaurus - I could certainly add a step for the addition of generated credential pair via `cf cups` to the durable logging doc. Is that what you're thinking?

**Comment by mogul** [comment]
I think it'd be a generally useful article in its own right... The
technique is not specific to ELK.

**Comment by ozzyjohnson** [comment]
I thought we had something for this on the docs site. Probably deserves to be highlighted in any case. I'll take it as a thing to do and perhaps pair on.

**Comment by brittag** [comment]
https://cloud.gov/docs/apps/production-ready/#protect-access-to-sensitive-credentials explains "Environment variables defined with cf set-env are ephemeral to the specific deployment of each application. Use user-provided services to store sensitive information such as credentials or API keys, and use your manifest.yml for non-sensitive variables."
