### ISSUE TITLE
Search button doesn’t do anything.

### ISSUE THREAD

**Issue by adunkman** [cloud-gov/cg-site#1354]
In Chrome 70.0.3538.102, the search button doesn’t seem to do anything:

![Screen recording showing Chrome browser window with a mouse clicking repeatedly on the cloud.gov search icon, only to curse away disappointedly.](https://user-images.githubusercontent.com/14930/48870273-296e7f80-edae-11e8-9f9e-c5587701a2ec.gif)

**Comment by mogul** [comment]
Doh! Sorry about that... I noticed that in passing but forgot to follow up and get it fixed. Please use [this link](https://search.usa.gov/search?affiliate=cloud.gov) directly to search.usa.gov in the meantime.

**Comment by adunkman** [comment]
Following up from Slack, @mgwalker and I are both at a loss as to where that `display: none` on `@media screen and (min-width: 600px) { .usa-nav-secondary .usa-search {}}` is coming from, and I’m having some issues getting node-sass compiled on my machine. I’d probably generate a sourcemap to see where it comes from — the sass imports include three or four different projects, so it’s too hard to figure it out on my own. 

Alternatively, to fix production while we figure this out, throw a gross patch somewhere: 

```scss
@media screen and (min-width: 600px) {
  .usa-nav-secondary .usa-search {
    display: block;
  }
}
```

**Comment by mogul** [comment]
@sharms is taking this on now... He said in Slack

![image](https://user-images.githubusercontent.com/47762/49051686-c0b44800-f19d-11e8-95d9-29708c36c840.png)

**Comment by rogeruiz** [comment]
on further inspection of this, I've noticed that the code that adds and removes the `.us-sr-only` class to the search `<form>` element is running twice and causing it to quickly toggle on & off.

**Comment by mogul** [comment]
We're planning to update the version of USWDS we're using for `cg-site` (and freezing `cg-dashboard` since we're deprecating it).

**Comment by mogul** [comment]
@thisisdano FYI

**Comment by mogul** [comment]
Fixed!
