### ISSUE TITLE
Add a page on PHP

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#137]
Include information about / links out to:
- [PHP extensions](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#php-extensions)
- [Composer](https://github.com/dmikusa-pivotal/cf-ex-composer)
- [Wordpress example](https://github.com/18F/cf-ex-wordpress)
- [Drupal example](https://github.com/dmikusa-pivotal/cf-ex-drupal)
- Drush
- Changing the PHP session storage to not use the filesystem

**Comment by brittag** [comment]
Covered by https://docs.cloudfoundry.org/buildpacks/php/ + https://docs.cloudfoundry.org/buildpacks/php/gsg-php-sessions.html
