### ISSUE TITLE
As a user, I need to specify a version of elasticsearch managed service

### ISSUE THREAD

**Issue by hollyallen** [cloud-gov/cg-site#138]
open-data-maker uses the elasticsearch managed service. The elasticsearch 2.0 service has a breaking change, and without a code change in open-data-maker it cannot be upgraded to use elasticsearch 2.0. I can understand wanting to offer 2.0 as a version of the managed service. If that is done, we'll want a way to run a pre-2.0 version instead, until such time as the necessary code change can be made.

cc @ultrasaurus

**Comment by mogul** [comment]
Now handled by someone else, and also being addressed prior to the move to GovCloud.
