### ISSUE TITLE
Update S3 documentation to reflect new sandbox syntax

### ISSUE THREAD

**Issue by fureigh** [cloud-gov/cg-site#1411]
If someone wants to use an S3 bucket in a sandbox, they now must use a plan name that ends in `-sandbox` (i.e., `basic-sandbox` or `basic-public-sandbox`).

### Current state:
The "[How to create an S3 instance](https://cloud.gov/docs/services/s3/#how-to-create-an-instance)" documentation doesn't yet reflect this sandbox-specific syntax.

### Proposed state:
Someone looking to create an S3 instance in a sandbox can successfully do so by following the "[How to create an S3 instance](https://cloud.gov/docs/services/s3/#how-to-create-an-instance)" documentation.

**Comment by jontours** [comment]
I'll get a patch for this going today thanks @fureigh!
