### ISSUE TITLE
Enabling secure east west communication 

### ISSUE THREAD

**Issue by RabehTawfik** [cloud-gov/cg-site#1444]
Hi All,

Just wondering, how do you go about enabling apps to use https within cloud foundry? My understanding is that TLS can be terminated at the LB, or the Go routers , or both. However, I am a bit confused about how can we use https for internal communication between apps/router  to apps ?

Many thanks.

**Comment by siennathesane** [comment]
@RabehTawfik let me unpack this a bit and point you to some resources.

> Just wondering, how do you go about enabling apps to use https within cloud foundry?

cloud.gov ships with HTTPS traffic required by default, so if you try to leverage non-HTTPS endpoints for external traffic entering the platform, it will be redirected to the HTTPS endpoints.

> My understanding is that TLS can be terminated at the LB, or the Go routers , or both.

This is correct, however to my knowledge we do not terminate at the LB, we just forward all traffic over HTTPS.

> how can we use https for internal communication between apps/router to apps ?

There exists a feature within Cloud Foundry, which we enable on cloud.gov, called [Shared Domains](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains), which has a sub-feature called Internal Domains. Internal Domains are domains which can only be leveraged via internal app traffic, like a frontend app to a backend app. You can configure your apps to respond on this domain with a given hostname which is globally unique. It does use HTTPS, so you can leverage that if you are interested. If you want app instance-specific SSL certificates, cloud.gov also exposes [App Instance Identity](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html), which is a per-app instance SSL certificate valid for 24 hours (renewed automatically by the platform). Leveraging the Internal Domains feature is likely the easiest path, but now you know what is available.

Does that answer your questions?

**Comment by RabehTawfik** [comment]
@mxplusb Yes, it does. Many thanks for help :)
