### ISSUE TITLE
cloud.gov / Federalist Unified Strategy Blog Post

### ISSUE THREAD

**Issue by Bryanthales-zz** [cloud-gov/cg-site#1456]
In order to make clear to federal customers the complementary nature of our service offerings from cloud.gov and Federalist, we plan to publish a blog post (to the 18F blog) reintroducing cloud.gov and Federalist -- and hopefully increase purchases of both services.

[18F Blog Draft - THIS IS THE VERSION TO REVIEW/EDIT](https://docs.google.com/document/d/1xkJRPHGefKbFYLYlQCn_5PDPEv0Vym-1pUVoANa6aJU/edit)
[OLD Working Document](https://docs.google.com/document/d/1LH4bKPvNjO-mo35LVo7W7JR1EwFe3LRMGM8hkUqMndo/edit?ts=5d5b4b2c)

[18F blog drafts repository](https://github.com/18f/blog-drafts) + [blog philosophy](https://handbook.18f.gov/blogging/)

Implementation sketch:

- [x] review existing documentation
- [x] review current blog posts to align messaging
- [x] draft blog post
- [x] file a GitHub issue in the blog drafts repository
- [ ] draft tweet that will go with post (and include in GitHub issue in blog drafts repository)

Acceptance criteria:

- [ ] Eddie has approved the content
- [ ] [The writing lab](https://github.com/18F/writing-lab) has approved the blog post content
- [ ] The blog team has organized and gone through any necessary outside-our-team reviews
- [ ] The blog post has been posted to the 18F blog

**Comment by Bryanthales-zz** [comment]
I have updated this and am adding Eddie to the card on the 18F Blog board for this posting.

**Comment by karareinsel** [comment]
Revisit post-Nov. 28.

**Comment by karareinsel** [comment]
Hold off on closing until we can revisit with the new ELP (Gary Hall) who is joining in January 2020 - he might be able to write this blog post.

**Comment by karareinsel** [comment]
@jessykacastillo to discuss with Gary Hall.

**Comment by karareinsel** [comment]
@eddietejeda what is the priority for this blog post? Can you advise?
