### ISSUE TITLE
Wercker not attaching the commit status

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#146]
The builds seem to be triggered, but the commit status isn't updated for some reason.

<img width="1440" alt="screen shot 2015-12-28 at 1 36 20 am" src="https://cloud.githubusercontent.com/assets/86842/12015543/857880b2-ad03-11e5-965c-5101896fab1f.png">

The documentation is [here](http://old-devcenter.wercker.com/articles/bestpractices/pullrequests.html), but doesn't seem to include any information about how to (re)enable the feature.

**Comment by dlapiduz** [comment]
Sent a message to Wercker about it... lets see what they say

**Comment by dlapiduz** [comment]
It is baaacckk!
