### ISSUE TITLE
Remove snyk

### ISSUE THREAD

**Issue by siennathesane** [cloud-gov/cg-site#1466]
We should remove snyk.io integration in favour of @dependabot.

**Comment by eddietejeda** [comment]
This is an org level decision. @afeld can you remove us?

(a reason for having our own org account)

**Comment by brittag** [comment]
I believe we can remove Snyk by removing the webhooks here: https://github.com/18F/cg-site/settings/hooks

**Comment by siennathesane** [comment]
You can remove things from the Snyk dashboard, as well, which will remove the webhooks.

**Comment by afeld** [comment]
@brittag I don't have access, sorry! https://github.com/18F/tts-tech-portfolio/issues/57

**Comment by hillaryj** [comment]
I removed snyk
