### ISSUE TITLE
As a potential user, I want to know what reporting types are available 

### ISSUE THREAD

**Issue by trevorbryant** [cloud-gov/cg-site#1479]
Reading the docs has a lot of information available about the benefits and how to's of getting started with cloud.gov. Some of the main benefits include the ATO, updates notifications, managing apps, etc. I'd like to know more about the things I care about post-purchase and implementation for continuous monitoring. Imay have missed something but I don't see it documented [here](https://cloud.gov/docs/).

  1) if I were a systems administrator, how would I configure reporting of a configurable compliance status to email me at a defined frequency?
  2) If I were an app owner, how would I configure reporting of continuous scanning and compliance against my app?

**Comment by karareinsel** [comment]
Thank you for submitting your comments and feedback. We recommend using https://cloud.gov/docs/apps/logs/ . For operational applications, we recommend contacting cloud-gov-support@gsa.gov.

**Comment by trevorbryant** [comment]
Thanks @karareinsel!

This doesn't answer any of the use cases, but it's a start. I'll request a feature in the future!
