### ISSUE TITLE
Always show seach box in homepage

### ISSUE THREAD

**Issue by eddietejeda** [cloud-gov/cg-site#1499]
As discussed here: https://github.com/uswds/uswds-site/issues/802

The click-to-show-search-field action is not a good practice. We should instead always show the search box.

Our newest templates show the search: https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/

**To Do**

- [ ] Update javascript to always show search box on homepage

**Comment by karareinsel** [comment]
Best addressed via a micro-request with 18F for front-end development support.

**Comment by karareinsel** [comment]
@eddietejeda can we close since this is being addressed by the work with 18F?

**Comment by bengerman13** [comment]
This looks like it's done to me. Closing - feel free to reopen if I'm wrong
