### ISSUE TITLE
How do you psql into a DB once it has been created?

### ISSUE THREAD

**Issue by monfresh** [cloud-gov/cg-site#15]
I followed the [database instructions](https://github.com/18F/cloud-foundry-notes/blob/master/app-deployment/databases.md) to create a database, but now I need to `psql` into the DB to run SQL commands. I have not been able to. It keeps timing out. I tried both the AWS RDS and the CF Service.

After some digging around, I learned that you can see your CF DB info by running `cf env <APP_NAME>`. I then tried to `psql` into my Postgres instance, but kept getting timed out as well. I am currently at home over VPN.

Thanks!

**Comment by afeld** [comment]
Note that this is _probably_ because the RDS database is within the Cloud Foundry VPC, which doesn't allow outside access.

**Comment by ozzyjohnson** [comment]
@monfresh - Connecting directly to a DB instance in CF is going to be a problem as the only the app route is exposed.  There have been a few plugins to do this specifically (tunnel to a service instance), but they're generally deprecated.

https://github.com/cloudfoundry/vmc
https://github.com/ybshen/tunnel-cf-plugin

As mentioned, [cf-ssh](https://github.com/cloudfoundry-community/cf-ssh) seems to be the future here.

**Comment by monfresh** [comment]
Awesome, thanks! I look forward to cf-ssh being available and documented.

**Comment by ozzyjohnson** [comment]
@monfresh - If you want to have a look, Diego has been putting some work into a functional cf-ssh script.

https://gist.github.com/dlapiduz/4e399ce13dd0af2fb804

**Comment by afeld** [comment]
It lives! https://docs.cf.18f.us/getting-started/cf-ssh/
