### ISSUE TITLE
As a user, I want to know where I can go to get help

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#153]
- If 18F staff, use #cloud-gov-support.
- Otherwise, use [the Google Group](https://groups.google.com/a/gsa.gov/forum/#!overview).
- If there's an issue with the documentation, [open an issue](https://github.com/18F/cg-docs/issues/new).

@mogul Does that sound right, for the current state of things?

**Comment by mogul** [comment]
Yes, though we're about to flip them from e-mail over to community.cloud.gov
.

**Comment by afeld** [comment]
Nice! Should I update #158 now, or wait?
