### ISSUE TITLE
Update footer and integrate USWDS styles

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1531]
During our UX audit, we noted a few fixes for the footer, including:
* Making sure it stacks properly on mobile devices
* Footer is not distinct from the main body, and is therefore harder to identify as a footer. 
* Integrate a link back to GSA

We also want the footer to map to the new USWDS tokens we've defined in #1535 and #1534 

## Done when
* [x] An updated footer design is created 
* [x] Shared with the team for feedback
* [ ] Updated footer is integrated on the site

## Notes
* [UX Audit's footer section](https://docs.google.com/document/d/1ItGl3CKfGf9BHPDA78UOLFNnrpOYl3TJC3y6c-K7JT8/edit#heading=h.hm038hs5y10d)

**Comment by cmajel** [comment]
@lauraGgit @karareinsel a few footer styles. 

## Footer 1 
(closest to default)
* Includes GSA link back (used language from Federalist)
* Background is `accent-warm`
* Text styles is 18franklin Medium, 14px/ `2xs`, `base-ink`

![cloudgov--footer-1](https://user-images.githubusercontent.com/2374206/74184446-d08a4180-4c14-11ea-8c91-fab4f91e3bcb.png)
![cloudgov--footer-1--mobile](https://user-images.githubusercontent.com/2374206/74184455-d3853200-4c14-11ea-8de2-e77350eaeb04.png)


## Footer 2 
(an alternative pattern I've seen on GSA sites)
* Footer 1st 
  * Background is is `accent-warm`
  * Text styles is 18franklin Medium, 14px/ `2xs`, `base-ink`
* Footer 2nd 
  * Background is `base-ink`
  * Text styles is 18franklin Medium, 14px/ `2xs`, white
![cloudgov--footer-2](https://user-images.githubusercontent.com/2374206/74184595-0af3de80-4c15-11ea-9a42-e723e0a71b0b.png)
![cloudgov--footer-2--mobile](https://user-images.githubusercontent.com/2374206/74184600-0f1ffc00-4c15-11ea-8d4f-cbfa849bd093.png)

**Comment by cmajel** [comment]
@cmajel add grid specs and PDF export

Let's plan on option #1

**Comment by lauraGgit** [comment]
took first pass at implementing #1 - need some guidance on the col layout.
![image](https://user-images.githubusercontent.com/5840989/74198704-27e9db00-4c30-11ea-91e3-c12a749298b8.png)

**Comment by cmajel** [comment]
@lauraGgit here's screenshots of the comps with the grid overlay.

![cloudgov--footer-1--grid](https://user-images.githubusercontent.com/2374206/74246640-de8e9f80-4cb2-11ea-8ea2-20721ea5a951.png)
![cloudgov--footer-1--mobile--grid](https://user-images.githubusercontent.com/2374206/74246924-42b16380-4cb3-11ea-9115-7c5b47e21a47.png)

**Comment by cmajel** [comment]
Updated footer for a 1024px grid 
![Screen Shot 2020-02-11 at 4 39 04 PM](https://user-images.githubusercontent.com/2374206/74282280-d6078a80-4ced-11ea-99cd-f8c42531ff25.png)

**Comment by cmajel** [comment]
@lauraGgit here's some styling notes.

Current on [preview site](https://cg-4bc824cf-0e89-4d31-a1be-d64b4c9fec53.app.cloud.gov/preview/18f/cg-site-federalist/colors-and-content/)

![Screen Shot 2020-02-18 at 1 30 04 PM](https://user-images.githubusercontent.com/2374206/74766154-d3a7b200-5252-11ea-9db1-ea24231c3ff3.png)
![Screen Shot 2020-02-18 at 1 30 11 PM](https://user-images.githubusercontent.com/2374206/74766157-d4404880-5252-11ea-94bc-b57eaf2dbe04.png)

* Can we set the links on hover to `primary-darker` / `#1A4480`/ `blue-warm-70v`? It seems like it's set for some of the links, but not all of them. 
* On mobile can we add 32px / USWDS spacing unit `4` between the different sections so that they don't ride right along one another?

@karareinsel passing to you for your notes.

**Comment by lauraGgit** [comment]
@cmajel for the mobile spacing - do you mean a- padding/margin? and both x and y - or just x/y?

**Comment by cmajel** [comment]
@lauraGgit I meant that between sections there's 32px of vertical space between the sections, either with margin or padding. Not sure what you mean by x/y. For these notes I was trying to give the value in actual pixels and USWDS tokens if that was confusing (value should be the same)

>  32px / USWDS spacing unit 4

**Comment by karareinsel** [comment]
Footer looks good - no additional comments.
