### ISSUE TITLE
Update colors to USWDS2 

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1534]
As we upgrade the site to USWDS2, we'll need to map the Cloud.gov color palette within the USWDS theming system.

This will also be an opportunity to evaluate text contrast on the site.

## Done when
- [x] Cloud.gov colors are mapped to USWDS color design tokens and theming names
- [x] Color recommendation is checked for text contrast
- [x] Colors are implemented on new USWDS branch of the site

**Comment by cmajel** [comment]
Proposed color updates here:
![cloudgov--colors-to-uswds](https://user-images.githubusercontent.com/2374206/73857486-025e6b00-4805-11ea-8efe-b5e516ecd796.jpg)
![cloudgov--uswds-palette--1](https://user-images.githubusercontent.com/2374206/73857488-02f70180-4805-11ea-9330-4845afa791a4.jpg)

**Comment by cmajel** [comment]
@lauraGgit after doing additional contrast testing on different backgrounds and working on the button (#1540), a few palette updates:
* Changing `base-darkest` and `base-ink` from `gray-warm-80` >> `gray-warm-90`
* Changing `primary-dark` from `blue-warm-60` >> `blue-warm-60v`
* Text link color should be updated from `primary-vivid` >> `primary-dark`. Icons can remain at `primary-vivid`
* Changing `secondary-light` from `red-20` to `red-20v`

Updated files:
![cloudgov--colors--update](https://user-images.githubusercontent.com/2374206/74252657-f6b6ec80-4cbb-11ea-88af-d0e0b75c68f3.jpg)
[cloudgov--colors--update.pdf](https://github.com/18F/cg-site/files/4186558/cloudgov--colors--update.pdf)

**Comment by cmajel** [comment]
@karareinsel I've added documentation on the `cg-product` repo to close out this work. Here's the [Cloud.gov styles](https://github.com/18F/cg-product/wiki/Cloud.gov-Styles) page I created in the wiki. 

I recommend replacing `Style guide` link in the sidebar with this new page, and removing the `design repo` link since it is also covered in this new page.

**Comment by karareinsel** [comment]
Agree with your recommendations. Looks good - feel free to wrap up and close out.
