### ISSUE TITLE
Update typography and address inconsistencies

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1535]
The initial [UX audit](https://docs.google.com/document/d/1ItGl3CKfGf9BHPDA78UOLFNnrpOYl3TJC3y6c-K7JT8/edit#) noted a few inconsistencies with the cloud.gov typography system (see notes below)

## Done when...
* [x] Updated typography system is recommended
* [x] Feedback is given by the team
* [x] Updated typography is reflected in the new USWDS branch

### Divergent heading / body copy styles
**System 1** on splash pages
* Headings are 18F-Franklin, with H1s sized at 48px and bold
* Body font is also 18F-Franklin, with p sized at 18px
![image](https://user-images.githubusercontent.com/2374206/73857857-83b5fd80-4805-11ea-9559-272d7af0e00d.png)

**System 2** on doc pages
* Headings are 18F-Franklin but thin, with H1 sized at 36px
* Body is Georgia, with p sized at 16px
![image](https://user-images.githubusercontent.com/2374206/73857914-99c3be00-4805-11ea-94d3-a0eab2a6bb09.png)

### Short line heights
Line-height for wrapped text should be at least 1.3 to be easily readable. Some sections, like this sub sidenav link for “How cloud.gov helps teams…”, have smaller values.
![image](https://user-images.githubusercontent.com/2374206/73858187-fb842800-4805-11ea-917a-ee67717bdb5b.png)

### H3s and H4s need more visual weight
In some places, these headings are smaller than body copy. 

### Some links are identified only by color
Text links are inconsistently styled (some have underlines, others don’t), and sometimes rely on color to communicate that they are links (USWDS says links should not be color dependent.)

Visited links are only distinguished by a different color underline. Recoloring the entire link will make it easier to know where you have been.

**Comment by cmajel** [comment]
@lauraGgit here's what I am thinking for type styles:
* Keep the same fonts: 18Franklin for headers, Georgia for body, and Roboto Mono for code
* Use heavier weights of 18Franklin (Semibold and Medium) for headers, so that they're easier to scan
* For the sidenav type...
  * Add indentation
  * Use blue to signify a highlighted section, and our base ink color for an inactive item. 
  * Use the sidenav highlight bar only on active sections

![cloudgov--typography--1](https://user-images.githubusercontent.com/2374206/73961504-b847b900-48da-11ea-959d-985d39dae5ae.jpg)

## Demo of this for doc pages
I also looked at the sidenav indentation and how to see where you are. This is using content from the existing site (sometimes frankenstein-ed so that I could get multiple header levels)

Note, I excluded icons to design quickly, but they can be added as placeholders for now. 

![doc-page--updated-type--1 0](https://user-images.githubusercontent.com/2374206/73961506-b8e04f80-48da-11ea-913c-7c66833cb4e8.png)
![doc-page--updated-type--1 1](https://user-images.githubusercontent.com/2374206/73961508-b978e600-48da-11ea-826f-6cde36458884.png)

**Comment by lauraGgit** [comment]
@cmajel can you provide the type specs in copiable text? it would be a lot easier to import them that way

**Comment by cmajel** [comment]
@lauraGgit whoops sorry about that. Here's a pdf version.

[cloudgov--typespecs.pdf](https://github.com/18F/cg-site/files/4167936/cloudgov--typespecs.pdf)

**Comment by lauraGgit** [comment]
Thanks! Also - should ux elements like nav/buttons be Franklin?

**Comment by cmajel** [comment]
From planning:
* May need to do a pass in the future to check the H1 > H3 issue on Doc pages. 
* @lauraGgit and @cmajel pair on type styles for splash pages.

**Comment by cmajel** [comment]
@lauraGgit adding an updated version of this that includes splash page styles. Changes include:

* Discussed this am: Set H2s to font weight 600 rather than 500
* Discussed this am: Set headings to have a `-3` letter spacing
* I realize our link color is currently `primary-darker`, and I'd like to reset that to `primary-dark`, with `primary-darker` being the hover color. 
* Added a home hero H1 style
* h4 upside from 16px > 18px
* Added a feature link style which appears on home page. (basically, they're H4 links, with a large variation in the home hero)

![cloudgov--typography--1](https://user-images.githubusercontent.com/2374206/74473469-a6818b00-4e71-11ea-9c72-e03bac02d066.jpg)
[cloudgov--typography--1.pdf](https://github.com/18F/cg-site/files/4200725/cloudgov--typography--1.pdf)

**Comment by cmajel** [comment]
Adjusted to include vertical spacing spec:

![cloudgov--typography--1--annotated](https://user-images.githubusercontent.com/2374206/74880676-b26dc100-5339-11ea-8983-1caf83b02939.jpg)
[cloudgov--typography--1--annotated.pdf](https://github.com/18F/cg-site/files/4227674/cloudgov--typography--1--annotated.pdf)

**Comment by cmajel** [comment]
@karareinsel I've added documentation on the `cg-product` repo to close out this work. Here's the [Cloud.gov styles](https://github.com/18F/cg-product/wiki/Cloud.gov-Styles) page I created in the wiki. 

I recommend replacing `Style guide` link in the sidebar with this new page, and removing the `design repo` link since it is also covered in this new page.

**Comment by karareinsel** [comment]
same as #1534 - looks good. I agree with your recommendations so feel free to wrap it up and close the issue.
