### ISSUE TITLE
Build a Cloud.gov site map 

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1536]
We want to understand what content exists on cloud.gov currently and what is used so that we can find a better way to organize the content. 

Standup notes:
Would be great to have a site map that shows...
* What content is there now, and how is it organize?
* What are people reading and what's popular?
* What biz dev uses to explain cloud.gov?
* And...maybe an alternative way to organize it?

## Done when
* [x] A site map is shared with and is accessible by the cloud.gov team
* [x] Guidance on how to reorganize the site (at a high level)

**Comment by cmajel** [comment]
Current content map from @erinzstrenio 
https://app.mural.co/invitation/mural/gsa6/1581345078867?sender=erinstrenio1697&key=17611383-8684-426e-85f9-0091d7c607d0

We'll check in with @jessykacastillo to compare her most used pages with most read pages.

**Comment by karareinsel** [comment]
For **existing** customers (especially newly signed up customers), the links found under "Managing Orgs" are extremely relevant. 

@jessykacastillo will follow up with the links she most frequently sends to **prospective** customers.

**Comment by karareinsel** [comment]
The three main questions @jessykacastillo receives from prospective customers are pricing, security, and how can they use their applications on cloud.gov.

Here are the links Jessyka frequently shares with prospective customers:

- https://cloud.gov/pricing/
- https://cloud.gov/docs/pricing/free-limited-sandbox/ - **this points to the same form as signup**
- https://cloud.gov/signup/ - **this points to the same form as getting a sandbox**
- https://cloud.gov/docs/overview/portfolio-analysis/
- https://cloud.gov/docs/security/fedramp-tracker/
- https://cloud.gov/docs/technology/responsibilities/

**Comment by erinzstrenio** [comment]
Thank you @karareinsel and @jessykacastillo! This is helpful.

**Comment by erinzstrenio** [comment]
Initial recommendations for site reorg: https://docs.google.com/document/d/1OrI8oelpBnosA_brEfOkdqgZz0Fnc7hK4v8SgMZF-Z4/edit?usp=sharing

Subject to change after content audit and more user testing (with new and current customers)!

Here's a link to the content audit spreadsheet: https://docs.google.com/spreadsheets/d/1zaRnJfUr9J3K2LcasMHs9PRD9KNxFiT1pONXqbc7v20/edit?usp=sharing
