### ISSUE TITLE
port over existing content

### ISSUE THREAD

**Issue by lauraGgit** [cloud-gov/cg-site#1538]
Done when:
* All content ported over

To do:
* Layout spacing on home page
* Sign up page needs some review
* Needs to add in updates page

**Comment by cmajel** [comment]
From planning:
* Making good progress
* Layout spacing on home page
* Sign up page needs some review
* Needs to add in updates page

**Comment by cmajel** [comment]
@lauraGgit it looks like the bulk of the migration has been done, but I am seeing a few places where content is missing.
* Some images in `/docs` do not appear. For example, this visualization of the ATO process. [Current site](https://cloud.gov/docs/security/fedramp-tracker/) vs [demo site](https://cg-4bc824cf-0e89-4d31-a1be-d64b4c9fec53.app.cloud.gov/preview/18f/cg-site-federalist/colors-and-content/docs/security/fedramp-tracker/). Maybe the asset links aren't mapping to the branch name correctly?
![Screen Shot 2020-02-18 at 12 43 27 PM](https://user-images.githubusercontent.com/2374206/74763128-36964a80-524d-11ea-8e99-55e521329673.png)
* Similarly, it looks like some inline links are broken, like to the `Control Implementation Summary + Customer Responsibility Matrix + Control-by-Control Inheritance (.xlsx)` link on that same ATO page. [Current site](https://cloud.gov/docs/security/fedramp-tracker/) vs [demo site](https://cg-4bc824cf-0e89-4d31-a1be-d64b4c9fec53.app.cloud.gov/preview/18f/cg-site-federalist/colors-and-content/docs/security/fedramp-tracker/).
* And, I believe this is on your radar, but there are some sidenav pages that aren't rendering. Like the `Dynamic behavior monitoring` link under Experimental Features.

**Comment by cmajel** [comment]
This has been updated, including:
* Updates migrated over
* Mermaid charts migrated over
* Docs and PDFs have been ported over
