### ISSUE TITLE
Fix side nav expansion

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1539]
[Our UX audit](https://docs.google.com/document/d/1ItGl3CKfGf9BHPDA78UOLFNnrpOYl3TJC3y6c-K7JT8/edit#heading=h.4tgllgpnm3l1) found that multiple sidenav items could be opened at once, which makes it easier to get lost on the page. 

## Done when
* [x] Solution is proposed
* [ ] Sidenav is updated on site per recommendation

## Notes
Relates to the doc page designs referenced in #1535 

This also ties closely to content decisions on the site. Cloud.gov currently uses its L0 sidenav as categories, not as pages. However often sites use their top L0 sidenav items as pages, with subpages underneath. For example:
* [18F engineering hiring guide](https://eng-hiring.18f.gov/interviews/)
* [PRA guide](https://pra.digital.gov/do-i-need-clearance/)

**Comment by cmajel** [comment]
My initial proposal if the content and categories stay the same is that...
* When I expand a new section, all other sections close
* The sidenav would still highlight what section is active, even if that section is closed.

But @erinzstrenio wondering if you have thoughts on this. Most of the sites I've seen haven't really used categories in sidenav, but do have the concept of parent > child pages.

**Comment by erinzstrenio** [comment]
@cmajel I'd agree with this suggestion!

**Comment by cmajel** [comment]
The initial sidenav is launched! 🎉 Future design enhancements on active state are documented here #1553
