### ISSUE TITLE
MVP sign up page

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1542]

**Comment by cmajel** [comment]
Initial sign up page MVP for desktop. @karareinsel would love your review on this.

A few notes:
* I wonder if "sign up" is even the right name for this page, since this page is more about creating a sandbox. I experimented with `Get a free sandbox` which is more descriptive.
* The current step 2 includes video tutorials and links to deployment instructions in java vs other languages. I...
  * Added a call to action pointing to the [Set up cloud.gov](https://cloud.gov/docs/getting-started/setup/) page, which is a top trafficked page and covers basic set up instructions
  * Removed the java vs other language instructions (since I believe this is covered in the CTA)
  * Moved up the sample application links from the old "additional resources" section to a sidebar list
  * Removed the video tutorials. All of the videos have fewer than 900 views after being on Youtube for 3 years, so I am not sure they are used. If they are useful, I'd recommend creating a playlist and linking to it via a text link, saying something like "Watch cloud.gov video tutorials". 
* For step 3 I...
  * Added a sidebar list with "Join the communities" links from the old additional resources section (since it's in line with contacting / reaching out)

## Comps
![signup--mvp--1](https://user-images.githubusercontent.com/2374206/74287297-9f367200-4cf7-11ea-8a70-0bf4ed72ebfb.jpg)


## with 1024px grid
![signup--mvp--1--grid](https://user-images.githubusercontent.com/2374206/74287331-b4130580-4cf7-11ea-9083-2e893c770258.png)


## PDF with selectable text
[signup--mvp--1.pdf](https://github.com/18F/cg-site/files/4188970/signup--mvp--1.pdf)

**Comment by lauraGgit** [comment]
🎉 this is great - you can see the WIP on the deployed branch.

**Comment by karareinsel** [comment]
This looks great - much cleaner and easier to understand. I'd like to keep a text link to the training videos (and removing the embedded the videos). 

Just as FYI - we would like to have a place on our site where links to training videos and materials can live - I think this will improve findability of our existing materials and support the new content we're working to create (in partnership with digital.gov university). @erinzstrenio sharing for visibility as you work on the site IA recommendations.

**Comment by karareinsel** [comment]
@eddietejeda and @jessykacastillo comp for the revised sign-up page is above if you want to take a look. I think it looks good and I'm on-board with the recommended changes.

**Comment by cmajel** [comment]
@karareinsel awesome. What do you think about adding text  under the "Set up cloud.gov" button that links directly to the three videos? This is the lightest weight option and doesn't move any content. Here's what I'm thinking for text:

> We also have video tutorials on [an overview of the cloud.gov platform](https://www.youtube.com/watch?v=LKb0liZyepA&feature=emb_logo), [a walk through of the initial registration process](https://www.youtube.com/watch?v=ip8G_Rafb_c&feature=emb_logo), and [a hands-on workshop on how to start running applications](https://www.youtube.com/watch?v=G2J8dxSF0-I&feature=emb_logo).

In the future, I could see this being a link to a youtube playlist of cloud.gov tutorials, or to a dedicated page of video tutorials, which may be a good option if there are more out there.

**Comment by karareinsel** [comment]
When a user clicks on the links, can those links open in a new tab/window rather than refresh the page? If so, your suggestion works for me.

**Comment by cmajel** [comment]
I believe we can do that. @lauraGgit can you add this text block in to the "setup cloud.gov" block of the sign up page?

**Comment by cmajel** [comment]
This content has been updated and added to the sign up page 
![Screen Shot 2020-02-21 at 3 47 29 PM](https://user-images.githubusercontent.com/2374206/75070573-7cf3df80-54c1-11ea-8cbf-4f149680c4bf.png)

**Comment by pburkholder** [comment]
The old quickstart page had a simple example. These examples probably don't work. This will probably make for a poor initial experience. We should talk.

**Comment by karareinsel** [comment]
@pburkholder which simple example are you referring to? When you say "these examples probably don't work" - can you provide more context?

**Comment by pburkholder** [comment]
Yes, that was too terse on my part. The current quickstart page https://cloud.gov/signup/ has an example for a Java app, "Learn how to deploy a Java web application in your sandbox." that you can follow step-by-step and have a working app running in cloud.gov. Whenever I do a demo I start from that point and then walk through it, usually with the scaffolding in https://github.com/18F/cg-demos#quickstart-demo.

The new page is a good clean up, but I think we should include the same demo.

The linked demos for Drupal and Wordpress are kind of fragile, present a lot of information overload, and I can't guarantee they'll work.

**Comment by karareinsel** [comment]
@eddietejeda is this the page you created? https://cg-4bc824cf-0e89-4d31-a1be-d64b4c9fec53.app.cloud.gov/preview/18f/cg-site-federalist/colors-and-content/docs/getting-started/code-samples/

**Comment by karareinsel** [comment]
Good to close.
