### ISSUE TITLE
Graphic suggestions for ATO responsibilities

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1543]
Current: 
![image](https://user-images.githubusercontent.com/2374206/74185050-de8c9200-4c15-11ea-82dd-a8583e6f5267.png)

Initial sketch from UX audit:
![image](https://user-images.githubusercontent.com/2374206/74185012-cd438580-4c15-11ea-96be-83b67e2f83c9.png)

**Comment by karareinsel** [comment]
This issue has been covered by https://github.com/cloud-gov/product/issues/1443
