### ISSUE TITLE
IA recommendations

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1545]
What can we do to improves the visibility of top pages?
Site IA can be adjusted.
By persona?

Done when: 
* [x] Site IA recommendations are shared with Cloud.gov
* [ ] Recommendations for content to remove

**Comment by erinzstrenio** [comment]
Initial recommendations for site reorg: https://docs.google.com/document/d/1OrI8oelpBnosA_brEfOkdqgZz0Fnc7hK4v8SgMZF-Z4/edit?usp=sharing

Content audit that @jessykacastillo and @karareinsel are working on. The goal is to identify which pages need to be updated or retired: https://docs.google.com/spreadsheets/d/1zaRnJfUr9J3K2LcasMHs9PRD9KNxFiT1pONXqbc7v20/edit?usp=sharing

**Comment by cmajel** [comment]
These initial recommendations have been incorporated into the MVP site:
![Screen Shot 2020-02-21 at 3 34 55 PM](https://user-images.githubusercontent.com/2374206/75069788-ea9f0c00-54bf-11ea-8ebf-e13e97f4cfc2.png)


Keeping this open for the cloud.gov team to continue working through their content audit and identifying how their content should be categorized, and what content needs updates and
