### ISSUE TITLE
Styling punchlist

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1547]
# To do
## Header 
_Christine review, prob done_
* [x] Look at Eddie's PR re: Banner, and look at flicker of gov banner and dropdowns on hard refresh.

## Home page
_To fill in_

## Get started page 
@cmajel working on all this
* [x] Add [this content](https://github.com/18F/cg-site/issues/1542#issuecomment-585244808) under the CTA for section 2, include `target=_blank` urls.
* [x] Fix hover states for last button
* [x] Spacing review based on current mock
* [x] Fix header weights
* [x] Add caret icons or arrow icons rather than `>` placeholder on buttons

## Pricing page

* [x] H1 should be 48px /  theme token `3xl.` Currently it's rendering at 32px / H2 size
* [x] Make title H1 `grid-col-9`
* [x] Downsize the pricing table header row (Sandbox, prototyping, etc) to 28px / USWDS system token `11`
* [x] add `margin-y-5` / 40px to the top and bottom of the pricing image
* [x] For side-by-side lists increase to `col-6`

### Pricing table
* [x] Note that on mobile this table *does not display properly*. Rather than turn each column into a table, it turns each row into a table. 

## Documentation page
* [x] Fix code block styling @cmajel 
* [x] Mermaid.js charts styling needs another look. Colors and lines don't appear to be rendering. Example on Compliance > ATO Process. 

### Sidenav

Current:
<img width="1102" alt="Screen Shot 2020-02-18 at 10 40 56 AM" src="https://user-images.githubusercontent.com/2374206/74751864-dc40be00-523b-11ea-9fda-a48b4be5b96f.png">

Updates to make:
* [x] Cursor is showing on hover for Parent elements, should be pointer.
* [ ] Add a caret icon on the far left to signify if the category section is opened or closed. Icon is the same as current site with the color `primary-vivid`.
* [x] Graphic category icons can remain. They should be  16px / `2` USWDS spacing units between icon and category name. States: 
  * [x] By default, color should be `accent-warm-dark` / USWDS gray-warm-20
  * [x] On hover and while active, color should be `primary-vivid`.
* [x]  Nav items should be styled as 18Franklin Regular, 16px / `sm`. States:
  * [x] By default, color should be `base-ink`. No background color shift. 
  * [x] On hover and when active, color should be `primary-dark` and font should shift to 18Franklin Medium.
  * [x] Remove border between items
  * [x] Sidenav items use (what I believe is) the default USWDS sizing and padding. Items are min 40px high which equates to a 16px padding between items. @cmajel 
* [x] Indentation of child elements @cmajel 

Updated:
![Screen Shot 2020-02-18 at 11 26 53 AM](https://user-images.githubusercontent.com/2374206/74755766-9edf2f00-5241-11ea-8eb0-a7bd92d7b9c1.png)

### Additional content

* [x] The headings are displaying as `bold` rather than `semibold`. In [the latest typespec](https://github.com/18F/cg-site/issues/1535), `bold` only applies to the main home splash page. For other headings...
  * H1, H2 should be 18Franklin Semibold / font-weight 600
  * H3, H4, H5, H6 should be 18Franklin Medium / font-weight 500
* [x] Content should be 64px / `.margin-8` from the top and bottom of the sections
* [x] Intro styling does not appear to be showing on the doc pages. @cmajel 

# Done

## Header
Current:
![Screen Shot 2020-02-11 at 4 09 57 PM](https://user-images.githubusercontent.com/2374206/74279586-2cbe9580-4ce9-11ea-9dd9-46caaf9adb0b.png)

Updates to make:
* [x] Top nav items should be font weight 500 / 18Franklin Medium (currently 700 / bold)
* [x]  Search bar should be grid-col-4
* [x] The default link color should be `base-ink` (it appears lighter on both the main nav and secondary nav
* [x] Nav links on hover should set to `primary-darker`
* [x] Active state bar can remain `primary-vivid` (currently set to darker shade)

Updated:
![Screen Shot 2020-02-11 at 4 09 14 PM](https://user-images.githubusercontent.com/2374206/74279724-71e2c780-4ce9-11ea-8fe2-10ca3dcea6dc.png)

### Pricing table
Current:
![Screen Shot 2020-02-12 at 10 19 01 AM](https://user-images.githubusercontent.com/2374206/74348791-3eec1280-4d81-11ea-9273-4c93ab183ada.png)

Updates to make:
* [x] remove border between icons and first header row
* [x] remove bottom padding between icons and first header row to make them feel more unified
* [x] for pricing table rows, there should be 24px of top/bottom padding between text and rows (USWDS spacing unit `3`)
* [x]  Let's keep the 18Franklin font for the pricing table 
* [x] The font size for the first two rows of content (description and monthly price) should be 16px. For additional rows, it should be a smaller text style of 18franklin regular, 14px / `3`, 1 
* [x] Price previews should be h3 sized / 22px / USWDS `lg`. Include breaks between `price / month` and supporting text.
* [x] Pricing buttons should have 16px bottom padding between additional links
* [x] `Get started` should be a button under the Free column

Updated:
![Screen Shot 2020-02-12 at 10 35 59 AM](https://user-images.githubusercontent.com/2374206/74350732-1f0a1e00-4d84-11ea-8b4d-c4bbde97d068.png)

### Additional content

Current:
![Screen Shot 2020-02-12 at 10 44 26 AM](https://user-images.githubusercontent.com/2374206/74351138-b5d6da80-4d84-11ea-8226-151058e2aa03.png)

Updates to make
* [x] The "estimate monthly cost" H2 is not properly sized. It should be 32px / USWDS `xl` but instead is rendering at 24px.
* [x] Same with H3. Should be 22px / USWDS `lg` but is rendering at 18px.
* [x] Let's use default body copy styling outside of the pricing table. So, switch from 18Franklin to Georgia.
* [x] Body copy should not extend beyond 7 cols to keep a readable words per line.
* [x] For estimate table, let's narrow it to 6 col 
* [x]  Per note above, space between sections (like pricing table <> estimate <> All use of cloud.gov <> Additional resources) should be 64px / `.margin-8`

Updated:
![Screen Shot 2020-02-12 at 11 01 25 AM](https://user-images.githubusercontent.com/2374206/74352802-0bac8200-4d87-11ea-932d-89b2bbb40750.png)

**Comment by lauraGgit** [comment]
- [x] top nav items should be font weight 500 / 18Franklin Medium (currently 700 / bold)
- [x] The default link color should be base-ink (it appears lighter on both the main nav and secondary nav
- [x] Nav links on hover should set to primary-darker
- [x] Active state bar can remain primary-vivid (currently set to darker shade)

@cmajel what should be the hover color for button[aria-expanded=true]?

**Comment by lauraGgit** [comment]
Updates to make
* [X] The "estimate monthly cost" H2 is not properly sized. It should be 32px / USWDS `xl` but instead is rendering at 24px. -* but question about the font weight - we can discuss later today*
* [X] Same with H3. Should be 22px / USWDS `lg` but is rendering at 18px. 
* [X] Let's use default body copy styling outside of the pricing table. So, switch from 18Franklin to Georgia.
* [X] Body copy should not extend beyond 7 cols to keep a readable words per line.
* [X] For estimate table, let's narrow it to 6 col 
* Per note above, space between sections (like pricing table <> estimate <> All use of cloud.gov <> Additional resources) should be 64px / `.margin-8` - ? `.margin-8`on each section - or `.margin-4` on each section?

**Comment by cmajel** [comment]
@lauraGgit I went through and ticked off the items ☝️ that have been updated in the [preview branch](https://cg-4bc824cf-0e89-4d31-a1be-d64b4c9fec53.app.cloud.gov/preview/18f/cg-site-federalist/colors-and-content/)

For this question:
> Per note above, space between sections (like pricing table <> estimate <> All use of cloud.gov <> Additional resources) should be 64px / .margin-8 - ? .margin-8on each section - or .margin-4 on each section?

I believe we chatted about this last week, but it appears that things are looking correct on the preview site. The goal is to have `64px` spacing between sections. It looks like we did this with padding so `.margin-8` is the right value.

**Comment by cmajel** [comment]
Notes from pairing today @lauraGgit :
* Side nav children indentation, low priority

Priority
* Sidenav
* Homepage styling
* Remaining images
* Pricing edits from Kara
* Mobile
  * header nav
  * pricing table
  * hide waves on get started
* Punchlist (christine and Laura tackling with leftover time)

**Comment by cmajel** [comment]
These have been completed 🎉 The only issues we did not get to have been added to the backlog:

#1554: Open close caret on sidenav
#1553 : Active pill placement and styling on sidenave
