### ISSUE TITLE
Home MVP

### ISSUE THREAD

**Issue by cmajel** [cloud-gov/cg-site#1548]
## MVP homepage design with updated styles
![home--mvp--1](https://user-images.githubusercontent.com/2374206/74746733-dc3cc000-5233-11ea-8e1c-8cd85af0167f.jpg)

Updates of note:

* Icons should remain the same as on current site (dropped some to design more quickly)

* I added headings to the different sections to make it easier to scan the page and for screenreaders to know where they are. (For example, added "why cloud.gov" and "who we work with")

* Adjusted the layout of the first section (on FEDramp authorization and compliance from the start) from a 3 column layout to a 2 column layout for the content sections and a highlight bar for the sandbox prompt. This gives the sandbox prompt more visual weight.

* Would recommend dropping the links to the sandbox guide and video tutorials and instead having one bold CTA button, since they all go to the same page.

* Adjusted layout for the "who we work with section" including switching to a 3 col grid for agencies. This will make it easier to scan and also to add additional rows if desired.

**Comment by cmajel** [comment]
ccing @karareinsel, @jessykacastillo and @eddietejeda if they'd like to provide feedback.

**Comment by karareinsel** [comment]
Some feedback
- The updated design looks cleaner and is easier to follow - the added headings really do help a user scan the page.
- I wonder if we should rework the current messaging at the top of the homepage. Right now it says "cloud.gov helps teams build, run, and authorize cloud-ready or legacy government systems quickly and cheaply." That feels very jargony to me - does anyone else feel that way? I could see a less technical prospective customer read that and wonder "But what does that mean?"

**Comment by cmajel** [comment]
@karareinsel I agree that this language could use revisiting:

> cloud.gov helps teams build, run, and authorize cloud-ready or legacy government systems quickly and cheaply.

For me, the `or` feels like it's interrupting the thought. Here are some ideas on simplifying the current message, but open to other ideas if this message doesn't seem right.

* cloud.gov helps teams build, run and authorize government cloud systems quickly and cheaply.
* cloud.gov helps government teams build and run compliant cloud systems quickly and cheaply.

**Comment by karareinsel** [comment]
I like cloud.gov helps teams build, run and authorize government cloud systems quickly and cheaply.

**Comment by cmajel** [comment]
Adding in the vertical spacing and annotated version:

![home--mvp--1--annotated](https://user-images.githubusercontent.com/2374206/74880739-d7faca80-5339-11ea-957c-7d08a64b1b26.jpg)
[home--mvp--1--annotated.pdf](https://github.com/18F/cg-site/files/4227680/home--mvp--1--annotated.pdf)
