### ISSUE TITLE
Add Netlify to cloud.gov's Federalist site

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-site#1557]
As a cloud.gov team member, I would like to add Netlify CMS to our instance of Federalist so that I can easily create and edit content based on the outcomes of the content audit for cloud.gov. 

As background, cloud.gov recently moved to Federalist but to an older version that doesn't have Netlify CMS included as standard. It needs to be added. More information on how to do this can be found [here](https://federalist.18f.gov/documentation/getting-started-with-netlify-cms/) and [here](https://www.netlifycms.org/docs/add-to-your-site/).

**Comment by apburnes** [comment]
I can jump in and take up where Eddie left off with #1565
