### ISSUE TITLE
Sunset pages under "Purchase and Pricing" section

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-site#1600]
Based on the audit of the [Purchase and Pricing ](https://github.com/cloud-gov/product/issues/1300)pages, the following pages should be sunsetted because their content is redundant.

- [x] Get started using cloud.gov (/docs/pricing/start-using-cloudgov/) - Content is already covered by other sections of the website.
- [x] Prototyping package details (/docs/pricing/prototyping/) - Content is already covered by other sections of the website. 
- [x] The cost of managed services (/docs/pricing/managed-services-cost/) - Move the content under "comparison with private sector pricing" to Quota costs, billing and limits page
- [x] How the pricing model is managed (/docs/pricing/pricing-model/)- Not sure what value this page provides nor who it's trying to serve.
- [x] Terms we use in pricing (/docs/pricing/pricing-terminology/) - Content needs to be updated to remove inaccurate and outdated information (such as removing mentions of 18F, managed services, consulting) and is already covered by other sections of the site.

**Comment by karareinsel** [comment]
@hillaryj is looking into moving the two remaining pages (https://cloud.gov/docs/pricing/quotas/) and (https://cloud.gov/docs/pricing/free-limited-sandbox/) so they live as drop-downs under Pricing in the top nav. Then we can remove Purchase and Pricing from the left nav.

**Comment by hillaryj** [comment]
I talked to @mheadd about this and he's worked with Jekyll sites before (which ours is now), so he's going to take on moving around the pages and fixing the dropdowns.
