### ISSUE TITLE
Docs pages code examples go off screen

### ISSUE THREAD

**Issue by ondrae** [cloud-gov/cg-site#1777]
<img width="1440" alt="Screen Shot 2020-09-21 at 2 50 35 PM" src="https://user-images.githubusercontent.com/595778/93825364-ef749b80-fc19-11ea-8a7f-51e649c709de.png">

https://cloud.gov/docs/services/relational-database/

On a 13 inch Mac laptop.

**Comment by ccostino** [comment]
Hi @ondrae, thank you for reporting this!  We're taking a look and will get this fixed as soon as we can.  I'm seeing it happen elsewhere on the site as well.
