### ISSUE TITLE
ensure that all links to Cloud Foundry documentation go to the community version

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#179]
We have multiple links to http://docs.run.pivotal.io (and possibly other providers), where linking to http://docs.cloudfoundry.org/ would be more appropriate.
- [ ] Change the existing links
- [ ] Add an automated test to suggest the domain be switched if this comes up again

**Comment by sharms** [comment]
I can adapt the title checker to also check for this in wercker
