### ISSUE TITLE
Document how to deploy a Flask app with Postgres

### ISSUE THREAD

**Issue by monfresh** [cloud-gov/cg-site#18]
I'd be happy to take a stab at this, but perhaps I should wait until `cf ssh` is ready?

**Comment by dlapiduz** [comment]
@monfresh you can take a first stab and then we can edit as needed...

**Comment by afeld** [comment]
There is now a guide:

https://docs.cloud.gov/apps/flask/

@monfresh Feel free to add to it if you think there's anything missing!
