### ISSUE TITLE
consider hosting the CF docs ourselves

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#180]
The Cloud Foundry documentation is structured in an interesting way: each "module" is hosted as a separate repository, and then [brought together via Bookbinder](https://github.com/cloudfoundry/docs-book-cloudfoundry). The other interesting thing is that the docs are [templatized](https://github.com/cloudfoundry/docs-book-cloudfoundry/blob/master/config.yml), so that a Cloud Foundry host like Pivotal Web Services can have their own nearly-identical docs (via [their own Bookbinder repo](https://github.com/pivotal-cf/bookbinder)) with
- The appropriate config values, e.g. the UAA host
- Their own sections of documentation pulled into the same place

**Pros**
- We still get to leverage the canonical documentation, just not at the canonical domain.
- This avoids the the issue of "go to this page, but use `uaa.cloud.gov` where it says `target`".
- Users don't have to jump back and forth between sites as much.
- We can simply exclude the parts of the docs that aren't relevant to our users
  
  ![cloud foundry docs](https://cloud.githubusercontent.com/assets/86842/12358060/70e7ee38-bb79-11e5-891d-bcd6e57f57b0.png)

**Cons**
- It might be confusing to users whether they can still use the canonical docs
- The docs (might) become less Google-able

Thoughts?

/cc @jameshupp @msecret

**Comment by jameshupp** [comment]
Okay, so as I understand this:
- Our documentation would build from the canonical docs, so when they update, ours update, too.
- We can incorporate supplemental info that's specific to cloud.gov alongside the most relevant canonical info, and we can exclude pieces of the canonical docs that aren't relevant to us.

If that's the case, the cons seem to me like almost non-issues. I don't see why this would reduce CF's Google-ability in any appreciable way, and while it might not give us _more_, right now ours for these docs is zero. And we could address confusion by creating an include note that we pull into any docs where it's relevant.

Does that square, or am I misunderstanding something? If that's all true, I say go for it. I love the idea of taking advantage of their work while also making our users' lives easier, but I don't want to recreate work they're already doing (to keep info up to date or in sync). I'm less enthusiastic if that's going to happen.

**Comment by afeld** [comment]
Yep, I think you've got it. One more bonus is that we would get to put the cloud.gov branding on the docs :sparkles:

**Comment by msecret** [comment]
I think this is a great idea. We've previously talked about how we might have a need to add more layers of hierarchy then what's offered in CF, and if we could add on to the documentation, we could make this easier.

**Comment by dlapiduz** [comment]
@afeld I think this would be pretty interesting... particularly doing it so in a programatic way so we pick and choose but at the same time we can keep up to date.

**Comment by dlapiduz** [comment]
@suprenant is this a no go?

**Comment by brittag** [comment]
@dlapiduz This has a new issue over here: https://github.com/18F/cg-docs/issues/403

**Comment by suprenant** [comment]
@dlapiduz what @brittag said – we're still planning on including it. sorry for any confusion!
