### ISSUE TITLE
Government Cloud ATO

### ISSUE THREAD

**Issue by florsem** [cloud-gov/cg-site#1810]
When trying to get a continuous ATO for a government system. What requirements are needed when your non-government organization is trying to start an ATO for a Cloud Platform? We are a new program and we would like to know the government requirements for a 3 year ATO when first starting out? How do we start the process? Is there a Checklist to go from?

**Comment by bengerman13** [comment]
Hi @florsem - thanks for reaching out. We're a Cloud Service Provider - we don't provide ATOs or instructions on ATOs. As a provider, we try to do as much work as possible in the open, so others can leverage our learning, but direct assistance for outside entities looking to gain an ATO is beyond the scope of our work. If you're looking to get and ATO, I'd recommend looking to [FedRAMP's guidance](https://www.fedramp.gov/jab-authorization/).
