### ISSUE TITLE
Move non-Documentation content out of Documentation category

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-site#1836]
A lot of content on cloud.gov is categorized under "Documentation" which causes a lot of problems with the left-side navigation. What would it take to re-categorize content that isn't "Documentation" so that it doesn't live under that bucket and the left navigation will no longer display unnecessarily?

**Comment by karareinsel** [comment]
@onelittlebecca can you add a link to your notes and then we'll close out this issue in favor of #1845 and #1846 ?

**Comment by onelittlebecca** [comment]
Oh, sure! [Here they are in a google doc](https://docs.google.com/document/d/1VF3Dx3_sGf--0FdSuZQlNvLcVT0V7ryzmP5cmiz6EHo/edit?usp=sharing).

**Comment by onelittlebecca** [comment]
Follow up thought: should we close this issue since this might apply to other sections of the site that we haven't worked through or made a plan for yet?

**Comment by karareinsel** [comment]
We can always open new issues for when we get to that point and reference back to this issue. That way we keep the board focused on stories that are being actively worked on.
