### ISSUE TITLE
Consolidate content between What is cloudgov + benefits pages

### ISSUE THREAD

**Issue by onelittlebecca** [cloud-gov/cg-site#1845]
In order to better communicate the information about what cloudgov is and the benefits you get from using the Platform, we want to rework the content on these two pages and consolidate them into one. 

We took a look at the What is cloudgov + benefits pages and realized they could both stand to be pared down and merged together into one clearly written and concise description of what the platform is

--- 

## Security considerations
none

This is a sub-issue of [issue 1836](https://github.com/cloud-gov/cg-site/issues/1836)

**Comment by karareinsel** [comment]
Working draft https://docs.google.com/document/d/1rU8lQ3RcH3dKk90rwVPz7I9bdr20c4SSa28wbECYfqw/edit#

**Comment by karareinsel** [comment]
Pairing with @onelittlebecca and @apburnes today to talk about next steps.
