### ISSUE TITLE
Optimize site navigation

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-site#1860]
So that prospective and existing cloud.gov customers can quickly and easily find the content they need on cloud.gov, the site navigation should be optimized to better meet their needs. Review latest analytics to inform a draft navigational structure that can be tested with users.

[Google analytics data](https://docs.google.com/spreadsheets/d/1mzR_B6VIMgta7_qfxZTJqSqB6AYPWGfUja7NT98_RNc/edit#gid=574694450) 

[cloud.gov site map ](https://app.mural.co/t/gsa6/m/gsa6/1581345078867/ecddcf20b48d92e1b5493ecbf0a78860f2a123eb)created as part of cloud.gov Federalist migration work done by 18F team in winter 2020

**Comment by karareinsel** [comment]
Hoping to pair with @apburnes and @onelittlebecca today or tomorrow.

**Comment by karareinsel** [comment]
Have a call on 1/12 with Julie Strothman (18F) to go over how to run a test on usertesting.com. Very rough draft of [proposed navigation](https://app.mural.co/t/gsa6/m/gsa6/1610117575103/22670c11fe5fceee58506b0a8d0976ba6cbf9847) (to be tested).

**Comment by karareinsel** [comment]
[How to run usertesting.com studies](https://docs.google.com/document/d/1-n79my_695_ogK4oNKsCulFQBK_vEWG4c6r7nmO2eiA/edit#heading=h.7tssvvmxsoxt)

[TTS usertesting.com study queue ](https://docs.google.com/spreadsheets/d/1AOAtx7IeUf-H20pWGHLGmepNf33ZGpC1PttOPBc-T-E/edit#gid=0)

**Comment by karareinsel** [comment]
Meeting with the login.gov team to talk about their recent redesign (Jan. 28).

**Comment by karareinsel** [comment]
[Draft questions](https://docs.google.com/document/d/1t2WscBK-_PvxnWAU3QF64xQGFgKtwITbONJP-rXY7uw/edit#) for cloud.gov user testing.

**Comment by karareinsel** [comment]
@apburnes @onelittlebecca should we close out this issue since we have a draft navigation and create new stories for the actual testing?

**Comment by apburnes** [comment]
That makes sense. This issue is starting to feel more like an epic.

**Comment by karareinsel** [comment]
Closing. Work continues and is represented with new stories.
