### ISSUE TITLE
cloud.gov homepage images aren't loading

### ISSUE THREAD

**Issue by bendelphinegov** [cloud-gov/cg-site#1865]
@ccostino I think this site is great! For some reason the background images aren't loading – screenshots from MacOS Big Sur Chrome and Firefox:
 
<img width="1441" alt="Screen Shot 2021-02-01 at 1 35 46 PM" src="https://user-images.githubusercontent.com/77686273/106508847-7839f880-6492-11eb-97b2-d25dbeefb657.png">

<img width="1618" alt="Screen Shot 2021-02-01 at 1 36 01 PM" src="https://user-images.githubusercontent.com/77686273/106508837-7708cb80-6492-11eb-9741-cf6684b61ca4.png">

**Comment by ccostino** [comment]
Hi @bendelphine, thanks for reaching out!  I checked with the team on this and double checked that the assets on the homepage are loading correctly, too.  At the moment there isn't a background image set for the homepage in the top section, and we're also not seeing any issue with the assets, either.

Were you expecting to see a background image, or was there something that went missing that I didn't capture above?

**Comment by bendelphinegov** [comment]
@ccostino you know I was expecting to see a background image but it is totally possible that one has never existed for this site. those uswds patterns are solid!

appreciate you looking into it, apologies for the distraction :)

**Comment by ccostino** [comment]
@bendelphine 😆 fair enough!  USWDS definitely brings a strong game to that front. :-)

FWIW, this did spur some discussion on our side as we have been thinking about the future of the site and making plans as it is, so we appreciate the feedback!

If there's anything we can help with, please don't hesitate to reach out. :-)
