### ISSUE TITLE
Update AWS Elasticsearch docs to be more helpful

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-site#1879]
Right now, our ES docs are really focused on upgrading from the old ES service, which is really confusing to users who didn't use that service. We also defer a lot to the AWS docs, which means getting things done requires hopping back and forth between pages. 

We should add documentation in tutorial and explanation form to:
- create a service instance
- interact with a service instance from a local command line, including where to get credentials from and spelling out what values a user needs to define themselves (n.b. because of the aws-header stuff, this will probably have to recommend using something like the python or ruby REPL)

We should also document directly that Kibana is not included in this offering, and that it's probably incompatible with this service.

**Comment by mheadd** [comment]
Also, I think there _may_ be some new monitoring and alerting options available with the AWS-brokered ES service. Would this be helpful information to include in our docs page as well?

**Comment by bengerman13** [comment]
Maybe as a separate issue? I worry a little about scope-creep here, and also part of our problem currently (IMO) is that we have more 200-level than 100-level instruction, if that makes sense

**Comment by mheadd** [comment]
~Will also likely want to add details of [options made available by this change](https://github.com/cloud-gov/aws-broker/issues/172) when it is complete.~ Done via [this commit](https://github.com/cloud-gov/cg-site/pull/1999).

**Comment by mheadd** [comment]
~Also related: [pricing change](https://github.com/cloud-gov/cg-site/pull/1991).~ Done.
