### ISSUE TITLE
Support for Docker Swarm

### ISSUE THREAD

**Issue by bselack** [cloud-gov/cg-site#1902]
Looking for details on Docker Swarm support and/or host networking for multiple docker instances that need to communicate. Thanks.

**Comment by ccostino** [comment]
We don't support Docker Swarm in cloud.gov as this is a platform built with [open-source CloudFoundry](https://docs.cloudfoundry.org/).  The platform does support [deploying Docker images](https://cloud.gov/docs/deployment/docker/) of your application in addition to deploying application code directly (which Cloud Foundry takes care of building into an image), but that is the extent of the Docker support.  Regardless of your app deployment method (Docker image or app code directly), you can deploy multiple apps/images, scale, and connect them in a single [manifest file](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-apps).

If it's helpful to you, there is also more information about internal networking within the platform in the Cloud Foundry documentation on [internal routes between containers](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#internal-routes).

If you'd like to learn more about the cloud.gov platform itself, which is available to federal agencies via an inter-agency agreement, I'd recommend reaching out to our inquiries@cloud.gov email to schedule a call and cover things in more detail as well as answer any other questions you may have.  Thanks!
