### ISSUE TITLE
Update example site references at the bottom of the home page (10/19)

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/cg-site#1906]
We have 6 example sites that run on cloud.gov at the bottom of our homepage, and at least one of them has been decommissioned and is no longer live.  We need to update this list/table to make sure we have recent, relevant examples.

## Acceptance Criteria
* [x] GIVEN links to government websites listed on our homepage
  WHEN a user clicks on any of them
  THEN they are taken to a working site

--- 

## Security considerations
- None

## Implementation sketch
* [x] Work with BU/customer engagement to determine which sites to link to; might need to reach out to the client first for permission

**Comment by jkreft-usgs** [comment]
I was just about to open this issue!  Every Kid in a Park looks like it is now every Kid Outdoors ( https://everykidoutdoors.gov/index.htm) though I am not sure if it is still on cloud.gov or not.

https://github.com/cloud-gov/cg-site/blob/2bb8dd9129549a6165a7a86dceb67b68a428b442/index.html#L209

https://github.com/cloud-gov/marketing-site/blob/daef9a5c5ec20f57320dd97acb061e0d48b734ea/index.html#L209

**Comment by ccostino** [comment]
Thanks, @jkreft-usgs!  The site had changed a few months ago and we've been focused on a few other things here, so this was missed initially.  We'll get our homepage updated soon! :-)

**Comment by jkreft-usgs** [comment]
Good deal.  Its actually really helpful for me to point at over here in another Interior agency.  NPS can use cloud.gov, so clearly USGS should be able to as well!

**Comment by ccostino** [comment]
Thanks for letting us know!  And if you haven't already, please reach out to us at inquiries@cloud.gov.  We can schedule a call with you to walk through the platform in more detail and how it might serve USGS' needs, as well as how the inter-agency agreement process works!
