### ISSUE TITLE
Documentation update https://cloud.gov/docs/services/relational-database/ 

### ISSUE THREAD

**Issue by davidhunt-cti** [cloud-gov/cg-site#1911]
The steps to check the database creation status in [https://cloud.gov/docs/services/relational-database/](https://cloud.gov/docs/services/relational-database/) no longer appear to be required. The broker is now correctly reporting “create in progress” in "cf services" and then switches to “create succeeded” when the service is available.

This is the section that should be updated:

> During instance provisioning, the results of cf services or cf service SERVICE_NAME will show status as created, as in the following example:
> \> cf services
name                 service   plan                bound apps   last operation
test-oracle          aws-rds   medium-oracle-se2                create succeeded
The last operation value of create succeeed may lead you to think the database is ready to use. This is misleading. Instead, the last operation indicates the API call to create the database has succeeded, not that provisioning has completed. To determine if a database is ready to use, test if you can create a service key. For example, test-oracle is not yet ready in this case:
cf create-service-key test-oracle test-oracle-ok
Creating service key test-oracle-oke for service instance test-oracle as peter.burkholder@gsa.gov...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: There was an error binding the database instance to the application. Error: Instance not available yet. Please wait and try again..
If the response is OK instead of FAILED then your database is ready to use.
The cloud.gov team aims to provide clearer status indicators in a future release of our service broker.

**Comment by bengerman13** [comment]
thanks for pointing this out, @davidhunt-cti !
