### ISSUE TITLE
Minor corrections to External Domain Service page

### ISSUE THREAD

**Issue by davidhunt-cti** [cloud-gov/cg-site#1920]
A few minor corrections for the External Domain Service documentation web page.

In the 'Compliance impact' section, at [https://cloud.gov/docs/services/external-domain-service/#compliance-impact](https://cloud.gov/docs/services/external-domain-service/#compliance-impact):

1. Fix the misspelling in the first paragraph discussing the P-ATO boundaries:
Commerical -> Commercial

2. The links to the SC-12 and SA-9 in the second paragraph are broken. Updated URLs for the links are:

- SC-12: [https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SC-12](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SC-12) 
- SA-9: [https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SA-9](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SA-9) 

In the 'CNAME and ALIAS records' section at [https://cloud.gov/docs/services/external-domain-service/#cname-and-alias-records](https://cloud.gov/docs/services/external-domain-service/#cname-and-alias-records)

3. Remove the duplicated word from "has only one one dot"

In the 'How to create an instance of this service' section at [https://cloud.gov/docs/services/external-domain-service/#how-to-create-an-instance-of-this-service](https://cloud.gov/docs/services/external-domain-service/#how-to-create-an-instance-of-this-service)

4. Fix the misspelling in step 2:
lauched -> launched

**Comment by ccostino** [comment]
Thank you, @davidhunt-cti!  A few of the spelling mistakes have been corrected just a bit ago today, and we'll take a look at the links too.
