### ISSUE TITLE
Left hand menu items do not expand

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-site#1932]
Left hand menu items do not expand when clicked on, and the following error appears in the console:

```
mermaid.min-65ac0c317e487d08312a7a1405f2573908ad3cc3cb5a636152dd59ed8b59b76c.js:24 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t (mermaid.min-65ac0c317e487d08312a7a1405f2573908ad3cc3cb5a636152dd59ed8b59b76c.js:24)
    at mermaid.min-65ac0c317e487d08312a7a1405f2573908ad3cc3cb5a636152dd59ed8b59b76c.js:24
    at Array.forEach (<anonymous>)
    at t (mermaid.min-65ac0c317e487d08312a7a1405f2573908ad3cc3cb5a636152dd59ed8b59b76c.js:24)
    at Object.initialize (mermaid.min-65ac0c317e487d08312a7a1405f2573908ad3cc3cb5a636152dd59ed8b59b76c.js:24)
    at Object.initialize (util.js:1)
    at app-8363c5c947072c8bedd4afd797bc382b42b4d6ec30697275cbe758703e976445.js:4
```

This issue has cropped up before and the [resolution seemed to be stepping the version of mermaid.js down](https://github.com/cloud-gov/cg-site/pull/1838).

**Comment by mheadd** [comment]
[This](https://github.com/cloud-gov/cg-site/commit/9e4b249f0d40b7f0b840ddbbc8a53a418052fcf0) appears to be the commit that did it.

**Comment by ccostino** [comment]
It looks like just the `package-lock.json` file was updated in this case - the `package.json` file still has the older version listed in it.

I see three references to it in the `package-lock.json` file, two of which have a newer version.  Think a PR to step down to match the required version will suffice?

**Comment by ccostino** [comment]
Then again, that file is supposed to be auto-generated, so I'm not quite sure the best way to fix this since we do have this version specified...  there are dependencies upon dependencies; dependencies all the way down. :-)
