### ISSUE TITLE
As an outside agency, I want to know how an ATO on cloud.gov will work

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#197]
This question seems to come up a lot. We are answering the question for 18F staff in [Before You Ship](https://pages.18f.gov/before-you-ship/ato/delegation/), but there should really be some information on the docs site about where responsbility lies for what. Feel free to convert this into a card or whatever it should be.

/cc @18F/ato https://github.com/18F/product-guide/issues/21

**Comment by afeld** [comment]
Some inspiration, via @mogul:
- https://policy.catalyze.io/#compliance-inheritance
- https://policy.catalyze.io/#hipaa-inheritance-for-paas-customers

https://18f.slack.com/archives/compliance-toolkit/p1454299968000306

**Comment by mogul** [comment]
Card [created](https://trello.com/c/gU6Z3HXB/661-provide-ato-guidance).

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/cg-docs/issues/327.
