### ISSUE TITLE
Offboard Haywood Wells (8/4) - waiting on confirmation for anything else

### ISSUE THREAD

**Issue by melanienleopold** [cloud-gov/cg-site#1970]
In order to complete Haywood's exit from the cloud.gov team, the assignee should complete a prescribed set of tasks that will remove any special access.

# Directions:

**Assignee:** The tasks below are organized by the role needed to complete them. If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

For compliance we need to show that critical offboarding actions happen within 24 hours of departure; some actions below **need GitHub issues comments** when completed. Completing tasks _before_ departure is good. (control PS-4: personnel termination)

## Haywood Wells

- [x] Initiate the process via the [Leaving TTS Handbook page](https://handbook.18f.gov/leaving-tts/)

## Assignee
- [x] Mention the TTS HR liaison and TTS Tech Portfolio in this ticket so they can update with their status
  - As part of TTS offboarding, TTS Tech Portfolio will automatically:
  - Remove their access to [StatusPage](https://manage.statuspage.io/organizations/btc69fwyvjh7/team) 
  - Remove them from [the cloudgov subteam in Docker Hub](https://hub.docker.com/u/18fgsa/dashboard/teams/?team=cloudgov)
  - Remove write/push access for NPM from [cloudgov-style](https://www.npmjs.com/package/cloudgov-style)
  - Remove them from [HackerOne](https://hackerone.com/)
  - If they are leaving GSA, ask `#admins-slack` to convert them to a single-channel alumni user
  - Remove their agent access to Zendesk - [switch their role to "end user"](https://cloud-gov.zendesk.com/agent/admin/people)
  - Remove them from [the cloud.gov group](https://app.cloudcheckr.com/Admin/UserGroupBuilder/fb111fab-ef5d-48d0-9472-cff691e1bd9c) in CloudCheckr
  - Update this issue with a comment within 24h of departure that the above steps are complete
- [x] Remove them from `@cg-team`, `@cg-operators`, and any other `@cg-` teams in the Slack Team Directory [using the three-dot menu (instructions)](https://get.slack.help/hc/en-us/articles/212906697-User-Groups)
- [x] Remove them from the [team roster](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Remove them from the [squad list](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#squads)
- [x] In the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0): if they're staying at TTS, move them to the "former teammates" tab; if they're leaving TTS, delete them from the spreadsheet
- [x] Remove them as invitees for any meetings on the cloud.gov calendar where they are specifically named
    - Invites where they are listed as part of the `cloud.gov` invitee group will be removed when they are removed from that group by the System Owner

## System Owner (or person delegated by System Owner)

**The following steps must be conducted and documented within 24 hours of departure**:

- [x] Exit interview with supervisor or contract account manager: Discuss with departee the following _information security topics_:
  - They are to remove any non-public cloud.gov data (e.g. keys, passwords, code, documents) from any non-GSA device
  - They are not to disclose any non-public cloud.gov technical practices without authorization from GSA
  - They will not access cloud.gov systems or services without authorization from GSA
  - If the System Owner cannot hold this discussion, they will communicate to GSA OHRM that the above topics need to be communicated to the leaving person.
- [x] Remove them from the [cloud.gov Github organization](https://github.com/orgs/cloud-gov/people)
- [x] Remove them from [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov/members/active)
- [x] If they are part of the business unit, remove their access to [GovDelivery](https://admin.govdelivery.com/administrators)

The following do not directly impact cloud.gov security & operations and can happen later:

- [x] Remove them from [Nessus](https://nessus.fr.cloud.gov/#/settings/users)
- [x] Remove them from the [Cloud Foundry Community GitHub org cloud.gov team](https://github.com/orgs/cloudfoundry-community/teams/cloud-gov/members)
- [x] Remove them from the `CG-PRIV` Google Group
- [x] Remove them from [the cloud.gov operations Google Group](https://groups.google.com/a/gsa.gov/forum/#!managemembers/cloud-gov-operations/members/active)
- [x] Remove them from [the cloud.gov compliance team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov-compliance/members/active)
- [x] Remove them from [the cloud.gov notifications Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov-notifications/members/active)
- [x] Remove them from [the cloud.gov inquiries Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov-inquiries/members/active)
- [x] Remove them from [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov-support/members/active)
- [x] Remove them from [the cloud.gov emergency Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!managemembers/cloud-gov-emergency/members/active)
- [x] Remove them from [our Google Groups for our AWS accounts](https://docs.google.com/document/d/110o1L7EOby3hvE5d-cDhg2LBLHymbZLnMPe9kuk4qp8/edit#) (relevant for PM, Director, and Deputy Director)
- [x] Remove them from [Search.gov](https://search.gov/) access for cg-site by pinging the search.gov team in the #search Slack channel

## Cloud Operations

**The following steps must be conducted and documented within 24 hours of departure**:

- [x] Delete the user in all cloud.gov AWS accounts.  There should be info on which AWS accounts you need to look at [here](https://docs.google.com/document/d/110o1L7EOby3hvE5d-cDhg2LBLHymbZLnMPe9kuk4qp8/edit)
- [x] Remove their account name from the [`inputs.yml` file in the AWS account audit](https://github.com/cloud-gov/cg-compliance/blob/master/audit/inputs.yml)
- [x] [Remove their access as an admin](https://cloud.gov/docs/ops/managing-users/#managing-admins) on the platform on all environments (tooling/ops, development, staging, and production)
- [x] Remove any privileges that their cloud.gov account has due to membership in the cloud.gov team (even if not in Cloud Ops), such as `admin_ui.user` and `scim.read`
    - [x] Verify these permissions have been removed using the [cg-scripts validate-admins.sh](https://github.com/18F/cg-scripts/blob/master/validate-admins.sh) run from a jumpbox
- [x] Remove any Org or Space roles that their cloud.gov account holds due to membership in the cloud.gov team (for example, remove them from the `cloud-gov` and `cloud-gov-operators` organizations)
- [x] Ensure any keys or passwords they had direct access to are rotated

**Comment by ccostino** [comment]
@kelleyconfer because Haywood is a contractor, I know there are some additional steps or folks to reach out to, so I've added you to this ticket.  I'll run through as much as I can, please let me know if there's anything else I can help with!

**Comment by ccostino** [comment]
Squad list update PR in place: https://github.com/cloud-gov/product/pull/1598

**Comment by ccostino** [comment]
@bengerman13 could you please remove Haywood from https://groups.google.com/a/gsa.gov/g/cloud-gov-notifications/members?  Thanks!

**Comment by ccostino** [comment]
Removed Haywood from all the Google Group accounts and Nessus; search.gov, GovDelivery don't apply as Haywood never had access.

**Comment by ccostino** [comment]
Removed Haywood from cloud.gov's GitHub organization and teams.  Also removed any direct invites to team events on the calendar.

**Comment by ccostino** [comment]
Haywood's AWS accounts have been deleted.

**Comment by ccostino** [comment]
Removed all of Haywood's admin access on the platform:

Ops Admin:
<img width="597" alt="Screen Shot 2021-07-30 at 10 48 10 AM" src="https://user-images.githubusercontent.com/121565/127671920-470374d4-d5f4-471c-87f1-0e91ec285e7a.png">

CF Admin:
<img width="625" alt="Screen Shot 2021-07-30 at 10 56 20 AM" src="https://user-images.githubusercontent.com/121565/127672001-1eb76158-dfc2-4e27-bcdb-b07dc126285c.png">

**Comment by ccostino** [comment]
Removed Haywood from any `cloud-gov` or `cloud-gov-operators` orgs and spaces in the platform.

**Comment by ccostino** [comment]
Sent a message to leavingTTS@gsa.gov.

@JJediny, @afeld, and/or @adborden, if there's anything else you need from us here to help complete Haywood's offboarding from cloud.gov and TTS please let us know!  He did not have any accounts with HackerOne, StatusPage, Docker Hub, Cloudcheckr, etc.

**Comment by ccostino** [comment]
I think the Slack access is all that should remain - I already removed Haywood from our private channels.

**Comment by ccostino** [comment]
Submitted a deactivate Slack user request via ServiceNow:

Submitted : 2021-07-30 11:21:33 AM
Request Number : REQ0625778
Estimated Delivery : --

**Comment by ccostino** [comment]
Removed Haywood's AWS account name from our AWS account audit: https://github.com/cloud-gov/cg-compliance/pull/241

**Comment by ccostino** [comment]
Haywood's Slack account was deactivated on 7/30: https://gsa-tts.slack.com/archives/C02KW46DP/p1627659165001000

<img width="350" alt="Screen Shot 2021-08-02 at 10 50 52 AM" src="https://user-images.githubusercontent.com/121565/127880827-91cc3c0c-b2d1-42ca-80bc-e68e53303d15.png">

**Comment by adborden** [comment]
Hey @ccostino usually the Tech Portfolio's checklist kicks in as part of the [TTS Offboarding](https://docs.google.com/spreadsheets/d/1rp8n78tFHqyvvHzsYuBo_XE3Jg1LwOuOX-R9TMRnZI8/edit#gid=1012037864). I'll double check your list here against what we have.

BTW, is this issue part of a template? I think StatusPage moved from Tech Portfolio to cloud.gov since you're the only team using it. I'd want to update the template to reflect that (and in case I find anything else that needs updating).

**Comment by kelleyconfer** [comment]
Rocal has been updated with departure date of 07/30/2021. 

Offboarding ticket has been submitted for account deletion and postage for GFE return has been requested.

**Comment by afeld** [comment]
> you're the only team using [StatusPage]

Login.gov does as well: https://logingov.statuspage.io/

**Comment by ccostino** [comment]
Thanks, @adborden and @afeld!

@adborden, yes, this issue is based on a template on our side, which is actively being updated (this format had some tweaks/adjustments we're trying for the first time!).
