### ISSUE TITLE
Announce and document the new space application security group egress rules.

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-site#2002]
In order to inform platform customers about the new space level egress controls, we want to document the different types of egress controls, how they will be applied to customer spaces, and how to implement an outbound proxy.

## Acceptance Criteria
* [x] Create a blog post announcing the new space egress rules
* [x] Add the egress rules to our documentation
--- 

## Security considerations
- Will inform customers of our addition of restricted egress rules

**Comment by mheadd** [comment]
Good thoughts here on how to visually display the egress rules. https://github.com/cloud-gov/cg-site/issues/2019

**Comment by LindsayYoung** [comment]
I checked the first box because there is a post up: https://cloud.gov/2021/11/16/controlled-space-egress/

Feel free to un check if that was a reference to something else.

**Comment by mheadd** [comment]
@apburnes and I chatted on this today, and a few of the items we touched on were:

* Update docs and get reference proxy app pushed out [before merging changes](https://github.com/cloud-gov/cg-scripts/pull/181) to org creation script that set up new ASGs, to avoid confusion.
* We might want to set up a brand new org with new ASG types for our own personal testing, demo apps, etc.
* Near term deliverable should be a reference app using some sort of forward proxy tool that demonstrates how to access S3 from `restricted-egress` or `close-egress` ASGs.

**Comment by mheadd** [comment]
Demo App Implementation Sketch:

App 1: Simple Node.js + express app that serves a file(s) from S3 via a REST endpoint
App 2: Proxy application (squid, HA proxy, something else?)

*  App 1 runs running in either `restricted-egress` or `closed-egress` ASG.
*  App 2 runs in `public-egress` ASG.
* App 1 exposes 2 routes:
     - one route attempts to make direct call to S3 (which will fail)
     - other routes request through proxy on App 2 (which will work)

Notes:
* [proxy-agent module](https://www.npmjs.com/package/proxy-agent) might be a good choice for this.
* Also, worth exploring if [setting `http_proxy` and/or `https_proxy` settings](https://docs.cloudfoundry.org/buildpacks/proxy-usage.html) makes sense.
