### ISSUE TITLE
Clarify ASG egress space types

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/cg-site#2019]
In order to easily and quickly understand the various ASG egress space types, we want a table to summarize the differences.

## Acceptance Criteria
* [ ] A table is added to the content

--- 

## Security considerations
None - just documentation

## Implementation sketch
| ASG Type | WWW | AWS S3 | AWS RDS | AWS Elasticache Redis | AWS Elasticsearch | Internal Routes |
| :-------- |  :-:  | :--: | :-------: | :---------------------: | :-----------------: | :---------------: |
| `public-egress`     | ✅  | ✅ | ✅ | ✅ | ✅ | ✅ | 
| `restricted-egress` | ❌  | ❌ | ✅ | ✅ | ✅ | ✅ |
| `closed-egress`     | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |

**Comment by bengerman13** [comment]
Love the idea of using a chart here, Dave!
