### ISSUE TITLE
incorporate notes from Google Docs

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#202]
A couple people had written up notes:
- [ ] [EPA on-boarding](https://docs.google.com/document/d/1HOWUV_cqwyfOXJ_2ssb_FU7pdHjhQGmvi1OKxxN0aCc/edit)
- [ ] @meiqimichelle's [notes from an 18F Cloud Foundry workshop](https://docs.google.com/document/d/10Ql-HrxVOm7KHld48HiZMSdONuy2TTUnB-bYVna8wz4/edit)

**Comment by jmcarp** [comment]
Looking over these notes, I see that lots of things have changed since January 2016, hopefully for the better. Closing unless there's some concrete thing we should do with these notes @afeld.

cc @brittag @mogul
