### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#205]
@msecret I'm seeing [a folder under cg-style](https://github.com/18F/cg-style/tree/master/img/favicons), but there isn't one appearing for the live site. https://cloud.gov has a :cloud: favicon, but maybe it should be switched to the new logo?

**Comment by msecret** [comment]
Yes it should, I haven't added this to cg-style and the other repos yet, but plan to do so.

Also, the favicons in those folders are from uswds, so it would not use those.

**Comment by afeld** [comment]
Seems to be solved!

![screen shot 2016-04-02 at 9 47 26 pm](https://cloud.githubusercontent.com/assets/86842/14230241/84a6bf7c-f91c-11e5-9e45-da4b6cd6aa7e.png)
