### ISSUE TITLE
Update Kibana troubleshooting steps

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-site#2066]
The [5 of 900 shards steps](https://cloud.gov/docs/ops/runbook/troubleshooting-logsearch/#fixing-5-of-900-shards-failed) need to be updated.

**Comment by bengerman13** [comment]
the upshot on this error is that one day's index is not queryable. 
This can happen for a lot of reasons. I think the most common we encounter is still the issue documented [here](https://cloud.gov/docs/ops/runbook/troubleshooting-logsearch/#fixing-5-of-900-shards-failed) - one day's field types are different from the others'

**Comment by mheadd** [comment]
Yeah, agreed. When @rbogle and I went through the steps today, we noticed that the Kibana interface had changed, and the description of how to navigate the UI was slightly different.
