### ISSUE TITLE
offer direction for different audiences

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#209]
@melodykramer asked the question "where should new 18F developers hires be directed to learn about cloud.gov?" I think that [deploying](https://docs.cloud.gov/getting-started/your-first-deploy/) is the best first step for technical folks, just to get a feel for it, whereas acquisition folks will be most interested in the [pricing](https://docs.cloud.gov/intro/pricing/rates/), [what's included](https://docs.cloud.gov/intro/pricing/whats-included/), etc. I'm thinking that having the homepage say "are you interested in X? go to this page" would be a good way to tackle these different paths for different audiences, but am curious what others think.

/cc @jameshupp

**Comment by melodykramer** [comment]
I think it would be helpful for technical newcomers to learn two specific things:

"if you need to get something online, then you need to use cloud.gov"

Then "this is how you put something online using cloud.gov"

I think being led to docs.cloud.gov can be overwhelming and lets them know about features, but they’re not necessarily making the connection that they should use it for everything.

**Comment by brittag** [comment]
This is more an 18F engineering onboarding issue than a cloud.gov docs issue, and I think it's already handled by 18F engineering.
