### ISSUE TITLE
It would be good if contractors could have access to sandbox accounts

### ISSUE THREAD

**Issue by ferlatte** [cloud-gov/cg-site#2152]
In order to make it possible for contractors to train staff on cloud.gov, I (and TrussWorks, my company) would like to be able to request sandbox environments as non-government employees.

Currently, even if cloud.gov would make sense for a given project, there's no way we'd suggest using it in an RFP since we can't practice on it. While I acknowledge that CloudFoundry is open source and we could set up our own, that's not very appealing;  cloud.gov is literally the only cloud foundry instance we've encountered in 10+ years of work. It's not in demand from our customers.

I'm sure there's a million reasons why this is difficult; however, given how dependent the government is on external contractors, it seems like it was worth asking about.

**Comment by mheadd** [comment]
Thanks for asking this, @ferlatte. Let me confirm something with our engineering team and then I might be able to provide some additional info. on this.

**Comment by mheadd** [comment]
@ferlatte While not exactly what you are looking for, I wanted to make sure you were aware that non-government employees can be added to existing sandbox spaces. So, if an agency has a sandbox, a non-government employees can be added as a user by 1) inviting them, and then 2) assigning them a space developer role in that sandbox. More details here: https://cloud.gov/docs/orgs-spaces/roles/#adding-roles-via-the-dashboard-for-users-to-access-orgs-and-spaces

This still requires someone at the agency to create and manage the sandbox, but it is one way for non-government employees to access sandboxes.

**Comment by ferlatte** [comment]
I appreciate the workaround and the timely response! 

This is good to know; we have been asked if cloud.gov would be viable for some of our clients, and this pattern would let us help them decide based on their use cases.

Feel free to close this out, although if there *is* a way to get the policy changed I'd still request it. :)

**Comment by mheadd** [comment]
This questions has come up before, so I'll close this issue but will try and update if a viable way of doing this is identified. Thanks again for raising it.
