### ISSUE TITLE
Finalize and merge cloud.gov/pages branch

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-site#2154]
In order to transition to cloud.gov, we need to finalize and merge the pages branch to deploy the marketing site on cloud.gov/pages/ 

## Background
- See PR https://github.com/cloud-gov/cg-site/pull/1956 to be merged
- Review and compare the [preview site](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/pages/pages)

## Acceptance Criteria
- [x] Review content on [preview site](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/pages/pages), compare with current federalist.18f.gov, and add any missing information to PR
- [x] Add SCR migration content to the pages branch about the transition from Github auth to Cloud.gov UAA and the creation of organizations to manage sites and users. 
- [x] Update PR so it can be merged into the production branch
- [x] Merge #1956 

## Security Considerations
Needed to support Pages SCR

**Comment by apburnes** [comment]
@drewbo for the SCR migration content, maybe we create a specific page with a migration guide for our customers. First iteration will probably just be the high level about transitioning from Github to Cloud.gov UAA authentication, the creation of Organizations, and to email support if they are interested in being early adopters. As we start to migrate customers, we can continue to expand and refine the guide.

**Comment by drewbo** [comment]
Replaced #1956 with #2179 and merged
