### ISSUE TITLE
Include rates in the marketplace

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/cg-site#220]
According to `rates.md`:

> You can see the rate for each type of service instance offered by running `cf marketplace`.

As far as I can tell, `cf marketplace` doesn't display rates for any available services--it only indicates which services are free and which are paid. Ideally `cf marketplace` would show prices, but until it does, let's keep the docs accurate. Maybe this line could read "you will eventually be able to see rates using `cf marketplace`".

Or maybe I'm just misinterpreting the output of `cf marketplace`--let me know if I am!

@mogul

**Comment by jmcarp** [comment]
Ping @mogul

**Comment by brittag** [comment]
Page no longer says this, and we'll look again at how want to handle explaining per-service rates when we get to the point for charging for services.
