### ISSUE TITLE
The email address pages-support@gsa.gov bounces

### ISSUE THREAD

**Issue by h-m-f-t** [cloud-gov/cg-site#2248]
pages-support@gsa.gov is [used](https://cloud.gov/pages/documentation/custom-domains/#notify-pages) in your documentation, but it bounces. https://cloudgov.statuspage.io/ says the address is pages-support@cloud.gov, which did successfully work for me.

The @gsa.gov address may be used other places; I did not search exhaustively.

## Acceptance Criteria

- [ ] As a user, the emails I send to the address named on Cloud.gov/Pages land at the right place for action.

**Comment by drewbo** [comment]
Thanks for flagging @h-m-f-t, looks like this is only on one page, we'll get it fixed shortly
