### ISSUE TITLE
Add documentation for adding new Pages users

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/cg-site#2275]
cloud.gov Pages doesn't have documentation on how to manager users and it's leading to some confusion (especially since we still haven't deprecated the collaborators tab). We should add a page to our documentation which clarifies the following:
- Users need to ask their organization manager for access
- Organization managers can add new users via the pages -> organization pane -> edit organization -> add new user
  - Screenshots would be helpful here, especially until we get improved UX
- CMS users still need to login to pages.cloud.gov first before using the content editor

## Acceptance Criteria

- [ ] New documentation post exists detailing the above information

cc: @cloud-gov/pages-ops

**Comment by svenaas** [comment]
@Ephraim-G, how can I help with this? 

Note that we **have** now removed the Collaborators tab: cloud-gov/pages-core#4085 (in production, even, as of cloud-gov/pages-core#4086).
