### ISSUE TITLE
508 Issues from pa11y-rails

### ISSUE THREAD

**Issue by nickbristow** [cloud-gov/cg-site#231]
Results can be recreated using [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/)
## Results for https://docs.cloud.gov
- **Error** Anchor element found with a valid href attribute, but no link content has been supplied.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
  - `#introduction:d680e8a854a7cbad6d490c445cba2eba > a`
  - `<a class="anchorjs-link " href="#introduction:d680e8a854a7cbad6d490c445cba2eba" aria-label="Anchor link for: introduction:d680e8a854a7cbad6d490c445cba2eba" data-anchorjs-icon="" style="opacity: 1; font-family: anchorjs-icons; font-style: normal; fon...`
- **Error** Anchor element found with a valid href attribute, but no link content has been supplied.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
  - `#sections:d680e8a854a7cbad6d490c445cba2eba > a`
  - `<a class="anchorjs-link " href="#sections:d680e8a854a7cbad6d490c445cba2eba" aria-label="Anchor link for: sections:d680e8a854a7cbad6d490c445cba2eba" data-anchorjs-icon="" style="opacity: 1; font-family: anchorjs-icons; font-style: normal; font-varian...`
- **Error** Heading tag found with no content. Text that is not intended as a heading should not be marked up with heading tags.
  - WCAG2AA.Principle1.Guideline1_3.1_3_1.H42.2
  - `html > body > header > div > h2`
  - `<h2 class="header-title">
        <a href="https://clo...</h2>`
- **Error** Anchor element found with a valid href attribute, but no link content has been supplied.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
  - `#usage:d680e8a854a7cbad6d490c445cba2eba > a`
  - `<a class="anchorjs-link " href="#usage:d680e8a854a7cbad6d490c445cba2eba" aria-label="Anchor link for: usage:d680e8a854a7cbad6d490c445cba2eba" data-anchorjs-icon="" style="opacity: 1; font-family: anchorjs-icons; font-style: normal; font-variant: nor...`
- **Error** Anchor element found with a valid href attribute, but no link content has been supplied.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
  - `#contributing:d680e8a854a7cbad6d490c445cba2eba > a`
  - `<a class="anchorjs-link " href="#contributing:d680e8a854a7cbad6d490c445cba2eba" aria-label="Anchor link for: contributing:d680e8a854a7cbad6d490c445cba2eba" data-anchorjs-icon="" style="opacity: 1; font-family: anchorjs-icons; font-style: normal; fon...`
### Summary

**Errors:** 5

**Comment by mogul** [comment]
Closing as stale
