### ISSUE TITLE
Add Knowledge Base tab and section for cloud.gov Pages

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-site#2334]
## Background

Add a tab titled "Knowledge base" to our [](https://cloud.gov/pages/) home page. Create an index page which will house all the links to Pages knowledge base articles a la [](https://cloud.gov/knowledge-base/). 

* [x] Create a folder in the root dir "kbarticlespages"
* [x] Create an index page and name it as a sub path
* [x] incorporate link to kb article
* [x] add .md file to (?)
* [x] Add kbarticles to collections
* [x] add title and subpath to the navigation.yml file for Pages

## Considerations

Jekyll assets is 💀 (?) how to correctly incorporate images via parcel

## Testing

Build site locally

## Security Considerations

N/A 

Add a tab and section in cloud.gov Pages to hold our Knowledge Base articles

## Acceptance Criteria
TDB

**Comment by Ephraim-G** [comment]
link checker failed with 

Run CI_CONFIG_FILE="_config_ci.yml"

> cg-site@1.3.0 build
> run-s prod:parcel jekyll --config _config.yml,_config_ci.yml

ERROR: Invalid Option: --config
Error: Process completed with exit code 1.

**Comment by drewbo** [comment]
Closed via https://github.com/cloud-gov/cg-site/pull/2357
