### ISSUE TITLE
document options for recurring tasks

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#234]
> @monfresh: Does cloud.gov have the equivalent of Heroku’s scheduler? I want to run a command once a day at the same time.
> 
> @afeld: take a look at https://github.com/18F/cg-cron. [C2](https://github.com/18F/C2) uses [Clockwork](https://github.com/tomykaira/clockwork) via [Foreman](https://github.com/ddollar/foreman) ([entry point](https://github.com/18F/C2/blob/eb3df2a81d7a2aed97dc15ec5dd39a874a4ca6ea/manifest.yml#L7)) if you are using a Ruby app.

https://18f.slack.com/archives/cloud-gov/p1458062762000038

**Comment by jessieay** [comment]
Dolores bot also uses a clockwork / foreman combo on Cloud.gov (inspired by C2) to send jobs once a minute https://github.com/18F/dolores-landingham-bot/

**Comment by monfresh** [comment]
Yep, I ended going that route as well. It works great. Here's the PR: https://github.com/18F/seal/pull/7

**Comment by afeld** [comment]
The new(-ish) [task API](https://blog.pivotal.io/pivotal-cloud-foundry/products/using-diego-to-schedule-one-off-tasks-in-cloud-foundry) might be relevant here.

**Comment by mogul** [comment]
It's still wildly experimental and not everything is in the CLI yet. Use caution.

**Comment by jmcarp** [comment]
So what would the docs say here? As @jezhumble pointed out on slack, our cron repos are basically abandoned, and I'm not sure if anybody is using them lately. It seems like our implicit stance on scheduling tasks is "bring your own scheduler"--we can write that down and link to examples if that would be useful.

**Comment by brittag** [comment]
This will be resolved by https://github.com/18F/cg-site/pull/1072
