### ISSUE TITLE
Anchor links no longer appearing in docs

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#235]
What we're after: 
 - Reviewing this issue to determine if it's a valid issue or not

Notes:
 - This should appear on at least every H2, H3 (not H1), and possibly beyond
 - Thinking that some of our dashboard changes could be affecting the docs. So, it'd generally be good to keep an eye on this sort of think in the future.

Hovering over a heading on any particular page isn't appearing...not sure if it's a CSS conflict or something? Not immediately obvious what the issue is.

/cc @msecret 

Acceptance criteria:
 - [ ]  Team member pulls most recent master (cg-style, cg-site) and reports whether or not the anchor links are working properly.

**Comment by msecret** [comment]
@afeld do we know what version(or commit hash) of the repo is currently on production? I know at some point we were not seeing most recent changes deployed, and that might point to the issue.

**Comment by afeld** [comment]
Wercker indicates that it's da8fe4940cac1e0e53534a864f24e4134d1511c5, deployed yesterday.

https://app.wercker.com/#applications/55036dfb210ef9cf6a005391/tab/deployment/

**Comment by msecret** [comment]
Looks like the JS is on the page:

```
  // AnchorJS
  anchors.options.visible = 'touch';
  anchors.add('.content h2,.content h3,.content h4,.content h5');
```

**Comment by msecret** [comment]
It could be that the anchorjs icons aren't loading correctly. I can't find them in the resources/network panel.

**Comment by suprenant** [comment]
@thisisdano to take a quicker look to see to if he can reproduce this. If not, he'll ask for some help.

**Comment by suprenant** [comment]
![screen shot 2016-12-06 at 12 25 15 pm](https://cloud.githubusercontent.com/assets/1452369/20940201/87dc5bc6-bbb7-11e6-8b5e-2c0a8c1bcfa8.png)

^production

**Comment by afeld** [comment]
Seems to have been fixed!

**Comment by thisisdano** [comment]
This seems to be a new issue now. Anchor links are no longer appearing at all in my local instance (but they are on cloud.gov).

Locally, the heds are missing the `<a class="anchorjs-link ">`

@msecret @line47 can you reproduce?

**cloud.gov**
![screen shot 2016-12-06 at 11 25 01 am](https://cloud.githubusercontent.com/assets/11464021/20940188/b73191cc-bba6-11e6-8d70-c6a92a0c474d.png)

**local**
![screen shot 2016-12-06 at 11 25 09 am](https://cloud.githubusercontent.com/assets/11464021/20940194/bd2b6bfc-bba6-11e6-8806-34373a4d0890.png)

**Comment by thisisdano** [comment]
See above ^^^

I see a new anchor link issue now... May as well piggyback on this issue since it's on our radar.

**Comment by line47** [comment]
I just got latest on this project and am seeing anchor links at H2 and H3 headers.

### Screenshot
<img width="747" alt="screen shot 2016-12-07 at 10 28 26 am" src="https://cloud.githubusercontent.com/assets/1449852/20973860/2dbd08aa-bc68-11e6-8331-da1937ddb98f.png">

**Comment by thisisdano** [comment]
OK. huh. Cos not only do you see the links, but the spacing seems better than mine. (See space between the `ol` and the `h2`) — wtf?

I _seem_ to be on the latest master for both cg-site and cg-style...

- - -

<img width="694" alt="screen shot 2016-12-07 at 8 01 10 am" src="https://cloud.githubusercontent.com/assets/11464021/20975144/61430860-bc53-11e6-8bdb-62d6c943ee71.png">

**Comment by suprenant** [comment]
@adborden to lend a hand here

**Comment by adborden** [comment]
We worked out the issue with @thisisdano 's setup and think this issue is fixed. @thisisdano do you want me to open a separate issue for the header spacing since that seems to be a valid bug.
