### ISSUE TITLE
Update mermaid and netlify-cms to fix outdated javascript libraries

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-site#2362]
The ZAP scans, and our 3pao, have fingered us for some outdated javascript libraries.

mermaid and netlify-cms both have outdated`moment.js`.

Bumping mermaid in the past has resulted in bugs (even within 8.x): #1838

We can do without netlify-cms IMO, but maybe others rely on it.

## Acceptance Criteria

- [x] ZAP scan is clean for javascript libraries

**Comment by drewbo** [comment]
@pburkholder should be good via https://github.com/cloud-gov/cg-site/pull/2369, let me know when we scan next to confirm

**Comment by drewbo** [comment]
Completed a ZAP scan, no vulnerable JS libraries flagged
