### ISSUE TITLE
As a user, I want to be able to search cloud.gov documentation

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#24]
http://gohugo.io uses a [Google Custom Search Engine](https://www.google.com/cse/), which it seems we can't create in our Google Apps account :confused:

**Comment by afeld** [comment]
...though it's also feeling a bit silly starting to duplicate features of the Hub.

**Comment by afeld** [comment]
Ah, found a trick through another site: we can have a search box that redirects the user to Google, using the search term `<query> site:docs.cloud.gov`. Example:

https://www.google.com/search?q=organizations+site%3Adocs.cloud.gov

Not ideal since they leave the site, but better than nothing.

**Comment by mogul** [comment]
Closing this one in favor of https://github.com/18F/cg-deck/issues/237 which is also `In Progress`.
