### ISSUE TITLE
Errors in s3 App Documentation

### ISSUE THREAD

**Issue by lukad03** [cloud-gov/cg-site#243]
In the s3 service documentation, the command for creating a service is incorrect and needs to be changed from `cf create-service <APP_NAME>-s3 s3 basic` to `cf create-service s3 basic  <APP_NAME>-s3`.

For consistency, the instructions for creating an empty s3 app should also reflect this second step. For example:

```
mkdir <APP_NAME>-s3
cd <APP_NAME>-s3
touch Staticfile
cf push <APP_NAME>-s3
```

**Comment by mogul** [comment]
Resolved in #264. Sorry for the long delay!
