### ISSUE TITLE
update pricing on pages proposal 

### ISSUE THREAD

**Issue by sknep** [cloud-gov/cg-site#2471]
[Pages one-pager
](https://cloud.gov/assets/documents/Pages-Proposal.pdf)
is out of date. Kelsey and I worked on a new revision at https://docs.google.com/document/d/1CwWJrlLh36Z7rsmauP9W5xxZkBg5H_fX3YzE_IrygPk/edit

Print flyers and hang up around federal buildings.

We need to publish this :)

**Comment by svenaas** [comment]
Work in progress [preview link](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.sites.pages.cloud.gov/preview/cloud-gov/cg-site/2471-update-pricing/pricing/). Currently includes pricing updates for existing services and the updated Pages one-pager PDF, but does not yet include the new Elasticsearch offerings.

**Comment by svenaas** [comment]
Published: #2499
