### ISSUE TITLE
The recommended multi-buildpack has been deprecated

### ISSUE THREAD

**Issue by DavidEBest** [cloud-gov/cg-site#248]
The multi-buildpack mentioned in the [docs](https://docs.cloud.gov/apps/multi-buildpack-deploys/), ddollar's [heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi) has been deprecated. According to the [warning message](https://github.com/ddollar/heroku-buildpack-multi/commit/1888902a4cabfe63f46c7d684dd772cff14312e8), it'll stop functioning 1/1/2017.

The documentation should be updated with a new recommendation.

**Comment by afeld** [comment]
Bummer! That being said, it no longer functioning on Heroku doesn't mean it won't still function in Cloud Foundry. Maybe there will/should be a CF fork?

**Comment by brittag** [comment]
We resolved this problem by recommending a maintained fork (https://github.com/18F/cg-docs/pull/411) and clearly marking buildpack-multi as experimental/unsupported in general (https://github.com/18F/cg-docs/pull/442).
