### ISSUE TITLE
CLOUD.GOV - Need information about hosting a website for our Gov client

### ISSUE THREAD

**Issue by 100SINGTHING** [cloud-gov/cg-site#2501]
One of our Government clients would like us to host a website for them. They require us to have expertise with a FedRamp-authorized cloud (and physical) hosting environment and with federal web standards and requirements. My question is, can we as a private company host a Govt website on cloud.gov? If yes, where can I get information about the process and pricing.

**Comment by bengerman13** [comment]
Thanks for reaching out! can you email us at inquiries@cloud.gov - the folks there are better equipped to answer these kinds of questions.
