### ISSUE TITLE
Elaborate on user-provided services

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/cg-site#251]
We briefly encourage users to use user-provided services over envvars, but we don't provide much information, and the text appears in the production-ready checklist. I think it would be useful to say more about why user-provided services are preferred, and link to the cf docs, and helper libraries like https://github.com/cloudfoundry/cf-app-utils-ruby and https://github.com/jmcarp/py-cfenv (because parsing `VCAP_SERVICES` manually is annoying). I would also like to encourage users to think about managing secrets early in development, so it might be good to document this outside the production ready section.

Thoughts @afeld? I've been bugging people about using user-provided services, so I'm down to flesh out the docs here if it would be useful.

**Comment by brittag** [comment]
Reopening as a Skyporter issue, since it seems like Skyporter should check on whether this might still be a user need. I see there's some info at https://cloud.gov/docs/apps/production-ready/#protect-access-to-sensitive-credentials now, but I'm not sure whether it fully addresses this question.
