### ISSUE TITLE
Check and fix broken links

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#253]
We check internal links as part of the Wercker build, but I just cam across two broken external ones in a row. We should run [HTML Proofer](https://github.com/gjtorikian/html-proofer) locally and fix them.

**Comment by suprenant** [comment]
@afeld we're doing some board cleanup. Is this still relevant?

**Comment by brittag** [comment]
Switched this to a SkyPorter label since this is about user-facing content. It would still be good to come up with a way to consistently check for broken external links in our content.

**Comment by brittag** [comment]
I ran a link checker on the site and found only one legitimately broken link, "[security reasons](http://www.twobotechnologies.com/blog/2014/02/importance-of-state-in-oauth2.html)" on https://cloud.gov/docs/apps/leveraging-authentication/

I'll fix that, but I think we're doing ok without the automated version.

**Comment by brittag** [comment]
Eh, reopening - this was an important catch actually!

**Comment by suprenant** [comment]
We had a recent update to the Github issue that didn't come through here.

**Comment by mogul** [comment]
Now handled as part of the deployment pipeline
