### ISSUE TITLE
Page is not rendering correctly

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/cg-site#2559]
This page is not rendering with the cloud.gov layout and theme: https://cloud.gov/2017/08/11/continuous-improvement-more-tools-help-use-cloud-gov/

This page does appear in the search results for the site: https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=cloud.gov&query=crime+data

## Acceptance criteria

- [ ] Page renders properly within the site

**Comment by sknep** [comment]
@jamesthebrooks for visibility at least, and to acknowledge this needs triaging

**Comment by semicoloncharmedlife** [comment]
This is resolved on /cloud-gov/site currently.  Thanks for looping me in!

**Comment by semicoloncharmedlife** [comment]
This is a duplicate of https://github.com/cloud-gov/cg-site/issues/2553

**Comment by sknep** [comment]
@jamesthebrooks thanks! what did you do to fix this one on the fork? is it an easy thing someone could do here too?

**Comment by semicoloncharmedlife** [comment]
IRC there was no layout assigned in front matter.
