### ISSUE TITLE
RSA-A: Document security boundary between platform and tenants

### ISSUE THREAD

**Issue by dlapiduz** [cloud-gov/cg-site#257]
In order to meet `NIST 800-53 SA-??` and avoid confusion about the boundary of responsibility between cloud.gov and tenant teams, we want docs illustrating which aspects of an apps are the tenant's responsibility, especially when they are using supported vs non-supported buildpacks, and Docker containers.

**Acceptance Criteria**
- [x] There's a page describing the security responsibilities of tenants with a diagram under an appropriate section of docs.cloud.gov. 
  ![trello-1113710656](https://cloud.githubusercontent.com/assets/4604/15259155/4117394e-1915-11e6-8f2b-0877baf4fcff.jpg)
- [x] The diagram shows a clear highlight around areas that are the tenant responsibility for (1) supported buildpacks (2) unsupported buildpacks (3) Docker containers (as a forward-compatible measure)
- [x] Anything else called out by `SA-*` is covered.

**Comment by mogul** [comment]
See also [this example](https://twitter.com/nigewillson/status/726368948594298880) which would give more detail.

**Comment by mogul** [comment]
Pulled this out of the icebox, as it got called out during our interview on the SA section.

**Comment by brittag** [comment]
I'd be up for working on this with somebody; here are bits I poked around at while getting some context on this:
- [Prototype diagram](https://docs.google.com/drawings/d/1UBiOteSPXpA72KE52Kh-j7aYr73zTkzJ_oMuw5F293I/edit)
- Pages - ["Your Security Responsibilities" seems like a fine title, why not](https://github.com/brittag/cg-docs/blob/security-lines/content/apps/security-responsibilities.md) + [linking to it from the intro section about security, to make it more visible](https://github.com/brittag/cg-docs/blob/security-lines/content/intro/security/improving-application-security.md).

**Comment by dlapiduz** [comment]
We can add something here: https://github.com/18F/cg-docs/blob/master/content/intro/overview/what-is-cloudgov.md

Maybe start with something simple like "What is your responsibility"

**Comment by brittag** [comment]
Note to help link together related work: https://github.com/18F/cg-docs/pull/300 is a PR working on this.

**Comment by brittag** [comment]
There is now a basic chart + description of responsibility boundaries in the docs intro section at https://docs.cloud.gov/intro/technology/responsibilities/

This doesn't include the full list of details in "Implementation Sketch", but specific technical implementation/usage advice for cloud.gov users should probably go under "Usage" rather than in the intro docs. If somebody works out a draft of the technical aspects of this advice, I can help edit it and fit it into the docs.

**Comment by mogul** [comment]
Looks good! I broke the "guidance for good app security on cloud.gov" into a [separate issue](https://github.com/18F/cg-docs/issues/319).
