### ISSUE TITLE
As a user of cloud.gov, I want to know about how to set up redirects

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#271]
Users of cloud.gov need to know the options for setting up redirects, e.g. handing switching from an old domain to a new one. There are a few options we should talk about:
- Setting up a little [staticfile](http://docs.cloudfoundry.org/buildpacks/staticfile/index.html) app with an nginx config that handles redirection
- For servers, having multiple routes mapped to the same Cloud Foundry application and doing the redirection in code. [Options for Rails](https://coderwall.com/p/l1uydg/redirect-to-canonical-host-in-rails-4).

**Comment by brittag** [comment]
I believe this would still be useful for the documentation; reopening without the Navigator label.

**Comment by afeld** [comment]
Closed by https://github.com/18F/cg-site/pull/214.
