### ISSUE TITLE
document how to do manual debugging of cloud.gov

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#278]
@sharms mentioned that, in order to debug machines/BOSH/etc. in production, he uses `fly intercept`. Let's write down the (currently) recommended way of doing this.

**Comment by afeld** [comment]
There's a brand-new process for this: https://18f.slack.com/archives/cloud-gov-atlas/p1466608230000801

**Comment by rogeruiz** [comment]
Only big concerns for me here are:
- Where should the docs live? a specific repo? `18F/cg-deploy-concourse`, `docs.cloud.gov`, somewhere else?
- Aside from getting into the box, do we want to include any further examples around commands to run from within the box.

### _Proposed_ Acceptance Criteria
- [x] Document the process of hijacking Concourse containers in `docs.cloud.gov`
- [x] Provide examples of what is possible or what can be run from within the hijacked Concourse containers ( i.e. access, files, commands, etc )

**Comment by afeld** [comment]
> Where should the docs live?

How about docs.cloud.gov under `Contributing`?

> Aside from getting into the box, do we want to include any further examples around commands to run from within the box.

For starters, we can just say "you can run BOSH commands from here" and point to the BOSH CLI docs. Not sure if AWS credentials are also set up in the jump boxes...?

> Proposed Acceptance Criteria

Framing it as a user story:
- [x] As a cloud.gov team member, I have all the information I need to run BOSH commands on tooling/staging/production written down

**Comment by mogul** [comment]
Noah asked that we include a high-level diagram to summarize what's happening here. 

> I would not over optimize or work the diagram at this point. Just take a pic of a piece of paper/cocktail napkin/whiteboard.

**Comment by afeld** [comment]
BOSH instructions added in #291. The pipeline doesn't seem to set AWS credentials in the jump box...should it? Should we make a separate story for it? Or are we taking a different approach there?

**Comment by afeld** [comment]
Discussion here: https://18f.slack.com/archives/cloud-gov-atlas/p1467140313001221
