### ISSUE TITLE
Investigate node-sass transitive dependency

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#279]
@msecret mentioned in https://github.com/18F/cg-docs/pull/273 that `node-sass` shouldn't be required for cg-docs to be built, but it seems to be a dependency through `uswds`. The install for it (because of `node-gyp`) is a bit of a pain, so let's look into how to remove it for users of these packages.

**Comment by msecret** [comment]
I figured it out:

cg-style depends on uswds which depends on bourbon-neat which depends on node-sass. Technically, I can't find a reason why bourbon-neat would require node-sass as a normal dependency rather then a dev on. I can try and talk to them though.

**Comment by suprenant** [comment]
This is dependent on this WDS upgrade: https://github.com/18F/web-design-standards/issues/1555

**Comment by jmcarp** [comment]
@suprenant do you know where this stands?
