### ISSUE TITLE
RCP-A: Develop and publish Contingency Plan

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#284]
In order to satisfy the CP family of NIST controls, the cloud.gov team needs to have a written Contingency Plan.
- [ ] docs.cloud.gov contains a page with the contingency plan

Things to cover:
- [x] Start from cg-provision, 
- [ ] Add contact info (appendix A)
- [x] Add recovery time objectives
- [x] Who approves changes to the plan
- [x] Who gets notified
- [ ] Testing schedule + metrics
- [x] S3 backup practices
- [x] Testing/restore of RDS backups
- [x] Alternate processing (inherit from AWS mostly, refer to availability zones)
- [ ] Telecommunications practices Appendix C-2 and C-3 (inherit a lot from AWS)

**Comment by brittag** [comment]
I put together [a draft document in our GSA Google Drive](https://docs.google.com/document/d/1XHSd1hYjpdbu2wC1pzUSgjw6qtSU_sKUGQ8SsZVNcuQ/edit) with two parts: reference info listing some useful requirements/notes for this contingency plan, and an early draft of a plan. This plan needs more work from other people who have a deeper perspective on our systems and practices.

**Comment by mogul** [comment]
Points we had in our notes; please double-check that these are covered.

> Start from cg-provision, 
> Add contact info (appendix A)
> Add recovery time objectives
> Who approves changes to the plan
> Who gets notified
> Testing schedule + metrics
> S3 backup practices
> Testing/restore of RDS backups
> Alternate processing (inherit from AWS mostly, refer to availability zones)
> Telecommunications practices Appendix C-2 and C-3 (inherit a lot from AWS)

**Comment by mogul** [comment]
@jacobian says that:
- The AWS contingency plan is published, and that we should refer to it whenever possible, stating that their uptime requirements/target are higher than ours. This means we can probably skip a lot of other stuff about backups for S3, etc. that benefit from that availability.
- A fallback plan in case AWS is nuked is that we could (with time) bring everything up in Azure using the CPI.

**Comment by brittag** [comment]
For reference, relevant PR: https://github.com/18F/cg-docs/pull/297

**Comment by brittag** [comment]
Noting for reference: there is an official Contingency Plan Template available at https://www.fedramp.gov/resources/templates-3/

**Comment by afeld** [comment]
@dlapiduz Mind posting an update?

**Comment by dlapiduz** [comment]
As @brittag said we have a template but not only that, there is also a completed version of that template for cloud.gov. I just finished filling in a bunch of stuff missing from that one and will send it to you all. (yay word docs)

**Comment by dlapiduz** [comment]
Personally I think we should keep the PR and use it as a guide since the official contingency plan has 40 pages and lacks a... plan.

**Comment by rogeruiz** [comment]
@dlapiduz can we add a CP doc link to the PR or this issue so we don't lose it. 👍

**Comment by brittag** [comment]
Here's the [Contingency Planning doc in Google Drive](https://drive.google.com/a/gsa.gov/file/d/0B1tXdxX5wEL0S3Q5RVNoOW9rMTg/view).

And yeah, let's also plan to convert that PR into a human-readable short guide for ourselves on docs.cloud.gov (compatible with the official plan), to describe how we'd deal with a few realistic important scenarios of things that could go wrong (such as what we'd do if Slack/GitHub/AWS went down for a non-trivial amount of time).

**Comment by afeld** [comment]
https://github.com/18F/cg-docs/pull/297 is in...good to close?

**Comment by dlapiduz** [comment]
@afeld lets shut this down!
