### ISSUE TITLE
RAC-C: Shorten _deployer password expiry and document how to avoid constant refresh

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#286]
In order to comply with federal compliance rules and avoid inconveniencing users, we want to limit the valid lifetime for passwords on local accounts and show teams how to minimize the impact of that change on their CD processes.

**Acceptance Criteria**
- [ ] _deployer account password lifetime is limited to 30 days or less
- [ ] Tenant teams receive advance notice of the change
- [ ] The advance notice includes a pointer to a page on docs.cloud.gov giving guidance on how to avoid credential rotation having a big impact on CD

**Implementation sketch** 
- Set the password expiry policy (easy, but wait until there's communication about it first)
- **Figure out if there can be longer-lived tokens attached to an account whose password has expired, and if so document how to set that up**
- Make edits to any admin-facing docs about how to set up deployer accounts and convey the tokens

**Comment by afeld** [comment]
Expiry already shortened: https://github.com/18F/cg-deploy-cf/pull/77.

**Comment by afeld** [comment]
Possibly a dupe of https://github.com/18F/cg-product/issues/15?

**Comment by mogul** [comment]
> Expiry already shortened: https://github.com/18F/cg-deploy-cf/pull/77.

Pretty sure we rolled that back out until we could communicate with users about it.

**Comment by mogul** [comment]
> Possibly a dupe of https://github.com/18F/cg-product/issues/15?

No, that one is about our internal credentials, eg the firehose-to-logstash.

**Comment by mogul** [comment]
Can we clarify if this comes from Veris or explicitly from FedRAMP requirements? In other words, can we pick a different cadence for rotation, or limit it to only certain kinds of accounts?

**Comment by mogul** [comment]
@s-matyukevich : Here’s how we’ve handled credentials for CD to date: https://docs.cloud.gov/apps/continuous-deployment/

**Comment by s-matyukevich** [comment]
Seems like I was able to make a long-lived tokens attached to an account whose password has expired. It is documented here https://docs.google.com/document/d/1r3hxsqbqtx6a7fUcNsmQBwWP49FnDBf1R5u7XIIVQXw/edit

**Comment by s-matyukevich** [comment]
I also investigate possibility to use different uaa zones in order to provide different types of tokens for different users. Based on my current understanding of uaa source code the desired behavior can't be achieved using different zones.

**Comment by rogeruiz** [comment]
@s-matyukevich Trying to investigate writing a `cf-plugin` for the `cf-cli`.
@LinuxBozo We need this to work in a CD environment like Travis, Circle, Werker, etc.

**Comment by mogul** [comment]
@rogeruiz: You mentioned you have experience using `cf` CLI plugins with CD... Do CD systems actually call the CLI?! I'm glad if that's the case, just surprised.

**Comment by mogul** [comment]
Given that tenants aren't yet in GovCloud, is there a big impact on _us_ (eg our Concourse deploys) if the password expiry for `_deployer` accounts is set to 30 days _now_? That would let us meet the FedRAMP remediation point while buying us time to add "long-lived deployment tokens" back as a feature on the GovCloud environment in future.

**Comment by rogeruiz** [comment]
@mogul yup, we were experiencing some downtime because of constant merging and deployments _and_ we  use _many_ manifests for `18F/web-design-standards` so I added `cf-autopilot`. 

**relevant bits** => https://github.com/18F/web-design-standards/commit/afae877d9c95700732460001a33867b6c132b9c7

**Comment by afeld** [comment]
> Do CD systems actually call the CLI?!

Yep!
- [Travis](https://github.com/travis-ci/dpl/blob/e03a1fcca1de4cd3449220077abf18fffdcb68fe/lib/dpl/provider/cloud_foundry.rb#L26)
- [Wercker](https://github.com/joshuamckenty/step-cloud-foundry-deploy/blob/abf1be537bda25b5c2382be9e37caa6cd202039d/run.sh#L6)

**Comment by s-matyukevich** [comment]
I've created a pull request to CF cli, that allows us to configure what OAuth client is used https://github.com/cloudfoundry/cli/pull/881  
Also I wrote a CLI plugin, that allows to login into cf cli using tokens, but not username and password https://github.com/s-matyukevich/set-token
Having this two parts we will be able to setup separate OAuth client,  configure it to issue a long lived tokens. And modify out CI/CD pipelines to use that tokens.

What is still missing is separate plugins for each CI/CD tool, that we are going to use.

**Comment by s-matyukevich** [comment]
Another thing that I am working right now is a pull request to UAA that will allow to setup password expiration time per user, So we will be able to create special accounts with password that never expires or expired after a long time. If this will be accepted, we will no longer need any cf cli plugins, or modifications to cli itself. We also don't need any plugins for CI/CD tools  in this case.

**Comment by mogul** [comment]
Transcript of a conversation with Pivotal yesterday  in Slack:

> [10:07 AM]  
> Steven Harms (CVG) @jmckenty: Hey Josh, do you happen to know how we can create Continuous Integration accounts which don't expire at the same time our passwords do?
> For example, Heroku, OpenShift, AppEngine, Github etc use keys which do not expire for non-human accounts, but in CF / UAA our deployers do not have the same ability
> 
> [11:47 AM]  
> Joshua McKenty Are you federating UAA with SAML?
> Let me ask Sree to join
> she’s the PM for UAA
> 
> [1:31 PM]  
> Steven Harms (CVG) Thanks - yes we are using UAA w/ SAML and have a password expiration of 90 days set up.  What would be ideal is to say 'I am sharms, I have a password, and I have a long lived API token'
> 
> [2:21 PM]  
> Joshua McKenty hey, sorry - where do I send Sree to get onto this team?
> 
> [2:22 PM]  
> Diego Lapiduz Our chat thingy is down due to govt can you  DM me her email?
> 
> [2:27 PM]  
> Joshua McKenty yeah
> 
> [2:34 PM]  
> Sree Tummidi joined #devops-public
> 
> [3:02 PM]  
> Sree Tummidi @sharms: When UAA is integrated with SAML,  UAA delegates the authentication to the SAML Identity provider. In this scenario UAA doesn't manage the user passwords and the password policy
> 
> [3:02 PM]  
> Steven Harms (CVG) @sreetummidi: How can I generate a token to give our CI pipelines which exists independently of that?
> 
> [3:03 PM]  
> Like in Github, if I change my password, all of my CI / integrations don't need to be updated because I have a token / key (edited)
> 
> [3:05 PM]  
> Sree Tummidi Long lived API tokens is not a supported flow with the CF CLI.  We plan on adding this support in the future.  The way to solve this for the time being would be to register an OAuth client via UAAC
> The grant type needs to be Client_Credentials
> You need to set the authority for the client to be cloud_controller.admin
> and the access token lifetime to a long duration
> The downside of this approach is that this Client is associated with admin permissions
> ^^ @sharms
> Also, there is one more approach. You could create an API user in UAA and associate that user with the corresponding CC Roles
> In UAA make sure that the password expiry is set to 0
> That means passwords don't expire
> In your automation script, you would need to feed the internal username and password
> 
> [9:13 AM]  
> Steven Harms (CVG) @sreetummidi: For these two solutions -
> 1. Using 'uaac client ...' as admin is too broad for multi-tenant
> 2. It appears that creating a deployer user is a non-starter since our UAA forces SSO which cannot be automated
> Any chance you could share a roadmap to getting deployer tokens associated with individual users?
> 
> [9:14 AM]  
> Diego Lapiduz @sharms: our UAA forces SSO only for certain domains… if you just pass in a username rather than an email you shouldn’t get a forced SSO
> 
> [9:15 AM]  
> Steven Harms (CVG) @diego: Every user requires an email address to be created, and using a non GSA one still forces SSO

**Comment by s-matyukevich** [comment]
@afeld  @sharms if you use SAML this pull request https://github.com/18F/cg-deploy-cf/pull/77/files probably don't make sense, because it configures password expiration for UAA db. 

Also I don't know that we use SAML, this fact actually changes a lot and my pull request to UAA don't make much sense, I will try to figure out how to do the same thing with SAML identity proovider.

**Comment by s-matyukevich** [comment]
I have written a plugin for Travis, that allows to deploy apps to CF using tokens to authenticate agains UAA. This plugin can be found here https://github.com/s-matyukevich/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb This plugin uses my another  plugin for CF cli, that allows to update tokens in config file using command line, and also it uses my fork of CF cli that adds possibility to set different oauth client. The whole workflow need some more testing, but in general it works.

Next step is to write such plugins for all other CI tools, that our clients are going to use and update documentation.

**Comment by rogeruiz** [comment]
@s-matyukevich Will talk after standup on simplifying the script

**Comment by s-matyukevich** [comment]
### Docs PR

https://github.com/18F/cg-docs/pull/320

**Comment by mogul** [comment]
We have a pull-request pending upstream... Meanwhile, @dlapiduz help us understand how much we have to continue focusing on this given that humans will only ever have MFA accounts in GovCloud...?

**Comment by dlapiduz** [comment]
Here is what I am thinking: If we only use local accounts for bots and testers, why do we have to have password rotation requirements? They are not _users_ just service accounts.

**Comment by dlapiduz** [comment]
@mogul ^^

**Comment by mogul** [comment]
Sergey demo'd yesterday that he now has a solution for generating tokens with a lifespan independent of the password expiration window... Basically, instead of using the username/password-based Travis, Circle, and Wercker CF targets, we provide a script that does the work to set up a long-lived refresh token. However, for this to work it relies on a change to the CF CLI to actually use its refresh token to get a new auth token whenever auth is rejected. That's pending upstream and we don't want to confuse users by requiring a special CF CLI binary, so the docs on doing this will stay in a pending PR until a new CF CLI drops with the functionality we need.

**Comment by rogeruiz** [comment]
I'm taking a look at the docs PR and will run through the code bits.

**Comment by s-matyukevich** [comment]
I have an update from CF CLI team. They said that they are going to implement long lived token functionality on UAA side first, and then add it to CLI. This functionality will be available in mid September. For now, they don't want to merge my PR. 

@mogul should we close this now?

**Comment by mogul** [comment]
Closing in favor of the upstream solution-to-be... Thanks for pushing to get them to this point, @s-matyukevich.
