### ISSUE TITLE
Add to Security IR Guide/Checklist to guide when/how to communicate outside the team about incidents

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#287]
For some kinds of security incidents, part of our response should be explaining to affected people and/or the public what happened and how we handled it, so I'd suggest putting some guidance in https://docs.cloud.gov/ops/security-ir/ to help us be consistent about when/how to inform people. I'm not sure what this should be; it might be as simple as a step for high-sev incidents saying "contact the 18F comms team to work on a comms plan". @jacobian

**Comment by jacobian** [comment]
Agreed; this a big can of worms, however. I'll crack it open next week and see what crawls out :)
