### ISSUE TITLE
Add a signed cert at https://docs.cf.18f.us/

### ISSUE THREAD

**Issue by drnic** [cloud-gov/cg-site#31]
The self-signed cert isn't super lovely :)

**Comment by afeld** [comment]
Heh, was wondering if any Cloud Foundry folks had come across this repo yet :smile: We're working on setting up a new domain for our CF deployment, so are waiting to buy a wildcard cert until then. Soon!

Other feedback welcome, too. Hope we can contribute a lot of this back to the canonical documentation sooner or later.

**Comment by dlapiduz** [comment]
We finally have a proper domain and cert. The new docs site lives at https://docs.18f.gov
