### ISSUE TITLE
Provide guidance for securing application code

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#319]
[We now have a card talking about the division of responsibilities... This card is about helping tenants understand how to meet theirs. Compliance is out of scope; we'll address that in materials specifically about how to get an ATO for an app hosted in cloud.gov.]

**Implementation Sketch**
- Cover .cfignore/.gitignore
- Advise to use envvars and user-provided services
- Make it clear we don't cover the app code, or any pinned app dependencies
- Other advice to help people not include secrets in their pushes
- Advise timed redeploys or restages to pick up fixes in buildpack or floating dependencies?
- Talk about deployer account security

**Comment by suprenant** [comment]
@mogul FYI pulling Navigator from here as well

**Comment by mogul** [comment]
This one's kind of addressing "production readiness", but from the compliance angle.
