### ISSUE TITLE
Improve leveraging-authentication.md

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-site#321]
I used the code sample at the bottom of [Leveraging Authentication](https://docs.cloud.gov/apps/leveraging-authentication/) to make a trivial OAuth client recently and noticed a few issues with it:
- The snippet assumes that `request` refers to node's [`request`](https://github.com/request/request) module but never mentions it.
- The snippet assumes that `app` is an [`express`](https://expressjs.com/) instance, but never mentions it.

Aside from that, the snippet isn't actually self-contained in any way, as it uses other constants that aren't defined anywhere, and doesn't provide a login link; most documentation that offers snippets also provides a "full code listing" that readers can copy-paste into an actual editor and get running with minimal effort. This also makes it difficult to double-check whether the snippet (or any changes we make down the road) is actually correct.

Rather than fix the snippet, though, I recommend just linking out to a fully self-contained UAA client.  I've taken the one defined in the snippet and added minimal extra code (~80 total LOC) and a `package.json` to install external dependencies here:

https://github.com/18F/cg-fake-uaa/tree/master/example-client

So we could potentially just link to that instead of providing the snippet.

Besides that, I'd also like to link to [cg-fake-uaa](https://github.com/18F/cg-fake-uaa) as a resource that might help folks integrate with cloud.gov authentication.

Oh, and I'd also like to link to [The Importance of the state parameter in OAuth2](http://www.twobotechnologies.com/blog/2014/02/importance-of-state-in-oauth2.html) when discussing the `state` parameter, to provide some context around it and nudge people to use it (depending on what our compliance folks think, we might even want to just mandate its use, but I'm not sure).

Thoughts @brittag @jseppi ?

**Comment by jseppi** [comment]
Yes, I agree a link to a fully functional reference client would be an improvement over the snippet.

**Comment by toolness** [comment]
Ok!

I started work on this a little while ago but got sidetracked by the fact that list nesting appeared to be wonky. After some investigation I figured it out and filed https://github.com/18F/web-design-standards/issues/1328 with a [fix](https://github.com/18F/web-design-standards/pull/1329).

Phew. I'll tackle the guide once that's been merged and makes its way downstream to this repo!
