### ISSUE TITLE
Django needs to vendor the requirements

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-site#322]
I'm working with PCF, so maybe cloud.gov is different, but don't you need something like this:

```
mkdir vendor
pip download --dest vendor -r requirements.txt
```

before doing a `cf push` ?

**Comment by afeld** [comment]
Ah, didn't realize this was the case!

http://docs.cloudfoundry.org/buildpacks/python/index.html#vendoring

Opened https://github.com/18F/cg-docs/pull/323 to point people to the official docs.
