### ISSUE TITLE
Explain what you can do with apps in a sandbox

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#325]
In order to feel confident about trying out apps in the sandbox as a new cloud.gov user, I'd like to know what I'm allowed to do in the sandbox org (stated briefly as part of my new user onboarding process). For example, I'd want to know if there's only a pre-approved list of applications I'm allowed to run in the sandbox (the "hello world" apps), or if I'm allowed to make significant modifications to them and run other ones. In other words, I want to know what I can do without an ATO in the sandbox.

Adding a little bit about this to the docs will likely require talking to:
- [ ] Somebody at 18F to get a sense of what you're allowed to do as a GSA employee.
- [ ] Somebody at EPA to get a sense of what you're allowed to do as an EPA employee.

Then:
- [ ] Put that info in the docs in some reasonable helpful place!

**Comment by toolness** [comment]
I'm curious if it's also worth mentioning the existence of (and link to) AWS Sandbox accounts for 18F employees who might want to do something innovative that isn't yet possible on cloud.gov?

**Comment by brittag** [comment]
Notes from Slack about this: [1](https://18f.slack.com/archives/cloud-gov-support/p1469646111000548), [2](https://18f.slack.com/archives/cloud-gov-support/p1469647067000550)

**Comment by brittag** [comment]
Also link to [Pre-authorization](https://pages.18f.gov/before-you-ship/ato/types/#pre-authorization) - which explains "You may operate without authorization if all of the following conditions are met".

**Comment by brittag** [comment]
I now believe there are two components of this explanation:

1) What cloud.gov allows cloud.gov users to do in the sandbox org (which is limited by things like "not production, doesn’t need more than 1 GB of RAM, doesn’t need any paid services, doesn't need ATO")
2) What an agency or team allows their staff to build/make/prototype/test in the sandbox org under those constraints (for example, at 18F we're limited in building things without ATO guided by that "pre-authorization" list; other teams and agencies have different guidance)

**Comment by brittag** [comment]
Example user question related to pre-authorization: what about trying one of the default "hello world" apps? Does that need to be hidden behind auth, as the pre-authorization list indicates?

**Comment by berndverst** [comment]
Probably related to this:
There are also some questions around what agencies may do in the Prototyping tier.

**Comment by brittag** [comment]
Example user question related to sandbox spaces: are you allowed to give access to your space to other people in your team, such as giving a coworker space developer access?

**Comment by afeld** [comment]
> are you allowed to give access to your space to other people in your team

I thought I remembered seeing something about that when I was working on the pricing docs, but couldn't find anything with a quick glance.

**Comment by brittag** [comment]
[From Slack](https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1476466135004115), for future docs: "There’s no restriction on collaborating in a sandbox. The restriction is that you can’t have an OrgManager who can see/manage access and quotas for all the spaces."

**Comment by brittag** [comment]
This is handled on https://cloud.gov/overview/pricing/free-limited-sandbox/
