### ISSUE TITLE
Document the basics of how compliance works for products on cloud.gov

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#327]
In order to get ATOs for products running on cloud.gov, cloud.gov users need clear explanations of which security controls are covered by cloud.gov and which ones they need to document themselves.

Doing this in a complete and thorough way is a bigger task (tracked at https://github.com/18F/cg-product/issues/63), but for now, we just need a basic compliance section in our docs to help people who are already trying to do this: what controls you'd need to document if you're at 18F and trying to get an ATO for a FISMA Low system that's running on cloud.gov.

This will help people with the last two items on the [18F ATO Checklist](https://pages.18f.gov/before-you-ship/ato/checklist/), and it should align with them:

> [Set up Compliance Masonry documentation](https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications)
> [Implement the controls](https://pages.18f.gov/before-you-ship/ato/walkthrough/#step-3--implement-the-controls)

Also related: https://pages.18f.gov/before-you-ship/ato/ and https://pages.18f.gov/before-you-ship/ato/controls/

Additional reference info:
- [NIST Controls](https://web.nvd.nist.gov/view/800-53/Rev4/impact?impactName=low)
- Email about cloud.gov and GSA LATO controls
- [This spreadsheet](https://docs.google.com/spreadsheets/d/1EYLuavFgLUvfHDiBOuFjJsjpKQFDwXZx6J6gTffegUM/edit?ts=5733adb1#gid=0)
- [This Slack conversation](https://18f.slack.com/archives/compliance/p1468868306000010)

Acceptance criteria:
- [ ] There's a page on docs.cloud.gov that has basic guidance for filling out your compliance documentation in the simplest case (18F staff, FISMA low, product on top of cloud.gov).

**Comment by brittag** [comment]
Related questions that people have:
- Do static apps on cloud.gov require an ATO? Such as apps deployed with the static buildpack?
- Do ATOs require an IAA?

**Comment by brittag** [comment]
Noting for reference: when we’re ready to work on this, we should check in with @jezhumble for context as well.

**Comment by mogul** [comment]
Going to revisit this once the SSP and CIS/CRM are solid.

**Comment by brittag** [comment]
Noting for the future: @toolness is interested in helping with this when we get to this point. He can contribute his perspective as a cloud.gov user who has been wrangling with the ATO process.

Also a potentially-useful resource when this happens: https://github.com/18F/before-you-ship/issues/189

**Comment by brittag** [comment]
We're handling this in other stories.
