### ISSUE TITLE
Provide guidance on running asynchronous worker processes

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#329]
In order to build complex products on cloud.gov, users need resources explaining best practices for setting up products that involve asynchronous worker processes.

Reference: [notes from @afeld's training today](https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit#heading=h.jzgrz2av0xjp).

This would likely include:
- A basic explanation of how to do this within the Cloud Foundry model (set up separate apps, etc.)
- A couple of helpful "role model" examples of 18F products that have set this up, with small explanations of their technical setups and the tradeoffs they chose.

**Comment by mogul** [comment]
Long since done: https://cloud.gov/docs/getting-started/one-off-tasks/
