### ISSUE TITLE
Give more guidance about cf-ssh

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#330]
In order for users to do non-trivial tasks with cloud.gov with minimal frustration, the instructions for cf-ssh (as a useful and commonly used tool) should have more context and advice so that readers can understand its benefits and limitations better.

To do this, we should put the [cf-ssh advice from @afeld's training](https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit#bookmark=id.xmckkupev4uf) into the [running one-off tasks page](https://docs.cloud.gov/getting-started/one-off-tasks/).

We might also consider rearranging that page if people usually find cf-ssh to serve their needs better than the "short-lived app" method.

**Comment by ghost** [comment]
Closing in favor of 18F/cg-product#154

**Comment by brittag** [comment]
@sushiandbeer Oh hmm, it looks like https://github.com/18F/cg-product/issues/154 got closed too - is there a new issue for this kind of thing?
