### ISSUE TITLE
Move business case explanation out of the documentation

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#332]
Our "documentation" should be primarily technical documentation, since that's what users usually expect when they click "documentation".

Our detailed business case explanation (currently "Introduction" in the sidebar) should live and grow outside of the technical documentation.

cc @berndverst 

The next step for working on this would be to sketch out a couple ideas for alternatives.

**Comment by berndverst** [comment]
I will work on a mock-up (or example structure) of this.

**Comment by brittag** [comment]
While sketching potential versions of this, let's also consider how to fit in a search box for both these kinds of content (business docs + technical docs).

**Comment by berndverst** [comment]
I'm doing actually sketching...
Can we separate out the search bar part? That is already captured in another issue anyway.

**Comment by brittag** [comment]
It's up to you how you'd like to sketch this; I'd suggest considering how to fit in a search bar if you think one should be part of the overall UI.

Noting the related issue for the record: https://github.com/18F/cg-product/issues/194

**Comment by mogul** [comment]
We heard today that @jameshupp will be rejoining cloud.gov as a content designer 10/1, so he can likely help out with this!

**Comment by berndverst** [comment]
In order to better serve the distinct needs of business/executive users and technical users I am proposing the following change:
- Product overview, motivation, high level security discussion etc will move into a separate section with separate nav.
- The technical docs used for getting started, or advanced topics etc. will live in the existing place.

I see this separation as critical before we proceed with active outreach efforts to potential customers / leads.

I would like to proceed with this separation soon. At this time I am not concerned with styling changes, or in fact changing any of the content. That may (and should) occur through future issues or work. The separation for the distinct audiences sets us up for more effective work on those items in the future.

Please see my screenshots:

Technical docs:
![techdocs](https://cloud.githubusercontent.com/assets/4535280/18928361/8c076eda-8574-11e6-9585-d775e1a04c80.png)

Product Overview:
![productoverview](https://cloud.githubusercontent.com/assets/4535280/18928373/96f13b3c-8574-11e6-96eb-f19cd9f6b409.png)

While this is a functional change of the website, it is a small task. I already did a lot of the work in less than one hour when I produced these screenshots.

Please provide me with any feedback or objections. I would really love to make this happen.

**Comment by berndverst** [comment]
Note that in the above screenshots I changed some text on the index pages. That was only for the sake of the screenshots.

**Comment by mogul** [comment]
(Search work is proceeding separately, btw.)

**Comment by mogul** [comment]
My intuition is that when I see a link labeled "About" I'm going to find
information about the company that made the product, funders/investors,
principal leads, etc. And I usually don't click it. :) I'd go with
"Overview" matching what you have in the sidebar to invite more eyes in
that direction.

**Comment by jameshupp** [comment]
Thinking through some nav labels...
- _Overview:_ Reverses existing terminology hierarchy to put Overview over Intro; this feels broadly accurate)
- _Introduction:_ Keeps existing terminology hierarchy, also keeps Overview as a second-level intro, which is how it's used on standards.usa.gov. At least within 18F I suspect there's some overlap between cloud.gov products and Standards products.
- _About cloud.gov:_ Not wild about this, but just wanted to suggest that inserting a second word changes the feel of the word "About" from being the organizational catch-all to defining the product more clearly. Even so, I'd rather avoid the design oddness of adding a second word to only one top nav item.

I'm not that hung up on any of this, though; the difference between the first two is a pretty quick and easy usability question we can handle with users after splitting.

**Comment by jameshupp** [comment]
Two things I want to flag.

First: what do we know about the use of About in the top nav right now? Do people click it and drop to the anchor link down the page? Do they never click it? Have users told us they don't expect it or hate it? Or was it our solution to people not seeing what else was on the page? Just want to get a sense of what's up there as we're changing at least what the term links to and probably the term itself.

Second: we ought to break the Terminology section apart. The cloud.gov terminology ought to just be "Terminology" but within the documentation. The pricing terminology ought to be "Terminology" under the Pricing heading.

Possible locations for the docs terminology:
- Top-level Documentation, between Contributing and Help (treat it as an appendix to the rest of the documentation for people who need it)
- Second level under Usage, first item listed, before Getting Started (suggest it as basic knowledge one may need before one starts using the platform).

**Comment by berndverst** [comment]
@jameshupp @mogul 

"About" can obviously be renamed to anything better like "Product" or "Overview". That would actually be my preference.

Also, please note that I didn't change the hierarchy here. I just moved one section into its own area. We can address the menu organization further, but can we do so in another issue and incrementally?
We can make things better in smaller chunks!

**Comment by berndverst** [comment]
@mogul I find "About" to be extremely unintuitive for a product page (as opposed to a company). I honestly don't know what I would expect there, but information on the team who made it would be my last thought.

I'm personally in favor of naming this "Product" or "Overview".

The landing page is still accessible via the cloud.gov logo itself, and we could certainly link there from various places.

At the same time, I think we should link from the landing page sections into the more detailed articles of our "Product Overview" section which I would like to introduce here.

**Comment by berndverst** [comment]
Let's keep this issue about literally nothing but moving the business / overview section into its own thing.

No other changes. There is of course much we should change, but this is how we can start and make things incrementally better with little risk.

**Comment by brittag** [comment]
I believe that if we made the following set of changes, this would be a helpful smallest-possible incremental improvement:
1. Move the "introduction" materials under "about", as shown in these screenshots
2. Rename the "about" nav item to "overview" or "introduction"
3. Add redirects to any URLs that would have been broken by this change (if any)

This change would add more importance to fixing the problem explained at https://github.com/18F/cg-dashboard/issues/447 - that there's no highlight in the top nav when you're viewing a section of the website - but we could address that separately.

**Comment by brittag** [comment]
(In other words, I agree with many above comments. :) I just wanted to summarize what I agreed with.)

**Comment by berndverst** [comment]
@jameshupp please take a pass when you got a chance / or add any further feedback. I can make this happen from a technical perspective.

The unfortunate part is that the marketing page and the docs are in different repos and use different servers (Jekyll vs Hugo)

**Comment by mogul** [comment]
Hugo's a super-set of Jekyll, AFAIK... You might investigate what it would
take to convert `cg-landing` to Hugo if you think the difference is going
to get in the way of migrating this content now, or other content going
forward. That's also an incremental step toward putting them in the same
repository.

(I also think it's perfectly possible to leave the content where it is in
`cg-docs`, but under a separate hierarchy, and just have the additional
global nav point to the new hierarchy's entry point.)

**Comment by berndverst** [comment]
@mogul thanks for the context.

@jameshupp let me know how you want to tackle this. Happy to work on this together!

**Comment by berndverst** [comment]
@jameshupp since I haven't heard anything I will proceed to make the change on a new branch and then review it together with you.

**Comment by brittag** [comment]
I believe this is complete now. :)
