### ISSUE TITLE
Separate cloud.gov user documentation from contribution documentation

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#333]
We have two kinds of technical documentation in our docs right now:
- "Usage" for users (application team and agency admin staff, such as developers, org admins, product managers)
- "Contributing" for contributors and potential contributors to cloud.gov (18F staff, external volunteers, users curious about contributing fixes)

Users are our primary audience for the "Documentation" link in the cloud.gov header, and it'd be good to help them find what they need as quickly as possible - so let's make this "Documentation" link (docs.cloud.gov) be dedicated to user documentation. This will also allow our user documentation to have more space to grow, with more sub-menus, while still being fast to access.

The contribution documentation should be clearly linked from the user documentation, since users may be interested in contributing.

**Comment by afeld** [comment]
The current "Contribution" section is really more about "Operation", rather than "here's how to contribute to our repositories/community".

**Comment by brittag** [comment]
Yes! I imagine part of this task would be to write a little preface for the Operations docs explaining that, and also write a little intro to how to contribute as a volunteer (or as an employee of a different org/agency/company).

**Comment by mogul** [comment]
cc @jameshupp since he'll likely want to look at this when he rejoins!

**Comment by berndverst** [comment]
I would like the operational information to not live on docs.cloud.gov and definitely not in the same navigation hierarchy as our technical content.

I don't feel that having these documents on docs.cloud.gov is beneficial to our customers. Whether any customer has benefited from these documents so far, I do not know. That being said, I believe that we would be best advised not to use the cloud.gov / docs.cloud.gov websites to track our own procedures, but instead moving this to Github or some sort of separate Wiki.

I'm also on the fence as to whether this information should be open at all. But if we choose to keep it public, why not just have it in Github via Github flavored markdown? We can still link to whichever Github repo we use from the cloud.gov marketing page.

/cc @mogul

**Comment by dlapiduz** [comment]
We can do something like docs.cloud.gov/ops and have all the docs there. I don't think we should hide that info though.

**Comment by mogul** [comment]
Right. The intent is that this information is open for people who want to
follow in our footsteps, and understand how our operations are handled.
It's fine to keep out of search results, but operators need to search too,
so we should think about how to preserve that capability. ;)

**Comment by brittag** [comment]
As a reference for later, I wrote some more thoughts about where to put contributing docs [at the bottom of the site refactor proposal doc](https://docs.google.com/document/d/1os4Kfr1Lg1YPiU8tol6dS2g2ejzjyiKVqUfhZTFSYaU/edit#bookmark=id.l80bfdsz7rzq).

**Comment by brittag** [comment]
We resolved the main problem here by renaming this section from "Contributing" to the better description of "cloud.gov team docs".
