### ISSUE TITLE
Restructure docs UI for easier navigation

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#336]
Writing down a few things we've noticed for later prioritization:
- Move the title of the page to the top of the reading area, so that it's easier to identify what page you're reading:

![screen shot 2016-07-20 at 12 29 53 pm](https://cloud.githubusercontent.com/assets/391313/17000145/0a02897c-4e76-11e6-826b-cb1550319f6e.png)
- Make "parent" sidebar items link to pages with content, rather than just expanding a sidebar menu, so that people get to helpful content with each click (rather than having to click multiple times to get to helpful content). It can be a little frustrating to need to click multiple times (and make multiple decisions) before getting to read new content. (This would require some content restructuring.)
- Provide an overarching way to identify that you're currently viewing documentation. This is the same visual issue as https://github.com/18F/cg-deck/issues/447 ("There's no clear visual distinction between the dashboard pages and docs pages"). This could be as simple as highlighting "documentation" in the top navigation.

cc @berndverst

**Comment by msecret** [comment]
I'm interested to see how we could design for the 3rd point. It definitely seems like we have to highlight where in the cloud.gov experience you are in the top nav.

**Comment by mogul** [comment]
> - Move the title of the page to the top of the reading area, so that it's easier to identify what page you're reading:
> 
> ![screen shot 2016-07-20 at 12 29 53 pm](https://cloud.githubusercontent.com/assets/391313/17000145/0a02897c-4e76-11e6-826b-cb1550319f6e.png)

+💯 on this one... As it stands the title located outside the body is essentially breaking the information hierarchy implied by the yellow "selected" tab.
