### ISSUE TITLE
Explain what aspects of cloud.gov's compliance toolkit are part of the standard fee

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#339]
In order for prospective customers and customers to confidently use cloud.gov, they'd like to know how fees work outside of the core PaaS function of cloud.gov: whether the ATO-related services (compliance toolkit services) cost extra money.

Let's document this as part of generally documenting how ATOs work on cloud.gov. This may overlap or otherwise interact with https://pages.18f.gov/before-you-ship/ato/

Slack chat archives that may be relevant: [1](https://18f.slack.com/archives/cloud-gov/p1469134303000261), [2](https://18f.slack.com/archives/cloud-gov/p1469134967000262), [3](https://18f.slack.com/archives/infrastructure/p1469145877000181)

**Comment by nikzei** [comment]
See [cg-product #432](https://github.com/18F/cg-product/issues/342), which seeks to define which consulting services fall outside of guidance that we provide under a standard fee. Might make sense to work on these two issues together.

**Comment by nikzei** [comment]
Also related to 18F/cg-product#258

**Comment by brittag** [comment]
As this issue gets more groomed, it might need a Highbar label too, depending on the shape of the work - not sure.

**Comment by brittag** [comment]
We fixed this by removing confusing information about compliance toolkit.
