### ISSUE TITLE
Improve pricing documentation

### ISSUE THREAD

**Issue by berndverst** [cloud-gov/cg-site#358]
UPDATE by Skyporter:
In order enable prospective users to clearly articulate what they need + so that they can make purchasing plans, the pricing content needs to reflect the way people actually buy and use IT services (they pay for stuff and they get stuff in return - right now it's not clear right what you get and for what price) 

---

Sample questions that should be addressed as part of this story:

- Is the support and service a part of the payment, or will the agency be billed for services separately from the use of the cloud capabilities themselves?  -->  support for platform is included but support for your app is not provided. 

- I want to be sure I understand what a “system” is so we can be confident about what our costs would be. 

- What is our pricing break down? 

- How do we charge for additional resources / services / quotas that are required / requested?

- If I renew my contract for the same system (app), do I still need to pay for the value of the compliance savings?

**Comment by brittag** [comment]
This user need is likely related: https://github.com/18F/cg-docs/issues/339 ("Explain what aspects of cloud.gov's compliance toolkit are part of the standard fee").

**Comment by berndverst** [comment]
👍

**Comment by mogul** [comment]
> We currently have quotas.18f.gov which shows real quota usage by org. We need to determine whether this should stay public. If so, we should explain this data in our documentation and also note that it is public.

Whoa, when did that become public? @dlapiduz was that you?

**Comment by berndverst** [comment]
related to 18F/cg-product#258

**Comment by nikzei** [comment]
check in with Britta before picking this one up

**Comment by nikzei** [comment]
[@jameshupp - James Hupp] our cg-ste brainstorm today touched upon this quite a bit, I think. I've added one more AC to see if we can get customers to pricing information more quickly.

**Comment by brittag** [comment]
Related to this, I made a card about improving info for the prototyping package: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3469

**Comment by nikzei** [comment]
Related story on improving documentation around prototyping accounts: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3469

**Comment by nikzei** [comment]
From the inquiries listserv: a few questions that @brittag suggested could be helpful address briefly on the website so that customers can bring more nuanced questions to us:

- How long will this [IAA processing] take? (I think we discuss this in our IAA section but maybe it's not easy enough to find)

- Is the support and service a part of the payment, or will the agency be billed for services separately from the use of the cloud capabilities themselves? 

- I want to be sure I understand what a “system” is so we can be confident about what our costs would be if we were to move lots of our MAX.gov apps over.

**Comment by nikzei** [comment]
Let's discuss and groom with [@jameshupp - James Hupp] before we pick this up.

**Comment by nikzei** [comment]
See card for pricing visuals: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-2911

**Comment by nikzei** [comment]
Also related, this card re: improving navigation for pricing: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-2798

**Comment by nikzei** [comment]
I'm typing up notes from a pricing research session with a colleague at 18F.

**Comment by nikzei** [comment]
Note that we have not yet conducted testing to validate these assumptions about the success of our changes. Testing should follow - we'll make a card.
