### ISSUE TITLE
Add hidden notes indicating documentation required for compliance

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#361]
In order for cloud.gov documentation contributors (especially cloud.gov staff) to maintain these docs without accidentally deleting something important (or breaking an important link), we need some hidden indication that a section/page/link is important for compliance.

We currently don’t mark or indicate that some of these docs pages/sections/diagrams are _required_ to be here for FedRAMP compliance, so it’d be easy for a person in the future to trim something that doesn’t look important but is secretly important. (Currently “this is required for compliance” is tracked only in the [System Security Plan](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0) and in a few people's heads.)

We should figure out how to make hidden comments, and then those of us with cloud.gov compliance knowledge in our heads should review the docs and add hidden comments to all of the important-for-compliance sections.

This should also happen for the onboarding docs stored in https://github.com/18F/cg-product - for example, some of those checklist items are required and important. There are also a few other scattered important things - for example we're mentioning https://github.com/18F/cg-postmortems in the SSP. We need to keep track of these.

**Comment by afeld** [comment]
Maybe

``` html
<!-- this is required for FedRAMP Moderate -->
```

?

**Comment by brittag** [comment]
I briefly tried this for our Onboarding Checklist since I was digging around in there anyway, and...GitHub is annoyingly persnickety about where it'll display HTML-style comments as comments and where it'll display that as normal text. I suspect for the Checklist we should just restructure the checklist and mark off a section as "pleeeease do this for compliance".

**Comment by brittag** [comment]
We should also put hidden notes like this in parts of our 18F Handbook and other 18F-wide policies and practices that are relevant for cloud.gov compliance (such as https://github.com/18F/open-source-policy/blob/master/practice.md).

**Comment by mogul** [comment]
Was this only icebox'd because the comments were a problem in checklists? Would that have worked in more prose-y pages?

**Comment by brittag** [comment]
I put this in Icebox since it didn't seem to have a specific priority. We can totally implement this in various ways (including hidden comments, or adding visible details when hidden comments aren't available, etc) in all the relevant pages.

**Comment by mogul** [comment]
It seems important to ensure people are aware of this when editing docs, particularly as we've got a fairly major reorganization of operator vs tenant documentation coming up. I'm going to move it back to the Backlog but detach it from the FedRAMP epic so it's not considered "in-scope" for this month.
