### ISSUE TITLE
Update third-party services list

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#367]
https://docs.cloud.gov/ops/third-parties/ is an incomplete list...we should add the services we came up with as part of the FedRAMP work.

https://docs.google.com/document/d/1iOA_7c8iuhVLbmIdRbM6DgIwQh72JcnKxRxP0SOcTbs/edit

/cc @LinuxBozo @brittag

**Comment by brittag** [comment]
We've deleted that page.
