### ISSUE TITLE
Bulleted lists use a different font from other content

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-site#374]
Here's an example, taken from the [Leveraging Authentication](https://docs.cloud.gov/apps/leveraging-authentication/) page:

> <img width="671" alt="screen shot 2016-08-19 at 6 45 28 am" src="https://cloud.githubusercontent.com/assets/124687/17807453/b264f874-65d8-11e6-9c6e-4b229636b74c.png">

Here the paragraphs are in Merriweather, yet the bulleted lists are in Source Sans Pro.  It seems like the bulleted lists should inherit the font of the content they're embedded in (i.e., in this case, they should be in Merriweather).

Unfortunately, I'm not sure if this is a problem with cg-docs or cg-style (I strongly doubt it's a problem with uswds, but I could be wrong).

**Comment by brittag** [comment]
This is now consistent:

![screen shot 2016-11-28 at 3 25 15 pm](https://cloud.githubusercontent.com/assets/391313/20690341/e2eff656-b57e-11e6-844b-c40c84b350f9.png)
