### ISSUE TITLE
Refine CDN advice on Production Ready Guide

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#375]
Carrying over [a few comments from this merged PR](https://github.com/18F/cg-docs/pull/365#discussion-diff-75249814) for the [Production Ready Guide](https://docs.cloud.gov/apps/production-ready/), for improving the [Asset Serving](https://docs.cloud.gov/apps/production-ready/#asset-serving) bit further:

> @afeld: "Do we actually have anyone in 18F serving assets from S3? Since we're offering CloudFront in GovCloud, I'd actually remove this recommendation in favor of saying "use our CloudFront CDN service (if you're in GovCloud), and make sure your application sets the appropriate [caching headers](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en).""
> 
> @LinuxBozo: "Not sure about S3, but we do provide instructions for setting up S3 as a service, and how to modify the policy to make it available outside of cloud.gov, so will link there. As for our CloudFront service, I don't believe we actually are using the CDN features when setting up that service. @jmcarp?"
> 
> @dogweather: "I agree with @afeld's sentiment: avoid the extra complexity of an asset server, and let the CDN optimize it."

**Comment by dogweather** [comment]
Thanks @brittag !

I'm coming from the point of view of having deployed several apps to cloud.gov-like environments using the put-your-assets-on-S3 approach. It used to be the recommended best practice. 

The thing is, it's a whole other process, server, set of permissions, etc. to manage and occasionally mess up.

So now the best practice seems to be, don't worry about it, and let the CDN do its job. Far simpler, and the same results: fast asset serving without hitting the dynamic application server.

**Comment by afeld** [comment]
Also a note that we should link to https://docs.cloud.gov/apps/custom-domains/#managed-service-method.

**Comment by brittag** [comment]
Carrying over [another comment from the merged PR](https://github.com/18F/cg-docs/pull/365/files/f3d74bcbd11c764f5693e935c3a6527f55ed236f#r76273667), from @jseppi:

> Per [discussion in Slack](https://18f.slack.com/archives/dev/p1472140610002098), it sounds like the best practice here is _not_ to use S3 or a CDN _unless_ you have huge traffic concerns. So maybe that first sentence in this section should be something along the lines of:
> 
> "If your application is expected to receive [THRESHOLD # OF REQUESTS], then you should use the CloudFront CDN to serve your static assets"
> 
> and the "How" section should include a link to https://docs.cloud.gov/apps/custom-domains/#managed-service-method (with the caveat that this isn't available until the migration to GovCloud is complete).

**Comment by jmcarp** [comment]
I haven't tested caching behavior on the CDN service, but we're pretty close to the CloudFront defaults for caching settings, so setting caching headers should work:

<img width="540" alt="screen shot 2016-08-25 at 12 15 59 pm" src="https://cloud.githubusercontent.com/assets/1633460/17977027/fedbeee4-6abd-11e6-8c9a-cac86d7a705d.png">

It wouldn't be a bad idea to verify that this works as expected before recommending.

**Comment by mogul** [comment]
Closing as stale; lots has changed since this was written! Comment if still relevant.
