### ISSUE TITLE
Add references to Dashboard functions in appropriate places in the docs

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#387]
In order for cloud.gov tenants to learn how to accomplish cloud.gov tasks with ease whether they prefer command line interfaces or GUIs for those tasks, our docs should explain both using the CF CLI and the cloud.gov Dashboard for tasks where both options are available.

Right now our docs mostly explain the CF CLI. We should go through the "Usage" docs and add notes about the Dashboard where relevant. For example:
- https://docs.cloud.gov/getting-started/setup/
- https://docs.cloud.gov/apps/managed-services/

Not sure what the acceptance criteria or parent epic issue for this should be - just noting down that we should do this at some point. :D

cc @msecret

**Comment by suprenant** [comment]
Noting that this could possibly require Liberator support.

**Comment by brittag** [comment]
Yes, I'd recommend working on this with Liberator support - to work together to identify all the many places in the docs that line up with the many helpful Dashboard features!

**Comment by brittag** [comment]
I'd also guess that some copy + documentation link updates for the Dashboard itself would naturally be a byproduct of working together on this story. :)

**Comment by brittag** [comment]
I made a list of the places for this: https://github.com/18F/cg-site/pull/1020#issuecomment-323135000

**Comment by mogul** [comment]
We do this wherever we can using purpose-built styling now, and will be revamping screenshots soon as the dashboard changes.
