### ISSUE TITLE
Coordinate "General Tips" with "Production Ready Guide" somehow

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#388]
These two pages seem to overlap in some ways:
- https://docs.cloud.gov/apps/deployment/ (which the docs direct people to read as part of their user onboarding after reading https://docs.cloud.gov/getting-started/your-first-deploy/)
- https://docs.cloud.gov/apps/production-ready/

I'm not sure exactly what needs to be done here, but it looks like we should take a look at them and coordinate them so that a new user learns what they need to know upfront, but isn't overloaded with detail upfront - they know where to go for additional details that they'll need later.

**Comment by mogul** [comment]
See also [info from cloud.gov.au](http://docs.cloud.gov.au/usage/orca/), which also has good tips that could be integrated.

**Comment by brittag** [comment]
We now have basic sequencing / cross-linking here.
