### ISSUE TITLE
As a user, I want to know how to import data to cloud.gov databases

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#396]
From a support email:

> Is there a recommended method to import data into a bound data service?  It seems like the security groups are setup such that direct database access using the credentials and connection string from “cf env” are not allowed.  Trying to import into Postgresql.

My reply:

> You're correct that the databases don't allow access outside of cloud.gov itself. We talk a bit about how to get data out of databases here:
> 
> https://docs.cloud.gov/apps/databases/#export
> 
> Importing into RDS would be similar, but the other way around:
> 1. Download the `pg_restore` executable into your project folder.
> 2. Save the data as a SQL file in your project folder.
> 3. Do a `cf push` from your machine.
> 4. Use the [short-lived app](https://docs.cloud.gov/getting-started/one-off-tasks/#short-lived-app) technique to [do the restore](https://docs.cloud.gov/apps/databases/#restore-to-local-database).
> 
> I CC'd @pkarman, one of the engineers at 18F, who has done this multiple times. Peter, where would one download the appropriate `pg_restore` from?

**Comment by pkarman** [comment]
here's the workflow I've used in the past: https://gist.github.com/pkarman/20f4a4a022a2c59e49bd96675e8101c3

**Comment by LinuxBozo** [comment]
Related: 18F/cg-product#230 and 18F/cg-product#231

**Comment by mogul** [comment]
[Now documented](https://cloud.gov/docs/services/relational-database/#access-the-data-in-the-database)
