### ISSUE TITLE
add additional information around hardening

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#399]
From @mogul, in an email thread with GSA OCISO:

> _[cloud.gov](http://cloud.gov/) specific stuff starts here &gt;&gt;&gt;_
> 
> For the [cloud.gov](http://cloud.gov/) side, there are [some helpful diagrams that explain the delineation between layers](http://www.markkropf.com/blog/2015/2/19/an-applications-view-of-the-cf-stack) that sit below hosted applications. Notes on how each of these layers fits into a hardening regime:
> - **stemcell**: Stemcells form the basis for every type of VM that gets deployed as part of cloud.gov... Not just the hosts where hosted applications run, but also support VMs.
>   - On the host for hosted applications: While [cloud.gov](http://cloud.gov/) runs Ubuntu to provide the stemcell, the hosted application only sees the running kernel ABIs via an application-specific namespace. So the actual host distro is immaterial... The filesystem is essentially empty until it is populated with the rootfs (see next). 
>   - That said, the Ubuntu distro that comprises the stemcell itself is hardened upstream, with [additional minor hardening](https://github.com/18F/cg-harden-boshrelease/tree/master/src/harden) done locally as it's pulled into [cloud.gov](http://cloud.gov/)'s deployment. The actual work done there is based on [the work we did on Ubuntu 14.04 LTS for FISMA-Ready](https://github.com/fisma-ready/ubuntu-lts).
> - **rootfs**: Effectively, this is the root filesystem that every application we host actually sees. This layer is also based on the Ubuntu 14.04 LTS Linux distribution. You can see [the exact set of Ubuntu packages installed and how they're configured](https://github.com/cloudfoundry/stacks/tree/master/cflinuxfs2) (start by looking at the Dockerfile). It contains only the minimum set of dependencies necessary for doing further language-specific setup in each buildpack (see next). 
> - **buildpack**: When application code is pushed to [cloud.gov](http://cloud.gov/), the language required is detected, and then both the "horizontal" and "vertical" (Noah's terms) stack supporting each language gets setup. 
>   - Each buildpack basically sets up the bare minimum/safe configuration for hosting an application written for that language runtime, then exposes configuration options for the app developer to say what else he wants done (eg what extensions to install). Here're [the docs for the PHP buildpack](http://docs.cloudfoundry.org/buildpacks/php/index.html), for example. 
>   - When you look at the source code for each buildpack (GitHub links [here](http://docs.cloudfoundry.org/buildpacks/#system-buildpacks)) you can see exactly what defaults are applied. For example, in the PHP buildpack you can see [the default configs for each of newrelic, PHP, and Apache or nginx](https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config) (depending on what the app author opts for). Note that if you click into each, you'll see defaults for _each supported version_ of each dependency, because buildpacks support a range of versions to make life easier on app developers.
>   - [cloud.gov](http://cloud.gov/) periodically updates buildpacks to address CVEs in their respective language stacks. Hosted apps have to be restarted to pick up the changes. We are planning to notify hosted teams whenever this is needed. (We've also talked about restarting them automatically after a grace-period, but need to test how much that would upset them.)
> 
> Separately, [cloud.gov](http://cloud.gov/) provides managed services to which teams can self-provision access. For example, MySQL, Postgres, Redis, Elasticsearch, etc. Application teams never see the hosting side of those services; they just get credentials to access them from their app. Accordingly, all the configuration for hosting those services happens on the [cloud.gov](http://cloud.gov/) side. So, lots of economy of scale in hardening there.
> 
> So looking at this list, for stuff hosted in [cloud.gov](http://cloud.gov/):
> - **Docker**
> - **Apache**
> - **nginx**
> - Drupal  
> - Wordpress  
> - jboss  
> - **mysql/mariadb**
> 
> ...the bolded ones are taken care of on the [cloud.gov](http://cloud.gov/) operator side, and application developers never really see them day to day. (They never see Docker unless they care to take on the added responsibility of replacing the buildpack functionality; see below for a suggestion on both the [cloud.gov](http://cloud.gov/) and non-[cloud.gov](http://cloud.gov/) Docker case.) For Drupal, Wordpress, and jboss, only the underlying language runtime is taken care of by [cloud.gov](http://cloud.gov/). However, there are plenty of examples to look at for how people typically deploy them on Cloud Foundry or Heroku which can still be instructive. 
> 
> _&lt;&lt;&lt; [cloud.gov](http://cloud.gov/) specific stuff ends here_
> 
> The Cloud Foundry community puts a lot of scrutiny and testing and minimizing surface area, so starting with these examples can also be helpful in developing standards for teams running these packages outside of the [cloud.gov](http://cloud.gov/) context! I suggest you start from the Cloud Foundry buildpacks and the deployment scripts for the managed services (I didn't provide links, but they exist), then add our own locally-identified GSA hardening, similar to what we did on the Ubuntu stemcell. (Anything we find missing from the upstream distribution can be rolled in locally, improving hardening of [cloud.gov](http://cloud.gov/) throughout this process... We can also contribute these changes upstream.)

Not exactly sure where it should live, but seems relevant.

**Comment by nikzei** [comment]
We'll incorporate this text into https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-603
