### ISSUE TITLE
On Custom Domains page, explain GovCloud status of Managed Service Method better

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#400]
https://docs.cloud.gov/apps/custom-domains/ is currently confusing. See "the docs really need to be updated because they really aren't clear by what it means by "you must use GovCloud". So the broker is in GovCloud but it writes _back_ to E/W" (https://18f.slack.com/archives/infrastructure/p1473344504000101) and earlier conversation above that.

**Comment by nikzei** [comment]
Let's do a docs-focused sprint working on docs after @berndverst and @jameshupp make headway with structural website changes. @berndverst @jameshupp

**Comment by brittag** [comment]
This is fixed.
