### ISSUE TITLE
Suggest ways to ensure an entire team can use cloud.gov productively

### ISSUE THREAD

**Issue by tadhg-ohiggins** [cloud-gov/cg-site#402]
In order to help teams share knowledge about how they are using cloud.gov, we should document best practices for capturing cloud.gov specific processes.

Acceptance Criteria

- [ ] we provide guidance on how to best capture how any given team is using cg

(we can't know what works best for individual teams, but we can suggest things that work well, eg, manifest files, single commands for deployment, documenting in the read.me)
 
Original text below:

---
Despite working on a project (eRegs) that uses cloud.gov, I don't deploy or otherwise deal with cloud.gov often enough to stay familiar with the environment. Working with it more frequently would be helpful, ideally in such a way that could replace local development.

**Comment by brittag** [comment]
Context - I asked @tadhg-ohiggins to write this down as a general dev user issue for us to consider dealing with in our docs somehow. It could be part of general user advice ("make sure each technical member of your team is deploying frequently enough to retain knowledge") or something to consider for how we write our docs in general.

**Comment by nikzei** [comment]
@tadhg-ohiggins  - would love to have a conversation with you about this and learn more. I'll arrange!

**Comment by nikzei** [comment]
PI8 75% assessment:
SHOULD
--> this speaks to an important need that existing users have, particularly new users.

**Comment by brittag** [comment]
I think the best way to solve this is by generally having good docs that serve newcomers well, so that people who are returning to cloud.gov after a while away are served well too.
