### ISSUE TITLE
As a [potential] user, I want to know what technologies I can use on cloud.gov

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#405]
I just (essentially) got this question this question from GSA's Deputy CIO...the answer is _kinda_ in a few pages, but I think we could have a clearer answer that we can pull people to. Relevant links:
- https://docs.cloud.gov/intro/pricing/whats-included/
- https://docs.cloud.gov/intro/technology/responsibilities/
- https://github.com/18F/cf-hello-worlds

**Comment by jmcarp** [comment]
I wonder if this question is too broad to try to answer in one place--what even are "technologies"? It could mean services, or languages, or other things, but IMO those belong in different places. I'm going to close this, but please reopen if I shouldn't have @afeld @brittag @mogul. Better to ask for forgiveness than permission 😇
