### ISSUE TITLE
Note for rails deploys to docs

### ISSUE THREAD

**Issue by jessieay** [cloud-gov/cg-site#412]
We might want to add some information about deploying on CF with Rails

Something like:

Make sure you set the `SECRET_KEY_BASE` environment variable for your Rails app. Otherwise, the Cloud Foundry ruby buildpack will automatically set it for you on each deploy. If you are using an authentication system that relies on session variables, not having `SECRET_KEY_BASE` set will effectively log out all of your users each time you deploy your application.

More info here:

https://gist.github.com/jessieay/25ac100206b9a40a191494fb4fc82d56

**Comment by afeld** [comment]
You mean like https://docs.cloud.gov/apps/rails/? 😉 Or are you just saying that neither ours nor the official docs mention the `SECRET_KEY_BASE`? Would be great to send a pull request to the latter to mention that.

**Comment by jessieay** [comment]
Yes, neither ours nor the official docs mention the consequences of not setting it.
