### ISSUE TITLE
Integrate search for docs into Cloud.gov nav

### ISSUE THREAD

**Issue by suprenant** [cloud-gov/cg-site#419]
@mogul commented on [Wed Apr 13 2016](https://github.com/18F/cg-dashboard/issues/237)

In order to save&nbsp;users time in finding&nbsp;everything relevant to their cloud.gov needs, we want an omnipresent search facility&nbsp;that will return search results for all public-facing materials.

Acceptance criteria
- [ ] Search results include hits from docs
- [ ] It's easy to initiate a search from any place that includes global cloud.gov navigation.

---

@mogul commented on [Wed Apr 13 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-209550034)

See [the task list for implementing search.usa.gov](http://search.digitalgov.gov/blog/go-live.html), which [we've already provisioned](http://search.digitalgov.gov/blog/go-live.html).

---

@mogul commented on [Wed Apr 13 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-209557597)

@sharms prototyped this directly on the docs site, see [the diff](https://github.com/18F/cg-docs/compare/enable-search)

---

@msecret commented on [Thu Apr 14 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-210272521)

I've gone ahead and updated the colors in digital.gov's site to work with our design. It's not perfect because the navigation scheme is different and the fonts aren't there, but I don't think we can get any closer.

---

@msecret commented on [Thu Apr 14 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-210273040)

This work will be simply including the form given by digital gov and possibly apply some web design standards classes to ensure it's styled properly. The digital gov JS can also be added as a separate file from the main JS.

---

@mogul commented on [Fri Apr 15 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-210628848)

For future:

> Did you know? We offer results through our Search Results API, if you'd like to create mash-ups or have complete control of the look and feel of your search results pages. You can access our Search Results API Instructions by clicking on the Activate Search option in the left-hand menu in the Admin Center.

---

@mogul commented on [Fri Apr 15 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-210687101)

Just to be clear: I didn't expect styling of the search results page to be in-scope for this story at all! Have created #246 to account for that, and placed it waaaay low in the backlog.

---

@jeremiak commented on [Mon Apr 18 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-211427582)

Per @msecret's [comment](/18F/cg-deck/issues/187#issuecomment-210274611), does it make sense for this search to return all public facing cloud.gov materials or just things within the deck? That would mean you could search for apps, orgs, or (I'd imagine) services.

I think it should be the same global search as everything else, as the deck isn't all that complicated and doesn't warrant a specific search IMHO 

---

@msecret commented on [Mon Apr 18 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-211480074)

I'd agree with your opinion that the deck isn't complicated enough now to warrant a search.

---

@mogul commented on [Mon Apr 18 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-211618259)

I think including deck entities like orgs, spaces, and apps in search is a separate concern altogether as it'll be specific to each user and depend on their permissions. So let's take it an expansion of how search works at a later time, when we find users are having a hard time finding all of their entities.

---

@msecret commented on [Fri Apr 22 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-213624300)

Here are some design options for the nav menu. 

The base of this design is that there's a search icon as the last item in the nav bar. Clicking on the icon brings up the full search bar as seen in the designs. Clicking anywhere off the search bar will un-expand the search bar in all these examples. Here is how the navbar will look initially:

![topnav_search-b-base](https://cloud.githubusercontent.com/assets/1701077/14757287/c2cbeb9e-08a6-11e6-8082-a99be6520049.png)

**Option A: animate expand left, moving the nav items over**. This expansion will have the search bar expand left moving over the nav items.

![topnav_search-b-1](https://cloud.githubusercontent.com/assets/1701077/14757288/c56fee7c-08a6-11e6-83d1-08ce54c54a3c.png)

**Option B: animate expand left, moving on top of nav items**. This expansion will have the search bar expand left moving on top of a couple of nav items.

![topnav_search-b-2](https://cloud.githubusercontent.com/assets/1701077/14757291/c719c748-08a6-11e6-9af2-52c6f4d0178f.png)

**Option C: fade in search bar below**. This expansion will fade in a search bar below the icon and nav items.

![topnav_search-b-3](https://cloud.githubusercontent.com/assets/1701077/14757295/c975a70a-08a6-11e6-84d7-39bc73ea3a30.png)

**Option CE: option C with small error to point to search icon**

![topnav_search-b-3-extra](https://cloud.githubusercontent.com/assets/1701077/14757299/d23b2270-08a6-11e6-836e-2acb8b7c37ad.png)

The speed and ease of the animation will likely be similar to [mediums global search](https://medium.com). I might work on bringing some quick animation to show these examples in the most realistic manner,

---

@mogul commented on [Fri Apr 22 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-213626562)

The ones that go down seem better... Popping over the other nav items feels weird and pushing over the other nav items send like it would behave strangely at narrow widths. Then again I have a poor grasp of how responsive layout works. :)

---

@msecret commented on [Mon Apr 25 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-214433011)

@jcscottiii lets go with option C, I'll discuss acceptance criteria and parameters here
##### MVP
- [ ] GIVEN a user WHEN they're on a cloud.gov page THEN they should see a search icon in the navigation.
- [ ] GIVEN a user on a cloud.gov page WHEN the user clicks on the search icon THEN a search input box should appear directly below the search icon AND their "focus" should be on the search input box
- [ ] GIVEN a user clicks the search icon WHEN a user clicks outside of the search input box THEN the search input box should not be displayed
- [ ] GIVEN a user clicks the search icon WHEN the user hits "Enter" THEN the page should go to the search results page
##### Post-MVP
- [ ] GIVEN a user on a cloud.gov page WHEN they click on the search icon THEN they should see a search box with a small arrow pointing back at the search icon
- [ ] GIVEN a user on a cloud.gov page WHEN they click on the search icon THEN the search bar should fade into view in a 0.75 animation.

---

@thisisdano commented on [Thu Sep 01 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-244138799)

OK, so here's a sketch of a search bar that doesn't occupy persistent space.
Invision: https://gsa.invisionapp.com/share/9T8GMJ8B8#/185612030_Search

Replaces nav with search bar when selected — returns to icon when dismissed.

Kinda duplicates one of the options above, but maybe nicer?? 

---

![search 2x](https://cloud.githubusercontent.com/assets/11464021/18175621/cc0cee96-7026-11e6-8c01-741ac1cbc222.png)

---

I'm sure there are some changes to the top nav we'll want to make at some point as well. Too many items! I mean, why have a prominent `About` page on the dashboard nav? Even `Contact` seems way too important. And `Logout` kinda fades in with the rest. It's an action rather than a destination.

---

@suprenant commented on [Mon Sep 12 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-246420040)

Pending https://github.com/18F/cg-style/issues/144

---

@suprenant commented on [Mon Sep 26 2016](https://github.com/18F/cg-dashboard/issues/237#issuecomment-249647382)

Updated this to be docs only and breaking out landing page and compliance results into a separate story.

**Comment by suprenant** [comment]
Replacement from previous issue. Noting that we will want @thisisdano @vz3 review for approval.

**Comment by juliasolorzano** [comment]
Got sign off from design that this is gtg when this PR is merged in: https://github.com/18F/cg-style/pull/159

**Comment by thisisdano** [comment]
A couple comments on this — not blocking release, but we'll want to have them eventually:

- highlighted search icon is appearing low-rez
- close box appearing low-rez
- close box should appear exactly where search icon appears (i.e. it shouldn't jump down)
- focus should move to search when it's activated
- `esc` should close the search
- `/` should trigger/close the search

**Comment by suprenant** [comment]
I put @thisisdano notes for polishing here:

https://github.com/18F/cg-docs/issues/451
