### ISSUE TITLE
Provide info for SaaS vendors wanting to use cloud.gov

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#427]
In order to reduce team overhead and distractions from SaaS vendor inquiries, we want docs.cloud.gov to include a canonical response about how cloud.gov can/can't help them.

Implementation sketch:
- Can start from recent responses on the cloud-gov-inquiries list

**Comment by brittag** [comment]
We now have guidance for this on https://cloud.gov/docs/help/
