### ISSUE TITLE
Update FedRAMP timeline

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#428]
In order to reduce team overhead and distractions from agency inquiries, we want docs.cloud.gov to include a canonical response about our FedRAMP timeline and availability.

**Implementation sketch:**
- Update [the existing page](https://docs.cloud.gov/intro/security/fedramp-tracker/) based on recent responses in the cloud-gov-inquiries mailing list and info from the FedRAMP PMO

**Comment by nikzei** [comment]
Update should be a change in the target date so that it is  . . . not October but what? December?

@mogul, who do you suggest would be a good match for this task? @brittag perhaps?

**Comment by brittag** [comment]
Closed by https://github.com/18F/cg-site/pull/514
