### ISSUE TITLE
Elaborate resilience, backup, and restore attributes for RDS service

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#429]
In order to eliminate customer confusion about how they can meet resilience and backup compliance requirements, it should be obvious which concerns are taken care of by the various RDS plans.

**Implementation sketch:**
- A page in docs includes full details on characteristics of the RDS service based on recent cloud-gov-inquiries and cloud-gov-support traffic
- RDS service and plan descriptions are updated to clarify their attributes, and point to the docs page

**Comment by brittag** [comment]
Basic info handled by https://github.com/18F/cg-site/pull/1076
