### ISSUE TITLE
Consolidate current E/W-GovCloud migration documentation

### ISSUE THREAD

**Issue by jameshupp** [cloud-gov/cg-site#464]
There is a lot of documentation that explains how to do certain things twice, once for each environment. However, there isn't a central place that helps people identify if they need to migrate, if they're ready to migrate, and what they'll need to do/know as they go. We're about to start telling people the migration is coming, so we should compile documentation about it in an easy-to-reference place. See [cg-product 238](https://github.com/18F/cg-product/issues/238).

**Comment by afeld** [comment]
Closed by https://github.com/18F/cg-site/pull/480.
