### ISSUE TITLE
circleci cf client install instructions wrong

### ISSUE THREAD

**Issue by amaline** [cloud-gov/cg-site#467]
The link on the wget command

  http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.deb

one the page https://docs.cloud.gov/apps/continuous-deployment/ does not work.

The following would be better:

```
- curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
- sudo mv cf /usr/local/bin
- cf -v
```

**Comment by adborden** [comment]
These are the commands we're using for dashboard. Has the advantage that it's still using a `.deb` file.

```
curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
sudo dpkg -i cf-cli_amd64.deb
cf -v
```

**Comment by msecret** [comment]
Is there a reason this was assigned to Navigator?

**Comment by adborden** [comment]
I'm not exactly sure why it ended up in the Navigator queue, but I think it makes sense. Both Navigator and Skyporter have overlapping goals in keeping documentation and overall platform UX consistent. Navigator seems to act as the "technical arm" for Skyporter recently and I'm happy to take on this work.

I wonder if at some point this example actually came from cg-dashboard's deploy script.
