### ISSUE TITLE
Dumping/restoring databases in GovCloud using port-forwarding should be documented

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-site#477]
In order for customers to manage the content of their DB services instances between spaces, the docs on managing databases should include an outline of how to use port-forwarding in the GovCloud environment.

**Background:**

The [databases page](https://docs.apps.cloud.gov/apps/databases/) outlines a cumbersome process for dumping/restoring DBs to/from a file in the instance, which requires the user to also download/upload that file.

In the GovCloud environment, if SSH is enabled for the space or the specific app, then [port-forwarding](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-services.html) can be used to directly interact with the database from the user's workstation. We should refer people to this method, since they probably don't want to hassle with uploading/downloading the dumpfile.

A common request is to be able to take a dump of a service instance in space A (eg `prod`) and immediately restore it to a service instance in space B (eg `stage`). I am guessing we could provide a one-line script that would directly dump from a DB service in space A and pipe that to a restore to a DB service in space B.

**Comment by suprenant** [comment]
We have a tool that can do this instead: cg-migrate-db.
