### ISSUE TITLE
Document cloud.gov east aws account

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/cg-site#484]
Because it exists, and we do things with it

cc @dlapiduz @sharms

**Comment by afeld** [comment]
Could you provide some more detail here?

**Comment by jmcarp** [comment]
cloud.gov has an aws account in the us partition that isn't the 18f account, which is where we keep cloudfront distributions for govcloud. We should document the existence of this account, what it's for, and who needs access.

**Comment by dlapiduz** [comment]
Here is some info: https://github.com/18F/cg-site/pull/506/files
