### ISSUE TITLE
As a reader, I want to know what content is specific to GovCloud vs. East/West

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#485]
We already do this on a bunch of pages, but I suggest that we
1. [x] Audit/update the docs for what _isn't_ marked as such and shouldn't be
2. [x] Come up with a standardized way of indicating the environment(s?) a page or section of a page to pertain to; Don't Make Them Think

/cc @jameshupp

**Comment by afeld** [comment]
My other thought here is that we could even have a toggle to say whether you're using East/West or GovCloud, and it would hide the non-relevant parts of the documentation.

**Comment by mogul** [comment]
It's great if you can figure out how to do that... The other use-case is for people using CLI or dashboard when an action could be taken in either. See for example [the client-specific instructions](https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-Slack-team) in Slack's docs.
