### ISSUE TITLE
Help cloud.gov tenants help teammates understand what is needed to deploy

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#486]
Per https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1477431141005742.

https://cloud.gov/docs/apps/managing-teammates/#give-roles-to-a-teammate

/cc https://github.com/18F/cg-dashboard/issues/619

**Comment by afeld** [comment]
@mogul Didn't we determine a user can get roles after they are invited but before they've accepted?

**Comment by mogul** [comment]
Pretty sure we did confirm that, yes.

**Comment by mogul** [comment]
(At least on the data/CLI side.)

**Comment by suprenant** [comment]
Not thinking there will be a strong need here, but we can pick this up if needed.

**Comment by brittag** [comment]
We're handling this with existing stories.
