### ISSUE TITLE
As a product owner migrating to GovCloud, I want to know the costs involved

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#487]
- Having orgs in two places will incur quota costs in both places (right?)
  - It's not self-service to change the quotas as they go (/cc https://github.com/18F/cg-product/issues/386), so they can't really scale the price up and down if they are moving over slowly.
- Staff time (how to estimate this)
    - I've been telling people "a half hour to a week" worth of people-hours

## Acceptance criteria

As a product owner whose system needs to migrate, I understand:

* [ ] The costs on the cloud.gov side for the migration, if any
* [ ] The costs to my project in terms of my developers' time

/cc @abisker @jameshupp

**Comment by afeld** [comment]
> Having orgs in two places will incur quota costs in both places

@dlapiduz @mogul Can you confirm this?

**Comment by dlapiduz** [comment]
Lets be super clear about this... 

For usage we will either bill for GovCloud or E/W not for both. At this point we are only billing for E/W.

For access package it doesn't matter where your account is we will only bill you once.

**Comment by abisker** [comment]
Ah that's great @dlapiduz! So we won't bill double for GovCloud and E/W. And we're not billing the partner for cloud.gov team time, but we ARE billing them for the project's team time in doing the transfer -- correct?

**Comment by dlapiduz** [comment]
Correct, in most cases it won't be a huge lift and the cloud.gov team will help out. The end result is probably a better state for everyone.

**Comment by abisker** [comment]
Yep, definitely. Thanks for the clarifications!

**Comment by afeld** [comment]
From @adelevie [in Slack](https://gsa-tts.slack.com/archives/cloud-gov-migration/p1478183482000164):

> I guess I'm unclear what level of consulting everyone is getting for free.

(This might be a tangential story.)
