### ISSUE TITLE
Update LICENSE file to note files in repo that are not public domain

### ISSUE THREAD

**Issue by berndverst** [cloud-gov/cg-site#492]
Reported by @brittag (and moved from another repo)

The LICENSE file says the repo is in the public domain, but there are some exceptions in https://github.com/18F/cg-site/tree/master/static/assets - so we should evaluate what needs to be in the LICENSE file and update it. We should also figure out whether we include any non-public-domain work from the Hugo template we use for this.

We should update the CONTRIBUTING file to match as well.

**Comment by brittag** [comment]
Related issue: https://github.com/18F/cg-docs/issues/228

**Comment by mogul** [comment]
@brittag is this still something for us to follow up on?

**Comment by brittag** [comment]
Yeah, we should still do this eventually.
