### ISSUE TITLE
Pa11y fixes

### ISSUE THREAD

**Issue by berndverst** [cloud-gov/cg-site#493]
Moved from another repo

@jeremiak commented on [Thu May 12 2016](https://github.com/18F/cg-landing/pull/65)

Inspired by #58 though it is now out of date because of the redesign. I ran the `HTML_CodeSniffer` tool on the current master branch and tried to fix the items that were in the "Error" category.

This PR changes:
1. The `<h2>` element in the header to be a regular `<div>` since it had no text content
2. The "Contact Us" form to use a `<legend>` instead of an `<h4>`

The tool also complained about color contrast and have opened 18f/cg-style#68 to address that.

Style changes required since using a `<legend>` instead of `<h4>` are addressed in 18F/cg-style#69

**Comment by mogul** [comment]
Closing as stale
