### ISSUE TITLE
Broken links to invite users

### ISSUE THREAD

**Issue by cnelson** [cloud-gov/cg-site#501]
These two pages have broken links to the invite app:
- https://github.com/18F/cg-site/blame/master/content/docs/apps/managing-teammates.md#L12
- https://github.com/18F/cg-site/blame/master/content/docs/ops/managing-users.md#L16

The links for invites are different for [govcloud](https://invite.fr.cloud.gov) and [east](https://invite.cloud.gov) so i wasn't sure how we wanted to display that information in the docs thus this issue instead of a PR.

**Comment by mogul** [comment]
@nikzei, for your attention... Stuck it at the bottom of the skyporter backlog for now.
