### ISSUE TITLE
Create a process for continuous updates of overview content

### ISSUE THREAD

**Issue by jameshupp** [cloud-gov/cg-site#520]
In order to reduce the amount of time we spend tracking down answers to questions of fact for prospective cloud.gov users, as a cloud.gov business team member I want a clear process for continuous improvement of product overview content.

I'm aware this construction centers a team member as the user, but in this story that's basically correct. Within the process of actually updating the content, the stories can be written with prospective and current platform users as the story's user.

To-dos:
- [x] Assemble the questions and issues raised by recent prospective cloud.gov users leading up to IAA that could be but were not answered by cloud.gov site content
- [x] Categorize the issues to clarify the broadest or deepest areas of concern
- [ ] Create a backlog of these issues in GH/Favro
- [x] Prioritize/comb the backlog
- [ ] Document a process in the Skyporter manual for making ongoing additions to the backlog

**Comment by berndverst** [comment]
What I propose is this:
Whenever we see a new question and a team member provides an answer, we either dump that quickly into a Github issue, or we just directly make a PR for it if it seems easy.

For incremental content updates that don't introduce entirely new page we can use a very lightweight process. And these should be small items we can easily knock out because they don't require research.

That being said, there will be other content work which needs planning, research etc. I am not speaking to those updates here.

**Comment by jameshupp** [comment]
I think that sounds great. The lightweight process as far as I'm concerned could be as little as just noting that a PR/commit to content went through. I want to be able to see if the areas where lots of small changes are made coalesce, whether it's around a theme or a specific part of the IAA process, or what. If they're all over, we could keep plugging at content. If they are concentrated together, that's an opportunity for direct research with people.

**Comment by nikzei** [comment]
PI8 75% assessment:
MUST
--> This is an important part of our efforts to make our communication efforts more user focused. We are close to meeting our set acceptance criteria.  Let's finish this up this PI, if not, let's get it done early PI9.

**Comment by nikzei** [comment]
We've made duplicates at cg-site #696 (also #691 is related). I will incorporate  relevant AC from those issues and then close them. cc [@James Hupp - TEACD] 

Document where we are tracking questions from inquiries listserv: https://docs.google.com/document/d/1nVCgwNdYO_IO_Vj-4FVeHWBlmLMrlOjXHmPghm0oObQ/edit?pli=1

**Comment by nikzei** [comment]
Ask [@sharms - Steve Harms] whether this is a priority item for him.
