### ISSUE TITLE
Document how to do Blue-Green deployments with an app

### ISSUE THREAD

**Issue by harrisj** [cloud-gov/cg-site#56]
I know I am being annoying, but I want to see this. It'll be so cool

**Comment by afeld** [comment]
Would love to figure out an easy way to distribute [this script](https://github.com/18F/C2/pull/500), since it's meant to be general-purpose.

**Comment by dhcole** [comment]
How about as its own repo with a package.json that has a `{ "bin": "deploy.sh" }` parameter? That should make it executable. Instructions for use would be:

``` sh
$ npm install -g cf-blue-green
$ cd path/to/app
$ cf-blue-green appname
```

**Comment by afeld** [comment]
Good call!

https://github.com/18F/cf-blue-green
