### ISSUE TITLE
The "deploying x" guides need copyediting 

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#560]
In order for cloud.gov tenants to set up apps quickly and easily, we need our "deploying x" guides to be clear, concise, and up-to-date.

Looking at this guides, they have some outdated bits ("It should now be running at APPNAME.18f.gov!") and passive voice. We should review them and fix them up:

- [x] https://cloud.gov/docs/apps/django/
- [x] https://cloud.gov/docs/apps/flask/
- [x] https://cloud.gov/docs/apps/meteor/
- [x] https://cloud.gov/docs/apps/rails/
- [x] https://cloud.gov/docs/apps/node/
- [ ] https://cloud.gov/docs/apps/static/

cc @jameshupp

**Comment by mogul** [comment]
I can appreciate what we did in #572 but now there's no indication of what languages we support. We should probably expand [this page](https://cloud.gov/docs/apps/frameworks/) to announce that clearly rather than burying that info behind buildpack jargon.
