### ISSUE TITLE
compile cloud.gov marketing package for engagement managers

### ISSUE THREAD

**Issue by nikzei** [cloud-gov/cg-site#577]
This should be a lightweight effort of pulling existing documentation and packaging it for engagement managers who will end up in the position of talking about cloud.gov with their agency partners. We should include basic product information (talking points?), intake template (this exists), and instructions about contacts within our team and other relevant information.

**Comment by nikzei** [comment]
PI8 75% assessment:
WON'T
--> If website clearly communicates value proposition to non-technical audience, we can direct engagement managers to the site. No immediate need to produce new materials.

**Comment by mogul** [comment]
Shall we `Icebox` then?

**Comment by nikzei** [comment]
I'd rather close this - I no longer see a need for it if our website successfully communicates the product and engagement managers can point prospectives to the site. 

If, in the future, engagement managers have a particular need that arises, we can address it then.
