### ISSUE TITLE
No Atom/RSS feed for subscribing to updates

### ISSUE THREAD

**Issue by suprenant** [cloud-gov/cg-site#590]
@suprenant commented on [Tue Nov 22 2016](https://github.com/18F/cg-dashboard/issues/759)

@adborden commented on [Fri Jul 08 2016](https://github.com/18F/cg-landing/issues/88)

I'd like to get updates from https://cloud.gov/updates/ via Atom/RSS. It seems like the `_feed.xml` is disabled.

**Comment by jmcarp** [comment]
@suprenant: is there a favro card for this? I'm hoping to continue closing these issues 😃

**Comment by gboone** [comment]
If there is, we should note there is a feed but it's maybe a non-intuitive URL https://cloud.gov/updates/index.xml
