### ISSUE TITLE
Market research: review communications by similar commercial products

### ISSUE THREAD

**Issue by nikzei** [cloud-gov/cg-site#600]
[sprints 4/5 - time blocked]

We're interested in understanding how other established B2B companies communicate about services similar cloud.gov. Stripe, Slack, Heroku, and many, many others . . . 

How do they discuss:
- the problem
- the product

**Comment by mogul** [comment]
This got done as part of the landing-page revamp, right?

**Comment by nikzei** [comment]
Yes!
