### ISSUE TITLE
add a section on "why we run a Paas"

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#61]
Can draw from here:

https://18f.gsa.gov/2015/05/08/layering-innovation/

**Comment by afeld** [comment]
Also can draw from (or maybe copy in) [the seed pitch](https://docs.google.com/document/d/19lFllSwzGrYERWMOv2o2SARcMsnaSQZiCg63YPQHEN4/edit).

**Comment by dlapiduz** [comment]
@afeld can we do a marketing page instead? (not joking)

**Comment by afeld** [comment]
:+1: 

/cc @rdpiazza

**Comment by dlapiduz** [comment]
Moved to a card: https://trello.com/c/6zeoLr7A/206-epic-build-landing-page

**Comment by afeld** [comment]
It lives!

https://docs.cloud.gov/intro/overview/why-build-cloudgov/
