### ISSUE TITLE
New, non-18F customer testimonies 

### ISSUE THREAD

**Issue by nikzei** [cloud-gov/cg-site#611]
In order to trust the cloud.gov as a product, I want to hear how it has worked well for other government teams like mine.

Acceptance Criteria:

- [ ] potential customers can learn about how cloud.gov has been used by other government teams
- [ ] potential customers can learn about cloud.gov from a neutral party that they can trust as credible (rather than only being able to learn from 18F teams that have an incentive to laud cloud.gov)
- [ ] whatever artifacts get produced, that they speak to the interests of both non-technical and technical audiences

@berndverst mentioned that we might be able to get one from the Air Force. Any other ideas?

Probably makes sense to wait a few months to give new outside users a little bit of time using our product before asking them for testimonials.

**Comment by nikzei** [comment]
PI8 75% assessment:
SHOULD
--> would be good to do since it strengthens our communications of our value proposition. Not a must.

**Comment by nikzei** [comment]
Document started by [@Britta Gustafson]  and [@James Hupp - TEACD]  to get this started: https://docs.google.com/document/d/1PEzMhZIndUIt2GibPYgya2WG3GWV2SjjAh33XmUsE0U/edit

**Comment by brittag** [comment]
Related card: [simple list of example systems](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3799).

**Comment by jmcarp** [comment]
@brittag: if we're tracking this in the card you linked, can we close this issue?

**Comment by brittag** [comment]
Yeah, let's close this. Thanks!
