### ISSUE TITLE
Describe the cloud.gov team on the website

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#617]
To help potential and current cloud.gov users gain a better understanding of cloud.gov and more confidence in it as a government service by and for government employees, our cloud.gov website could explain the team that builds this project.

This is just an idea right now - it could take a variety of forms on the website, or we could decide that it's not a good idea.

For example, the site could have a team page that explains:

* Where we work - brief explanation of our structure (cloud.gov in 18F in TTS in GSA)
* The squads and the people who work on them (list of squads with brief explanation of each, list of people in each squad, small photo of each person, maybe link to GitHub for each person)
* List of people who are no longer on the team but made contributions to cloud.gov

**Comment by brittag** [comment]
We currently have a team list at https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#squads and squad descriptions at https://github.com/18F/cg-product#sub-teamsthemes-of-work; we haven't quite kept them up to date, which is ok since this isn't blocking anything, but might be nice to consolidate together as a team list on the site.

**Comment by brittag** [comment]
No longer thinking this would be helpful - we don't really see people asking about this.

**Comment by nikzei** [comment]
marked as closed --> I'm archiving.
