### ISSUE TITLE
Needed sudo for cf-ssh `mv`

### ISSUE THREAD

**Issue by adelevie** [cloud-gov/cg-site#62]
From following the instructions here: https://docs.18f.gov/getting-started/cf-ssh/,

I ended up needing to run `sudo mv cf-ssh /usr/local/bin`. Everything still seems to work fine (e.g I can run `cf-ssh` without `sudo`).

**Comment by afeld** [comment]
I wonder what default permissions on that directory are for most people...

```
$ ls -l /usr/local | grep bin
drwxrwxr-x  291 aidanfeldman  admin   9894 Jun  1 15:44 bin
```

**Comment by dlapiduz** [comment]
I have similar permissions to @afeld but it doesn't hurt to add a note saying "you may need sudo". @adelevie can you send a PR?
