### ISSUE TITLE
Update services examples on Continuous Deployment page

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#623]
For some of the examples at https://cloud.gov/docs/apps/continuous-deployment/#continuous-integration-services it's not quite clear what you're supposed to replace and what you're supposed to keep (for example what to do with `http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.deb -qO temp.deb` and `dlapiduz/cloud-foundry-deploy`), and we also need to mention `api.fr.cloud.gov` along with `api.cloud.gov` to accommodate GovCloud.

**Comment by brittag** [comment]
We've mostly fixed these issues!

**Comment by nikzei** [comment]
I'm archiving issues that are marked as closed.
