### ISSUE TITLE
Documentation for mongodb service?

### ISSUE THREAD

**Issue by adborden** [cloud-gov/cg-site#624]
Looks like mongodb exists in govcloud, but not in e/w. I don't see it in the docs, but have questions about what I get with it. There is only one plan available standard.

```
 $ govcloud marketplace
Getting services from marketplace in org cloud-gov / space deck as aaron.borden@gsa.gov...
OK

service            plans                              description
mongodb32          standard                           MongoDB 3.2 service for application development and testing
```

Some questions I would like to see answered by the docs:
How many nodes in the replica set?
How much RAM does each node have?
How much storage is provided?
Is sharding available?
Are backups provided?

**Comment by mogul** [comment]
I thought this was only available to a certain subset of orgs, and invisible to others... /cc @dlapiduz

**Comment by brittag** [comment]
Yeah, we shouldn't document this since it's not supported and only available to like one internal org.
