### ISSUE TITLE
"Read more" links aren't linked in the service documentation

### ISSUE THREAD

**Issue by adborden** [cloud-gov/cg-site#625]
The "more" text is not clickable but the service name is linked to service-specific page. Maybe we should just drop the "Read More" column?
![screenshot from 2016-12-07 13-50-49](https://cloud.githubusercontent.com/assets/509703/20988123/3945fac6-bc84-11e6-802a-456f8ede8a7f.png)

**Comment by afeld** [comment]
Closed by #663.
