### ISSUE TITLE
Clean up sidebar nav for docs

### ISSUE THREAD

**Issue by suprenant** [cloud-gov/cg-site#643]
@suprenant commented on [Mon Dec 05 2016](https://github.com/18F/cg-dashboard/issues/796)

It's sometimes the case in the sidebar that that proper view is not highlighted. We want to fix this so users can easily navigate docs to find what they are looking for.

Implementation notes:
 - Find example of exhibition of each behavior
 - Determine and document priority/steps to fix
 - Fix accordingly 

Acceptance criteria:
- [ ] Docs pages should have proper highlight of current section
- [ ] Every section that is a parent section should have an arrow
- [ ] Arrow switching of open-close states behavior should be consistent (arrow indicating that parent session is open/closed does not currently consistently happen)

---

@suprenant commented on [Mon Dec 05 2016](https://github.com/18F/cg-dashboard/issues/796#issuecomment-265023083)

Slated for Sprint 8.5. Thought we had a similar issue on the board but can't find it at the moment. 

---

@thisisdano commented on [Tue Dec 06 2016](https://github.com/18F/cg-dashboard/issues/796#issuecomment-265233894)

- proper highlight of current section
- proper arrow switching of open-close states
- arrows for all sections with subsections

**Comment by brittag** [comment]
This isn't a problem anymore.
