### ISSUE TITLE
Idea for a quickstart tutorial

### ISSUE THREAD

**Issue by ultrasaurus** [cloud-gov/cg-site#65]
I did a little experimenting yesterday with CloudFoundry, Rails and ElasticSearch.  It took a little hunting and some help from @ozzyjohnson to get started, but it is actually quite easy.  I thought it might be nice to add a little tutorial to the docs for getting started with Rails (using what is free and doesn't require a billing code).  

Should something like this go into [Deploying Rails](https://docs.18f.gov/apps/rails/) or is there a better spot for it?

It would need a little text explanation for the steps, but here's my outline:

```
cf target -o sandbox
rails new myapp -O
or
rails new myapp --skip-activerecord

cd myapp
ln -s .gitignore .cfignore

edit Gemfile, add for better logging:
gem 'rails_12factor'

bundle
cf push myapp

http://myapp.cf.18f.us

cf logs       
```

then to add elasticsearch

```
cf create-service elasticsearch15 free eservice

add to Gemfile:

gem 'cf-app-utils'
gem 'elasticsearch'

bundle
```

I don't know if it needs a complete example, but this code snippet would have been useful for me:

```
require 'elasticsearch'
require 'cf-app-utils'
eservice = CF::App::Credentials.find_all_by_service_tag('eservice')
service_uri = eservice['uri']

client = Elasticsearch::Client.new host: service_uri, log: true
```

**Comment by afeld** [comment]
> I thought it might be nice to add a little tutorial to the docs

:+1: 

> Should something like this go into Deploying Rails

I'd prefer putting it on its own page.

> here's my outline

I wrote up some notes/steps for the training I did a few weeks ago:

https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit

which may be useful as part of this guide. Happy to collaborate on this!

**Comment by ozzyjohnson** [comment]
I think this should be made part of or at least prominently referenced from the Rails guide unless we expect services to be used by a minority of Rails apps.

Anecdotally, folks run through the guide for their language of of choice and don't readily consuming the separate docs about services / troubleshooting etc.

**Comment by ultrasaurus** [comment]
I think I forgot this part:

```
cf bind-service my-app eservice
```

**Comment by brittag** [comment]
Covered by the docs at https://docs.cloudfoundry.org/buildpacks/ruby/index.html such as https://docs.cloudfoundry.org/buildpacks/ruby/gsg-ror.html
