### ISSUE TITLE
New homepage copy requires tweak to chevron design

### ISSUE THREAD

**Issue by jameshupp** [cloud-gov/cg-site#657]
@vz3 @suprenant @thisisdano 

This needs to be resolved one way or another before #656 can be merged.

The new homepage copy reduces the number of homepage sections from 8 to 5. The chevron design of the homepage is disrupted by this change. The existing design follows these two patterns:

Color: blue (first/title section) -> white -> cream -> white -> black -> white -> cream -> white
Chevron shape between sections: down (first/title section) -> up -> up -> down -> down -> up -> up

With the new count of sections it looks like this:

Color: blue -> white -> cream -> white -> black
Chevron: down -> up -> up ->down

This presents a problem — the Contact section is black, which I don't think works. So in my PR on this I rearranged the scheme:

Color: blue -> white -> cream -> black -> white
Chevron: down -> up -> up -> up

The color change was intentional, and I think it works. The chevron change was accidental. But as you can see, there's a limitation in the way the classes interact that I wasn't counting on. The black chevron is broken.
<img width="1143" alt="screenshot_pr656_black-chevron" src="https://cloud.githubusercontent.com/assets/6314097/21457291/251563fa-c8fc-11e6-92b0-c5586ade22f4.png">

The code for the homepage in #656 contains the correct content. Whatever design adjustments you need to make can be merged into the [homepage_new_copy branch](https://github.com/18F/cg-site/tree/homepage_new_copy).

**Comment by suprenant** [comment]
@jameshupp is this still relevant given https://github.com/18F/cg-site/pull/656 is now merged?

**Comment by jameshupp** [comment]
@suprenant All good now! Addressed in #656
