### ISSUE TITLE
New homepage copy requires updated icon

### ISSUE THREAD

**Issue by jameshupp** [cloud-gov/cg-site#658]
@vz3 @suprenant @thisisdano 

This is part of #656. It is not totally essential before that PR can be merged, but it would be best if we could resolve this before mid-January.

The existing three-column iconography for the homepage doesn't really work for the new content. There is a possible three-column section, but as you'll see the the third hexagonal icon with the compass doesn't really represent that text.
<img width="1038" alt="screenshot_pr656_hexagon-icons-headers" src="https://cloud.githubusercontent.com/assets/6314097/21457464/865c6ae0-c8fd-11e6-9d80-2208f31252bc.png">

I'm okay with any resolution here: no columns, no icons, different icons, etc. Or even justification for leaving as is. The code for the homepage in #656 contains the correct content. Feel free to merge any changes you make here into the [homepage_new_copy branch](https://github.com/18F/cg-site/tree/homepage_new_copy).

**Comment by suprenant** [comment]
We removed the icons so are considering this done. @jameshupp please let us know if you have questions or need anything further here.
