### ISSUE TITLE
Explain how cloud.gov supports continuous delivery

### ISSUE THREAD

**Issue by nikzei** [cloud-gov/cg-site#715]
In order to help prospective and current cloud.gov customers deliver great digital services to their users by moving their services to a PaaS and continuously delivering changes to their users, we should publicly explain how using cloud.gov supports practicing continuous delivery in the context of government compliance requirements. This should also be helpful information for other cloud service providers, both ones who currently work in government contexts and ones who want to learn how to work in government contexts.

**Implementation sketch**

Take the [outline here](https://docs.google.com/document/d/1ATOOZpMVh7d6oKEJb3KaT2wT7oTqlkGnk5adPYSwGMc/edit) and flesh it out. This could be done by one person familiar with the principles of continuous delivery and how we build cloud.gov, or it could be done by a writer pairing with a subject matter expert (or a few). We have subject matter experts on the cloud.gov team and at 18F.

Once we pick this up, we should identify how best to publish this information, such as cloud.gov overview content and/or an 18F blog post.

It would be nice to review the draft with cloud.gov customers (both inside and outside 18F) to see if it they have feedback about it, especially since compliance requirements vary between agencies.

**Acceptance criteria**

- [ ] We have a fleshed-out draft that explains how cloud.gov uses and supports the use of continuous delivery in our government context.
- [ ] It's published!

**Comment by brittag** [comment]
Groomed this story and moved it to "ready"! :high_five:

**Comment by brittag** [comment]
This was a good idea, but we have a lot of other post ideas that would take priority over this one to address specific prospective user questions that we hear more often.
