### ISSUE TITLE
Relational Database page should reference cf-service-connect for GovCloud users

### ISSUE THREAD

**Issue by cnelson** [cloud-gov/cg-site#744]
Instead of the complicated steps listed under https://cloud.gov/docs/services/relational-database/#manually-access-a-database we should recommend GovCloud users use https://github.com/18F/cf-service-connect to access their databases

**Comment by nikzei** [comment]
I'm creating a card for this in Favro + closing this issue.

**Comment by brittag** [comment]
Link to card for easy cross-referencing: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3486
