### ISSUE TITLE
Learning and reference table has single right-aligned column

### ISSUE THREAD

**Issue by adborden** [cloud-gov/cg-site#789]
https://cloud.gov/docs/ has a table with a single column. We've changed the table styling to be left aligned except for the last column (right-aligned) which is an improvement for the majority of tables in the docs. Not only does this not work for tables with a single column, but a single column table doesn't really make sense. We should either add a second column or convert this table to a list.
![screenshot from 2017-02-22 17-09-20](https://cloud.githubusercontent.com/assets/509703/23240363/f4a4347a-f921-11e6-9825-67fe90e754c3.png)

**Comment by brittag** [comment]
Heh, this can be a list instead of a table - I just wanted it to look nicer than a list, but that was sort of clunky.

**Comment by brittag** [comment]
Fixed in https://github.com/18F/cg-site/issues/790!

**Comment by adborden** [comment]
:sunglasses: 

Feel free to open a bug against cg-style, the styles should look good in all contexts that they appear. Would be good to give more specifics about what makes it feel clunky to you.

**Comment by brittag** [comment]
Oh good question! I like the list style in general, but the current body content of https://cloud.gov/docs/ just looks a bit empty, since I haven't been sure what to put there. That's a pretty low-priority page though - it doesn't really _need_ to do much.
