### ISSUE TITLE
Site is only running one instance in production

### ISSUE THREAD

**Issue by cnelson** [cloud-gov/cg-site#793]
During a maintenance window to upgrade CF to version 252 the cloud.gov site was temporarily unavailable because this app is not configured to run multiple instances.

The manifest for this app should be updated to provision multiple instances, and we should probably review this site to makes sure it follows all the other recommendations in our production ready guide.

**Comment by mogul** [comment]
I'm confused... Do we address that by editing the manifest.yml here in GitHub, or is there something in the Concourse pipeline?

**Comment by cnelson** [comment]
Should just be the manifest update.  I'll try to resolve this (and a couple others I noticed, like fugacious) tomorrow.  Should be white-noise work.
