### ISSUE TITLE
Pull service broker descriptions from the brokers themselves

### ISSUE THREAD

**Issue by adborden** [cloud-gov/cg-site#798]
To avoid having to update service broker descriptions both in the docs and the service broker metadata, the docs should pull this information from the service brokers at build time. This also avoids the issue of the docs being out of sync from brokers.

https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1488240746012348 from @jmcarp:
> how about merging the `entity` hash from https://apidocs.cloudfoundry.org/252/services/list_all_service_plans_for_the_service.html  into the existing toml files on deploy?

This way, we could add custom metadata to docs (like support status) but keep descriptions in sync.

**Comment by adborden** [comment]
Might also add a note in the README or toml files indicating where the service broker metadata lives, since each is in it's own repository.

**Comment by mogul** [comment]
I really like this idea. Which squad do you think is best-suited to take on the work?

**Comment by adborden** [comment]
I'm not sure. This feature makes it easier to keep the dashboard, CLI, and docs consistent so it could fall under either the Navigator or Skyporter theme. But neither owns the repositories that house the actual metadata, so it could also be someone else.

**Comment by mogul** [comment]
OK. We're thinking now about how we might shake-up/mash-up the squads for the coming quarter and this is a good test-case for that.

**Comment by mogul** [comment]
We should see if we can have this include the buildpack information too.

**Comment by adborden** [comment]
Great idea, I've captured it in a separate story since it will be a different implementation. We don't even keep metadata on the buildpacks in cg-site from what I can tell.

**Comment by suprenant** [comment]
Closing this issue but keeping this card in Favro for future reference.
