### ISSUE TITLE
Document buildpack information from CF API

### ISSUE THREAD

**Issue by adborden** [cloud-gov/cg-site#812]
In the spirit of https://github.com/18F/cg-site/issues/798, we can provide up-to-date information about what buildpacks cloud.gov supports if we pull this information from the [CF API](https://apidocs.cloudfoundry.org/252/buildpacks/list_all_buildpacks.html). We might want to keep some extra metadata on the buildpacks in addition to what the API provides so that we can provide additional context (maybe documentation links or level of support).

An example response from `/v2/buildpacks`
```
{
  "total_results": 9,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "57ac3d01-9302-4161-896c-af7ec989e4b8",
        "url": "/v2/buildpacks/57ac3d01-9302-4161-896c-af7ec989e4b8",
        "created_at": "2016-06-09T17:52:31Z",
        "updated_at": "2017-02-24T01:17:10Z"
      },
      "entity": {
        "name": "staticfile_buildpack",
        "position": 1,
        "enabled": true,
        "locked": false,
        "filename": "staticfile_buildpack-cached-v1.3.17.zip"
      }
    },
    ...
  ]
}
```

It would be nice to parse the version information from the filename.

**Comment by brittag** [comment]
This is a cool idea since it could be automated and could offer more detailed info about the buildpacks, but since our buildpacks don't change very often (probably not more than once a year), this seems better to update manually rather than writing code that we'd have to maintain.
