### ISSUE TITLE
Old ssp at compliance.cloud.gov is confusing

### ISSUE THREAD

**Issue by hollyallen** [cloud-gov/cg-site#858]
I was recently fooled into thinking that the old SSP at compliance.cloud.gov was the real up to date one. I knew better, but still was fooled. It came up in google search results for a NIST control (probably "nist ra-5 container"). 

There is a note on the front page of the site that says it is not the up to date SSP, but I did not see that page until Bret told me about the note there.

I recommend removing this site for now, or adding the note to every page.

**Comment by brittag** [comment]
Thanks Holly! We agree - [we have a plan here to take it down](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-4263). I'll follow up on that.

**Comment by brittag** [comment]
We've taken down `compliance.cloud.gov`, so I'll close this issue.
