### ISSUE TITLE
cloud-gov-identity-provider.md does not explain how to retrieve OAuth2 secrets

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-site#864]
I noticed that [`cloud-gov-identity-provider.md`](https://github.com/18F/cg-site/blob/master/content/docs/services/cloud-gov-identity-provider.md) explains how to register an `oauth-client` service, but it doesn't provide any information about actually obtaining the client ID and client secret for the service, which are required to authenticate against it (they are mentioned in the [leveraging authentication](https://cloud.gov/docs/apps/leveraging-authentication/) section but no information is given on how they are to be obtained).

Fortunately, however, the page *does* link to the GitHub repo for uaa-credentials-broker, which has a nice ["usage" section](https://github.com/cloudfoundry-community/uaa-credentials-broker#usage) that explains how I need to use `cf service my-service-account` to get the fugacious link to my credentials.

Would it be useful to also put this information in `cloud-gov-identity-provider.md`? I am happy to submit a PR if so, just let me know!

**Comment by brittag** [comment]
Good point, thank you! Yes, we would be delighted to get a PR for this!
