### ISSUE TITLE
Service Level Agreements

### ISSUE THREAD

**Issue by aucjo01** [cloud-gov/cg-site#877]
Does cloud.gov come with any Service Level Agreements?
How are the SLAs tracked internally to insure success, proactive monitoring, quick problem resolution, etc.?
How are the SLAs reported to the customers of the cloud.gov service?
How can cloud.gov and its customers figure out is a problem is due to the customer's app versus the cloud.gov service?
Any and all SLA info is appreciated!

**Comment by brittag** [comment]
Thank you @aucjo01 for asking this! So far we've primarily been discussing these topics with prospective and current customers in conversations, and we plan to publish information on the cloud.gov website with a crystallized version of those conversations for easy review. We'll post a note on this issue when we have an update on that.

Our [cloud.gov StatusPage](https://cloudgov.statuspage.io/) may also be of interest - that's how we report planned and unplanned service disruptions to customers. It includes [a history of past disruptions](https://cloudgov.statuspage.io/history).

**Comment by mogul** [comment]
Closing as part of stale issue cleanup
