### ISSUE TITLE
Distinguish operations docs from general user docs: Troubleshooting SMTP edition

### ISSUE THREAD

**Issue by fureigh** [cloud-gov/cg-site#893]
**User stories:**
* As a cloud.gov user, I want to be able to follow the docs' instructions, so that I can accomplish what I came to do without accidentally following false paths.
* As a cloud.gov team member doing support, I want a reliable set of instructions that are reliably applicable to users, so that I can give users accurate guidance.

**Context:**
There's a larger question about whether operations docs should be separate from the general user docs, but it'd take a megaticket to execute on that. :) We can start small, by clearly stating when something is 18F-specific.

Prompted by the references to #infrastructure, which outsiders can't access, and Mandrill, which we're not currently recommending, on the [Troubleshooting SMTP](https://github.com/18F/cg-site/blob/f996eb07a430c082cf618ecdc2c65a203182f156/content/docs/ops/runbook/troubleshooting-smtp.md) page.

**Comment by brittag** [comment]
All of the pages in /docs/ops/ are specific to the cloud.gov team and not expected to be usable by people outside 18F, other than /docs/ops/repos/. Sounds like we might need a tiny template note at the top of each /docs/ops/ page in case people end up there without that context.
