### ISSUE TITLE
Remove content/docs/apps/govcloud.md once the login page stops using the URL.

### ISSUE THREAD

**Issue by jcscottiii** [cloud-gov/cg-site#896]
Once the login page stops using the URL to the GovCloud page, we should remove it. It is at `content/docs/apps/govcloud.md`

![image](https://cloud.githubusercontent.com/assets/7788930/26218368/bbf55100-3bd8-11e7-8781-9e13c6451935.png)

**Comment by jcscottiii** [comment]
Should also update anywhere else that's using it: https://github.com/search?p=1&q=%22%2Fdocs%2Fapps%2Fgovcloud%2F%22&type=Code&utf8=%E2%9C%93

**Comment by brittag** [comment]
Filed a PR at https://github.com/18F/uaa-customized-boshrelease/pull/9

**Comment by brittag** [comment]
We still need to remove this page. :D

**Comment by jcscottiii** [comment]
Whoops. jumped ahead of myself!

**Comment by brittag** [comment]
That change is deployed, so the login page no longer links to the GovCloud page. We're free to remove the GovCloud page (or redirect it).
