### ISSUE TITLE
Script mention in secrets doc is missing

### ISSUE THREAD

**Issue by cnelson** [cloud-gov/cg-site#941]
@rogeruiz / @wjwoodson - I notice the [docs mention a `get-all-cf-deployers.sh` script ](https://github.com/18F/cg-site/blame/master/content/docs/ops/runbook/rotating-secrets.md#L145)but I don't see in the `cg-scripts` repo.  Where can I find it?

**Comment by rogeruiz** [comment]
closed by 18F/cg-scripts#52
