### ISSUE TITLE
Write up instructions for accessing a DB over cf-ssh

### ISSUE THREAD

**Issue by dhcole** [cloud-gov/cg-site#99]
Approach is generally,
1. `cf-ssh APP_NAME`
2. `curl https://s3.amazonaws.com/18f-cf-cli/psql-9.4.4-ubuntu-14.04.tar.gz | tar xvz`
3. `./psql/bin/psql $DATABASE_URL`

**Comment by dhcole** [comment]
h/t to @pkarman for building from source and uploading the compiled assets

**Comment by dhcole** [comment]
Where is the right place to host the tar file?

**Comment by afeld** [comment]
`cf-ssh` is uploaded as a release at https://github.com/18F/cloud-foundry-scripts/releases/ ... there's also an `18f-cf-cli` bucket on S3.

**Comment by pkarman** [comment]
@afeld thanks, updated url to: https://s3.amazonaws.com/18f-cf-cli/psql-9.4.4-ubuntu-14.04.tar.gz

**Comment by afeld** [comment]
:shipit:

**Comment by dlapiduz** [comment]
@afeld this is not a PR :)
